slice_name: Chatbots
description: null
certified_by: null
certification_details: null
viz_type: table
params:
  datasource: 141__table
  viz_type: table
  slice_id: 121
  query_mode: raw
  groupby: []
  temporal_columns_lookup: {}
  all_columns:
  - chatsession_agent
  - chatsession_title
  - courserun_readable_id
  - chatsession_object_id
  - user_email
  - user_id
  - user_full_name
  - chatsession_thread_id
  - checkpoint_step
  - human_message
  - agent_message
  - parent_checkpoint_id
  - chatsession_created_on
  - chatsession_updated_on
  - checkpoint_metadata
  percent_metrics: []
  adhoc_filters: []
  order_by_cols: []
  order_desc: true
  row_limit: 1000
  server_page_length: 10
  table_timestamp_format: smart_date
  allow_render_html: true
  show_cell_bars: true
  color_pn: true
  comparison_color_scheme: Green
  comparison_type: values
  extra_form_data: {}
  dashboards:
  - 54
query_context: '{"datasource":{"id":141,"type":"table"},"force":false,"queries":[{"filters":[],"extras":{"having":"","where":""},"applied_time_extras":{},"columns":["chatsession_agent","chatsession_title","courserun_readable_id","chatsession_object_id","user_email","user_id","user_full_name","chatsession_thread_id","checkpoint_step","human_message","agent_message","parent_checkpoint_id","chatsession_created_on","chatsession_updated_on","checkpoint_metadata"],"orderby":[],"annotation_layers":[],"row_limit":1000,"series_limit":0,"order_desc":true,"url_params":{},"custom_params":{},"custom_form_data":{},"post_processing":[],"time_offsets":[]}],"form_data":{"datasource":"141__table","viz_type":"table","slice_id":121,"query_mode":"raw","groupby":[],"temporal_columns_lookup":{},"all_columns":["chatsession_agent","chatsession_title","courserun_readable_id","chatsession_object_id","user_email","user_id","user_full_name","chatsession_thread_id","checkpoint_step","human_message","agent_message","parent_checkpoint_id","chatsession_created_on","chatsession_updated_on","checkpoint_metadata"],"percent_metrics":[],"adhoc_filters":[],"order_by_cols":[],"order_desc":true,"row_limit":1000,"server_page_length":10,"table_timestamp_format":"smart_date","allow_render_html":true,"show_cell_bars":true,"color_pn":true,"comparison_color_scheme":"Green","comparison_type":"values","extra_form_data":{},"dashboards":[54],"force":false,"result_format":"json","result_type":"full","include_time":false},"result_format":"json","result_type":"full"}'
cache_timeout: null
uuid: 90099854-5b34-4d06-926c-f58f42b2d69e
version: 1.0.0
dataset_uuid: f1ec896e-86d4-451a-84cc-841d234e70a6
