---
slice_name: Chatbot Usage By Course Section and Subsection
description:
certified_by:
certification_details:
viz_type: table
params:
  datasource: 154__table
  viz_type: table
  query_mode: aggregate
  groupby:
  - section_title
  - subsection_title
  temporal_columns_lookup:
    activity_date: true
  metrics:
  - expressionType: SIMPLE
    column:
      advanced_data_type:
      certification_details:
      certified_by:
      column_name: chatbot_used_count
      description:
      expression: ''
      filterable: true
      groupby: true
      id: 2284
      is_certified: false
      is_dttm: false
      python_date_format:
      type: BIGINT
      type_generic: 0
      verbose_name:
      warning_markdown:
    aggregate: SUM
    sqlExpression:
    datasourceWarning: false
    hasCustomLabel: false
    label: SUM(chatbot_used_count)
    optionName: metric_ltm3gotcgtb_i9j5lmpw90e
  all_columns: []
  percent_metrics: []
  adhoc_filters:
  - clause: WHERE
    subject: activity_date
    operator: TEMPORAL_RANGE
    comparator: No filter
    expressionType: SIMPLE
  order_by_cols: []
  row_limit: 1000
  table_timestamp_format: smart_date
  allow_render_html: true
  show_cell_bars: true
  color_pn: true
  comparison_color_scheme: Green
  comparison_type: values
  extra_form_data: {}
  dashboards: []
query_context: '{"datasource":{"id":154,"type":"table"},"force":false,"queries":[{"filters":[{"col":"activity_date","op":"TEMPORAL_RANGE","val":"No
  filter"}],"extras":{"having":"","where":""},"applied_time_extras":{},"columns":["section_title","subsection_title"],"metrics":[{"expressionType":"SIMPLE","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"chatbot_used_count","description":null,"expression":"","filterable":true,"groupby":true,"id":2284,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":"BIGINT","type_generic":0,"verbose_name":null,"warning_markdown":null},"aggregate":"SUM","sqlExpression":null,"datasourceWarning":false,"hasCustomLabel":false,"label":"SUM(chatbot_used_count)","optionName":"metric_ltm3gotcgtb_i9j5lmpw90e"}],"orderby":[[{"expressionType":"SIMPLE","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"chatbot_used_count","description":null,"expression":"","filterable":true,"groupby":true,"id":2284,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":"BIGINT","type_generic":0,"verbose_name":null,"warning_markdown":null},"aggregate":"SUM","sqlExpression":null,"datasourceWarning":false,"hasCustomLabel":false,"label":"SUM(chatbot_used_count)","optionName":"metric_ltm3gotcgtb_i9j5lmpw90e"},false]],"annotation_layers":[],"row_limit":1000,"series_limit":0,"order_desc":true,"url_params":{},"custom_params":{},"custom_form_data":{},"post_processing":[],"time_offsets":[]}],"form_data":{"datasource":"154__table","viz_type":"table","query_mode":"aggregate","groupby":["section_title","subsection_title"],"temporal_columns_lookup":{"activity_date":true},"metrics":[{"expressionType":"SIMPLE","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"chatbot_used_count","description":null,"expression":"","filterable":true,"groupby":true,"id":2284,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":"BIGINT","type_generic":0,"verbose_name":null,"warning_markdown":null},"aggregate":"SUM","sqlExpression":null,"datasourceWarning":false,"hasCustomLabel":false,"label":"SUM(chatbot_used_count)","optionName":"metric_ltm3gotcgtb_i9j5lmpw90e"}],"all_columns":[],"percent_metrics":[],"adhoc_filters":[{"clause":"WHERE","subject":"activity_date","operator":"TEMPORAL_RANGE","comparator":"No
  filter","expressionType":"SIMPLE"}],"order_by_cols":[],"row_limit":1000,"table_timestamp_format":"smart_date","allow_render_html":true,"show_cell_bars":true,"color_pn":true,"comparison_color_scheme":"Green","comparison_type":"values","extra_form_data":{},"dashboards":[],"force":false,"result_format":"json","result_type":"full"},"result_format":"json","result_type":"full"}'
cache_timeout:
uuid: 9ad6f248-c9cd-42bd-9285-5dbe6d30d5c3
version: 1.0.0
dataset_uuid: 8c2b6f11-28f8-4353-8e43-6c53ea6b1d91
