slice_name: Chatbots
description: null
certified_by: null
certification_details: null
viz_type: table
params:
  adhoc_filters:
  - clause: WHERE
    comparator: VideoGPTBot
    datasourceWarning: false
    expressionType: SIMPLE
    filterOptionName: filter_bqsyyf0759m_oz3z7w8aqd
    isExtra: false
    isNew: false
    operator: ==
    operatorId: EQUALS
    sqlExpression: null
    subject: chatsession_agent
  all_columns:
  - chatsession_agent
  - chatsession_title
  - courserun_readable_id
  - chatsession_object_id
  - user_email
  - user_id
  - user_full_name
  - chatsession_thread_id
  - checkpoint_step
  - human_message
  - agent_message
  - parent_checkpoint_id
  - chatsession_created_on
  - chatsession_updated_on
  - checkpoint_metadata
  allow_render_html: true
  annotation_layers: []
  color_pn: true
  comparison_type: values
  dashboards: []
  datasource: 59__table
  extra_form_data: {}
  groupby: []
  order_by_cols: []
  order_desc: true
  percent_metrics: []
  query_mode: raw
  row_limit: 1000
  server_page_length: 10
  show_cell_bars: true
  slice_id: 121
  table_timestamp_format: smart_date
  temporal_columns_lookup: {}
  viz_type: table
query_context: '{"datasource": {"id": 59, "type": "table"}, "force": false, "queries":
  [{"filters": [{"col": "chatsession_agent", "op": "==", "val": "VideoGPTBot"}], "extras":
  {"having": "", "where": ""}, "applied_time_extras": {}, "columns": ["chatsession_agent",
  "chatsession_title", "courserun_readable_id", "chatsession_object_id", "user_email",
  "user_id", "user_full_name", "chatsession_thread_id", "checkpoint_step", "human_message",
  "agent_message", "parent_checkpoint_id", "chatsession_created_on", "chatsession_updated_on",
  "checkpoint_metadata"], "orderby": [], "annotation_layers": [], "row_limit": 1000,
  "series_limit": 0, "order_desc": true, "url_params": {}, "custom_params": {}, "custom_form_data":
  {}, "post_processing": [], "time_offsets": []}], "form_data": {"datasource": "59__table",
  "viz_type": "table", "slice_id": 121, "query_mode": "raw", "groupby": [], "temporal_columns_lookup":
  {}, "all_columns": ["chatsession_agent", "chatsession_title", "courserun_readable_id",
  "chatsession_object_id", "user_email", "user_id", "user_full_name", "chatsession_thread_id",
  "checkpoint_step", "human_message", "agent_message", "parent_checkpoint_id", "chatsession_created_on",
  "chatsession_updated_on", "checkpoint_metadata"], "percent_metrics": [], "adhoc_filters":
  [{"expressionType": "SIMPLE", "subject": "chatsession_agent", "operator": "==",
  "operatorId": "EQUALS", "comparator": "VideoGPTBot", "clause": "WHERE", "sqlExpression":
  null, "isExtra": false, "isNew": false, "datasourceWarning": false, "filterOptionName":
  "filter_bqsyyf0759m_oz3z7w8aqd"}], "order_by_cols": [], "order_desc": true, "row_limit":
  1000, "server_page_length": 10, "table_timestamp_format": "smart_date", "allow_render_html":
  true, "show_cell_bars": true, "color_pn": true, "comparison_type": "values", "extra_form_data":
  {}, "dashboards": [], "force": false, "result_format": "json", "result_type": "full",
  "include_time": false}, "result_format": "json", "result_type": "full"}'
cache_timeout: null
uuid: 37348ff8-4ec6-4b33-a2a6-5d8d8bf62356
version: 1.0.0
dataset_uuid: f1ec896e-86d4-451a-84cc-841d234e70a6
