slice_name: Content Engagement - Weekly
description: null
certified_by: null
certification_details: null
viz_type: echarts_timeseries_line
params:
  datasource: 10__table
  viz_type: echarts_timeseries_line
  slice_id: 72
  x_axis:
    expressionType: SQL
    label: courseactivity_date
    sqlExpression: courseactivity_date
  time_grain_sqla: P1W
  xAxisForceCategorical: true
  metrics:
  - aggregate: null
    column: null
    datasourceWarning: false
    expressionType: SQL
    hasCustomLabel: true
    label: Watched_a_video
    optionName: metric_nn1wefuu2db_mpukfx7sm3p
    sqlExpression: COUNT(DISTINCT (CASE WHEN num_video_played> 0 THEN user_username
      ELSE null END))
  - aggregate: null
    column: null
    datasourceWarning: false
    expressionType: SQL
    hasCustomLabel: true
    label: Tried_a_problem
    optionName: metric_5dkp4rc3smx_j5uh6anrsrg
    sqlExpression: COUNT(DISTINCT(case when num_problem_submitted> 0 then user_username
      else null end))
  - aggregate: null
    column: null
    datasourceWarning: false
    expressionType: SQL
    hasCustomLabel: true
    label: Participated_In_Discussion
    optionName: metric_nyeto5r6o1_a3bqgmcrvng
    sqlExpression: COUNT(DISTINCT(case when num_discussion_participated> 0 then user_username
      else null end))
  - aggregate: COUNT_DISTINCT
    column:
      advanced_data_type: null
      certification_details: null
      certified_by: null
      column_name: user_username
      description: null
      expression: null
      filterable: true
      groupby: true
      id: 123
      is_certified: false
      is_dttm: false
      python_date_format: null
      type: VARCHAR
      type_generic: 1
      verbose_name: null
      warning_markdown: null
    datasourceWarning: false
    expressionType: SIMPLE
    hasCustomLabel: true
    label: Learner_count
    optionName: metric_455ovz8nu4s_6b2gv5odit3
    sqlExpression: null
  groupby: []
  adhoc_filters:
  - clause: WHERE
    comparator: No filter
    datasourceWarning: false
    expressionType: SIMPLE
    filterOptionName: filter_vmnxg0351v_lspf9hzyi4i
    isExtra: false
    isNew: false
    operator: TEMPORAL_RANGE
    sqlExpression: null
    subject: courseactivity_date
  timeseries_limit_metric:
    aggregate: MAX
    column:
      advanced_data_type: null
      certification_details: null
      certified_by: null
      column_name: courseactivity_date
      description: null
      expression: null
      filterable: true
      groupby: true
      id: 122
      is_certified: false
      is_dttm: true
      python_date_format: null
      type: DATE
      type_generic: 2
      verbose_name: null
      warning_markdown: null
    datasourceWarning: false
    expressionType: SIMPLE
    hasCustomLabel: false
    label: MAX(courseactivity_date)
    optionName: metric_okhl5d9h4c_ah7l934rd7f
    sqlExpression: null
  order_desc: true
  row_limit: 10000
  truncate_metric: false
  show_empty_columns: false
  comparison_type: values
  annotation_layers: []
  forecastPeriods: 10
  forecastInterval: 0.8
  x_axis_title_margin: 15
  y_axis_title_margin: 15
  y_axis_title_position: Left
  sort_series_type: sum
  color_scheme: supersetColors
  time_shift_color: true
  show_value: false
  only_total: true
  area: false
  opacity: 0.2
  markerEnabled: true
  markerSize: 6
  zoomable: true
  show_legend: true
  legendType: scroll
  legendOrientation: top
  x_axis_time_format: smart_date
  xAxisLabelInterval: auto
  rich_tooltip: true
  showTooltipTotal: false
  showTooltipPercentage: false
  tooltipTimeFormat: smart_date
  y_axis_format: SMART_NUMBER
  logAxis: false
  truncateXAxis: true
  y_axis_bounds:
  - null
  - null
  extra_form_data: {}
  dashboards: []
query_context: '{"datasource":{"id":10,"type":"table"},"force":false,"queries":[{"filters":[{"col":"courseactivity_date","op":"TEMPORAL_RANGE","val":"No
  filter"}],"extras":{"time_grain_sqla":"P1W","having":"","where":""},"applied_time_extras":{},"columns":[{"timeGrain":"P1W","columnType":"BASE_AXIS","expressionType":"SQL","label":"courseactivity_date","sqlExpression":"courseactivity_date"}],"metrics":[{"aggregate":null,"column":null,"datasourceWarning":false,"expressionType":"SQL","hasCustomLabel":true,"label":"Watched_a_video","optionName":"metric_nn1wefuu2db_mpukfx7sm3p","sqlExpression":"COUNT(DISTINCT
  (CASE WHEN num_video_played> 0 THEN user_username ELSE null END))"},{"aggregate":null,"column":null,"datasourceWarning":false,"expressionType":"SQL","hasCustomLabel":true,"label":"Tried_a_problem","optionName":"metric_5dkp4rc3smx_j5uh6anrsrg","sqlExpression":"COUNT(DISTINCT(case
  when num_problem_submitted> 0 then user_username else null end))"},{"aggregate":null,"column":null,"datasourceWarning":false,"expressionType":"SQL","hasCustomLabel":true,"label":"Participated_In_Discussion","optionName":"metric_nyeto5r6o1_a3bqgmcrvng","sqlExpression":"COUNT(DISTINCT(case
  when num_discussion_participated> 0 then user_username else null end))"},{"aggregate":"COUNT_DISTINCT","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"user_username","description":null,"expression":null,"filterable":true,"groupby":true,"id":123,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":"VARCHAR","type_generic":1,"verbose_name":null,"warning_markdown":null},"datasourceWarning":false,"expressionType":"SIMPLE","hasCustomLabel":true,"label":"Learner_count","optionName":"metric_455ovz8nu4s_6b2gv5odit3","sqlExpression":null}],"orderby":[[{"aggregate":"MAX","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"courseactivity_date","description":null,"expression":null,"filterable":true,"groupby":true,"id":122,"is_certified":false,"is_dttm":true,"python_date_format":null,"type":"DATE","type_generic":2,"verbose_name":null,"warning_markdown":null},"datasourceWarning":false,"expressionType":"SIMPLE","hasCustomLabel":false,"label":"MAX(courseactivity_date)","optionName":"metric_okhl5d9h4c_ah7l934rd7f","sqlExpression":null},false]],"annotation_layers":[],"row_limit":10000,"series_columns":[],"series_limit":0,"series_limit_metric":{"aggregate":"MAX","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"courseactivity_date","description":null,"expression":null,"filterable":true,"groupby":true,"id":122,"is_certified":false,"is_dttm":true,"python_date_format":null,"type":"DATE","type_generic":2,"verbose_name":null,"warning_markdown":null},"datasourceWarning":false,"expressionType":"SIMPLE","hasCustomLabel":false,"label":"MAX(courseactivity_date)","optionName":"metric_okhl5d9h4c_ah7l934rd7f","sqlExpression":null},"group_others_when_limit_reached":false,"order_desc":true,"url_params":{},"custom_params":{},"custom_form_data":{},"time_offsets":[],"post_processing":[{"operation":"pivot","options":{"index":["courseactivity_date"],"columns":[],"aggregates":{"Watched_a_video":{"operator":"mean"},"Tried_a_problem":{"operator":"mean"},"Participated_In_Discussion":{"operator":"mean"},"Learner_count":{"operator":"mean"}},"drop_missing_columns":true}},{"operation":"flatten"}]}],"form_data":{"datasource":"10__table","viz_type":"echarts_timeseries_line","slice_id":72,"x_axis":{"expressionType":"SQL","label":"courseactivity_date","sqlExpression":"courseactivity_date"},"time_grain_sqla":"P1W","xAxisForceCategorical":true,"metrics":[{"aggregate":null,"column":null,"datasourceWarning":false,"expressionType":"SQL","hasCustomLabel":true,"label":"Watched_a_video","optionName":"metric_nn1wefuu2db_mpukfx7sm3p","sqlExpression":"COUNT(DISTINCT
  (CASE WHEN num_video_played> 0 THEN user_username ELSE null END))"},{"aggregate":null,"column":null,"datasourceWarning":false,"expressionType":"SQL","hasCustomLabel":true,"label":"Tried_a_problem","optionName":"metric_5dkp4rc3smx_j5uh6anrsrg","sqlExpression":"COUNT(DISTINCT(case
  when num_problem_submitted> 0 then user_username else null end))"},{"aggregate":null,"column":null,"datasourceWarning":false,"expressionType":"SQL","hasCustomLabel":true,"label":"Participated_In_Discussion","optionName":"metric_nyeto5r6o1_a3bqgmcrvng","sqlExpression":"COUNT(DISTINCT(case
  when num_discussion_participated> 0 then user_username else null end))"},{"aggregate":"COUNT_DISTINCT","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"user_username","description":null,"expression":null,"filterable":true,"groupby":true,"id":123,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":"VARCHAR","type_generic":1,"verbose_name":null,"warning_markdown":null},"datasourceWarning":false,"expressionType":"SIMPLE","hasCustomLabel":true,"label":"Learner_count","optionName":"metric_455ovz8nu4s_6b2gv5odit3","sqlExpression":null}],"groupby":[],"adhoc_filters":[{"clause":"WHERE","comparator":"No
  filter","datasourceWarning":false,"expressionType":"SIMPLE","filterOptionName":"filter_vmnxg0351v_lspf9hzyi4i","isExtra":false,"isNew":false,"operator":"TEMPORAL_RANGE","sqlExpression":null,"subject":"courseactivity_date"}],"timeseries_limit_metric":{"aggregate":"MAX","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"courseactivity_date","description":null,"expression":null,"filterable":true,"groupby":true,"id":122,"is_certified":false,"is_dttm":true,"python_date_format":null,"type":"DATE","type_generic":2,"verbose_name":null,"warning_markdown":null},"datasourceWarning":false,"expressionType":"SIMPLE","hasCustomLabel":false,"label":"MAX(courseactivity_date)","optionName":"metric_okhl5d9h4c_ah7l934rd7f","sqlExpression":null},"order_desc":true,"row_limit":10000,"truncate_metric":false,"show_empty_columns":false,"comparison_type":"values","annotation_layers":[],"forecastPeriods":10,"forecastInterval":0.8,"x_axis_title_margin":15,"y_axis_title_margin":15,"y_axis_title_position":"Left","sort_series_type":"sum","color_scheme":"supersetColors","time_shift_color":true,"show_value":false,"only_total":true,"area":false,"opacity":0.2,"markerEnabled":true,"markerSize":6,"zoomable":true,"show_legend":true,"legendType":"scroll","legendOrientation":"top","x_axis_time_format":"smart_date","xAxisLabelInterval":"auto","rich_tooltip":true,"showTooltipTotal":false,"showTooltipPercentage":false,"tooltipTimeFormat":"smart_date","y_axis_format":"SMART_NUMBER","logAxis":false,"truncateXAxis":true,"y_axis_bounds":[null,null],"extra_form_data":{},"dashboards":[],"force":false,"result_format":"json","result_type":"full"},"result_format":"json","result_type":"full"}'
cache_timeout: null
uuid: fb5f7dd7-f56e-44f4-97f6-ed0c3804382f
version: 1.0.0
dataset_uuid: e7330108-bdfa-4ff0-8ca3-084d7e8cbda8
