---
slice_name: Course AI Chatbot Table Metadata
description:
certified_by:
certification_details:
viz_type: table
params:
  datasource: 113__table
  viz_type: table
  slice_id: 130
  query_mode: raw
  groupby: []
  temporal_columns_lookup:
    created_on: true
    changed_on: true
  all_columns:
  - expressionType: SQL
    label: last_updated_on (in UTC)
    sqlExpression: changed_on
  percent_metrics: []
  adhoc_filters:
  - clause: WHERE
    comparator: No filter
    datasourceWarning: false
    expressionType: SIMPLE
    filterOptionName: filter_3dsv4wp8vgc_o60z9rhbuj
    isExtra: false
    isNew: false
    operator: TEMPORAL_RANGE
    sqlExpression:
    subject: created_on
  - clause: WHERE
    comparator:
    - chatbot_usage_report
    datasourceWarning: false
    expressionType: SIMPLE
    filterOptionName: filter_xmpn9aiwaq_uobmk9lebdm
    isExtra: false
    isNew: false
    operator: IN
    operatorId: IN
    sqlExpression:
    subject: table_name
  order_by_cols: []
  row_limit: 1000
  table_timestamp_format: smart_date
  allow_render_html: true
  show_cell_bars: true
  color_pn: true
  comparison_color_scheme: Green
  extra_form_data: {}
  dashboards:
  - 55
query_context: '{"datasource":{"id":113,"type":"table"},"force":false,"queries":[{"filters":[{"col":"created_on","op":"TEMPORAL_RANGE","val":"No
  filter"},{"col":"table_name","op":"IN","val":["chatbot_usage_report"]}],"extras":{"having":"","where":""},"applied_time_extras":{},"columns":[{"expressionType":"SQL","label":"last_updated_on
  (in UTC)","sqlExpression":"changed_on"}],"orderby":[],"annotation_layers":[],"row_limit":1000,"series_limit":0,"order_desc":true,"url_params":{},"custom_params":{},"custom_form_data":{},"post_processing":[],"time_offsets":[]}],"form_data":{"datasource":"113__table","viz_type":"table","slice_id":130,"query_mode":"raw","groupby":[],"temporal_columns_lookup":{"created_on":true,"changed_on":true},"all_columns":[{"expressionType":"SQL","label":"last_updated_on
  (in UTC)","sqlExpression":"changed_on"}],"percent_metrics":[],"adhoc_filters":[{"clause":"WHERE","comparator":"No
  filter","datasourceWarning":false,"expressionType":"SIMPLE","filterOptionName":"filter_3dsv4wp8vgc_o60z9rhbuj","isExtra":false,"isNew":false,"operator":"TEMPORAL_RANGE","sqlExpression":null,"subject":"created_on"},{"clause":"WHERE","comparator":["chatbot_usage_report"],"datasourceWarning":false,"expressionType":"SIMPLE","filterOptionName":"filter_xmpn9aiwaq_uobmk9lebdm","isExtra":false,"isNew":false,"operator":"IN","operatorId":"IN","sqlExpression":null,"subject":"table_name"}],"order_by_cols":[],"row_limit":1000,"table_timestamp_format":"smart_date","allow_render_html":true,"show_cell_bars":true,"color_pn":true,"comparison_color_scheme":"Green","extra_form_data":{},"dashboards":[55],"force":false,"result_format":"json","result_type":"full","include_time":false},"result_format":"json","result_type":"full"}'
cache_timeout: -1
uuid: 3ac40124-8856-4823-8b81-4be13975e103
version: 1.0.0
dataset_uuid: 3b10e411-e497-4e8c-8132-08f673e8d72d
