slice_name: Daily Learner Enrollment- All Courses
description: null
certified_by: null
certification_details: null
viz_type: echarts_timeseries_bar
params:
  adhoc_filters: []
  annotation_layers: []
  color_scheme: supersetColors
  comparison_type: values
  dashboards: []
  datasource: 6__table
  extra_form_data: {}
  forecastInterval: 0.8
  forecastPeriods: 10
  groupby: []
  legendOrientation: top
  legendType: scroll
  metrics:
  - aggregate: null
    column: null
    datasourceWarning: false
    expressionType: SQL
    hasCustomLabel: true
    label: Verified_Count
    optionName: metric_sro1akhey7m_2hewdplnpqn
    sqlExpression: sum(case when courserunenrollment_enrollment_mode= 'verified' then
      1 else 0 end)
  - aggregate: null
    column: null
    datasourceWarning: false
    expressionType: SQL
    hasCustomLabel: true
    label: Audit_Count
    optionName: metric_h6b5qcemebr_cgvckf11ndw
    sqlExpression: 'sum(case when courserunenrollment_enrollment_mode= ''audit'' then
      1 else 0 end) '
  - aggregate: null
    column: null
    datasourceWarning: false
    expressionType: SQL
    hasCustomLabel: true
    label: Total_Enrollment_count
    optionName: metric_non11autol_nyiwujsq2rq
    sqlExpression: count(*)
  only_total: true
  order_desc: true
  orientation: vertical
  rich_tooltip: true
  rolling_type: null
  row_limit: 10000
  show_empty_columns: true
  show_legend: true
  sort_series_type: sum
  time_grain_sqla: P1D
  tooltipTimeFormat: smart_date
  truncate_metric: true
  viz_type: echarts_timeseries_bar
  x_axis:
    expressionType: SQL
    label: Enrollment_Date
    sqlExpression: cast(substring(courserunenrollment_created_on, 1, 10) as date)
  x_axis_sort: name
  x_axis_sort_asc: true
  x_axis_time_format: smart_date
  x_axis_title_margin: 15
  y_axis_bounds:
  - null
  - null
  y_axis_format: SMART_NUMBER
  y_axis_title_margin: 15
  y_axis_title_position: Left
query_context: '{"datasource":{"id":6,"type":"table"},"force":false,"queries":[{"filters":[],"extras":{"having":"","where":""},"applied_time_extras":{},"columns":[{"timeGrain":"P1D","columnType":"BASE_AXIS","label":"Enrollment_Date","sqlExpression":"cast(substring(courserunenrollment_created_on,
  1, 10) as date)","expressionType":"SQL"}],"metrics":[{"expressionType":"SQL","sqlExpression":"sum(case
  when courserunenrollment_enrollment_mode= ''verified'' then 1 else 0 end)","column":null,"aggregate":null,"datasourceWarning":false,"hasCustomLabel":true,"label":"Verified_Count","optionName":"metric_sro1akhey7m_2hewdplnpqn"},{"expressionType":"SQL","sqlExpression":"sum(case
  when courserunenrollment_enrollment_mode= ''audit'' then 1 else 0 end) ","column":null,"aggregate":null,"datasourceWarning":false,"hasCustomLabel":true,"label":"Audit_Count","optionName":"metric_h6b5qcemebr_cgvckf11ndw"},{"expressionType":"SQL","sqlExpression":"count(*)","column":null,"aggregate":null,"datasourceWarning":false,"hasCustomLabel":true,"label":"Total_Enrollment_count","optionName":"metric_non11autol_nyiwujsq2rq"}],"orderby":[[{"expressionType":"SQL","sqlExpression":"sum(case
  when courserunenrollment_enrollment_mode= ''verified'' then 1 else 0 end)","column":null,"aggregate":null,"datasourceWarning":false,"hasCustomLabel":true,"label":"Verified_Count","optionName":"metric_sro1akhey7m_2hewdplnpqn"},false]],"annotation_layers":[],"row_limit":10000,"series_columns":[],"series_limit":0,"order_desc":true,"url_params":{},"custom_params":{},"custom_form_data":{},"time_offsets":[],"post_processing":[{"operation":"pivot","options":{"index":["Enrollment_Date"],"columns":[],"aggregates":{"Verified_Count":{"operator":"mean"},"Audit_Count":{"operator":"mean"},"Total_Enrollment_count":{"operator":"mean"}},"drop_missing_columns":false}},{"operation":"flatten"}]}],"form_data":{"datasource":"6__table","viz_type":"echarts_timeseries_bar","x_axis":{"label":"Enrollment_Date","sqlExpression":"cast(substring(courserunenrollment_created_on,
  1, 10) as date)","expressionType":"SQL"},"time_grain_sqla":"P1D","x_axis_sort_asc":true,"x_axis_sort_series":"name","x_axis_sort_series_ascending":true,"metrics":[{"expressionType":"SQL","sqlExpression":"sum(case
  when courserunenrollment_enrollment_mode= ''verified'' then 1 else 0 end)","column":null,"aggregate":null,"datasourceWarning":false,"hasCustomLabel":true,"label":"Verified_Count","optionName":"metric_sro1akhey7m_2hewdplnpqn"},{"expressionType":"SQL","sqlExpression":"sum(case
  when courserunenrollment_enrollment_mode= ''audit'' then 1 else 0 end) ","column":null,"aggregate":null,"datasourceWarning":false,"hasCustomLabel":true,"label":"Audit_Count","optionName":"metric_h6b5qcemebr_cgvckf11ndw"},{"expressionType":"SQL","sqlExpression":"count(*)","column":null,"aggregate":null,"datasourceWarning":false,"hasCustomLabel":true,"label":"Total_Enrollment_count","optionName":"metric_non11autol_nyiwujsq2rq"}],"groupby":[],"adhoc_filters":[],"order_desc":true,"row_limit":10000,"truncate_metric":true,"show_empty_columns":true,"rolling_type":null,"comparison_type":"values","annotation_layers":[],"forecastPeriods":10,"forecastInterval":0.8,"orientation":"vertical","x_axis_title_margin":15,"y_axis_title_margin":15,"y_axis_title_position":"Left","sort_series_type":"sum","color_scheme":"supersetColors","only_total":true,"show_legend":true,"legendType":"scroll","legendOrientation":"top","x_axis_time_format":"smart_date","y_axis_format":"SMART_NUMBER","y_axis_bounds":[null,null],"rich_tooltip":true,"tooltipTimeFormat":"smart_date","extra_form_data":{},"dashboards":[],"force":false,"result_format":"json","result_type":"full"},"result_format":"json","result_type":"full"}'
cache_timeout: null
uuid: 65762bf7-1c08-4abb-ad17-e569311a67d0
version: 1.0.0
