slice_name: Data Detail Discussion
description: null
certified_by: null
certification_details: null
viz_type: table
params:
  datasource: 110__table
  viz_type: table
  query_mode: raw
  groupby: []
  time_grain_sqla: P1D
  temporal_columns_lookup:
    event_timestamp: true
  metrics: []
  all_columns:
  - platform
  - course_title
  - courserun_readable_id
  - event_type
  - post_title
  - post_content
  - discussion_component_name
  - page_url
  - event_timestamp
  percent_metrics: []
  adhoc_filters:
  - clause: WHERE
    subject: event_timestamp
    operator: TEMPORAL_RANGE
    comparator: No filter
    expressionType: SIMPLE
  order_by_cols: []
  row_limit: 1000
  server_page_length: 10
  order_desc: true
  table_timestamp_format: smart_date
  allow_render_html: true
  show_cell_bars: true
  color_pn: true
  comparison_color_scheme: Green
  comparison_type: values
  extra_form_data: {}
  dashboards: []
query_context: '{"datasource":{"id":110,"type":"table"},"force":false,"queries":[{"filters":[{"col":"event_timestamp","op":"TEMPORAL_RANGE","val":"No
  filter"}],"extras":{"having":"","where":""},"applied_time_extras":{},"columns":["platform","course_title","courserun_readable_id","event_type","post_title","post_content","discussion_component_name","page_url","event_timestamp"],"orderby":[],"annotation_layers":[],"row_limit":1000,"series_limit":0,"order_desc":true,"url_params":{},"custom_params":{},"custom_form_data":{},"post_processing":[],"time_offsets":[]}],"form_data":{"datasource":"110__table","viz_type":"table","query_mode":"raw","groupby":[],"time_grain_sqla":"P1D","temporal_columns_lookup":{"event_timestamp":true},"metrics":[],"all_columns":["platform","course_title","courserun_readable_id","event_type","post_title","post_content","discussion_component_name","page_url","event_timestamp"],"percent_metrics":[],"adhoc_filters":[{"clause":"WHERE","subject":"event_timestamp","operator":"TEMPORAL_RANGE","comparator":"No
  filter","expressionType":"SIMPLE"}],"order_by_cols":[],"row_limit":1000,"server_page_length":10,"order_desc":true,"table_timestamp_format":"smart_date","allow_render_html":true,"show_cell_bars":true,"color_pn":true,"comparison_color_scheme":"Green","comparison_type":"values","extra_form_data":{},"dashboards":[],"force":false,"result_format":"json","result_type":"full","include_time":false},"result_format":"json","result_type":"full"}'
cache_timeout: null
uuid: 39c99c2d-1290-4d37-9b0f-eef559172947
version: 1.0.0
dataset_uuid: 5bab95fd-d465-44f3-bed8-40c559958fc4
