---
slice_name: Data Detail Problems
description:
certified_by:
certification_details:
viz_type: table
params:
  datasource: 107__table
  viz_type: table
  query_mode: raw
  groupby: []
  time_grain_sqla: P1D
  temporal_columns_lookup:
    event_timestamp: true
  metrics: []
  all_columns:
  - platform
  - course_title
  - courserun_readable_id
  - problem_name
  - event_type
  - answers
  - attempt
  - success
  - grade
  - max_grade
  - max_attempts
  - weight
  - markdown
  - event_timestamp
  percent_metrics: []
  adhoc_filters:
  - clause: WHERE
    subject: event_timestamp
    operator: TEMPORAL_RANGE
    comparator: No filter
    expressionType: SIMPLE
  order_by_cols: []
  row_limit: 1000
  server_page_length: 10
  order_desc: true
  table_timestamp_format: smart_date
  allow_render_html: true
  show_cell_bars: true
  color_pn: true
  comparison_color_scheme: Green
  comparison_type: values
  extra_form_data: {}
  dashboards: []
query_context: '{"datasource":{"id":107,"type":"table"},"force":false,"queries":[{"filters":[{"col":"event_timestamp","op":"TEMPORAL_RANGE","val":"No
  filter"}],"extras":{"having":"","where":""},"applied_time_extras":{},"columns":["platform","course_title","courserun_readable_id","problem_name","event_type","answers","attempt","success","grade","max_grade","max_attempts","weight","markdown","event_timestamp"],"orderby":[],"annotation_layers":[],"row_limit":1000,"series_limit":0,"order_desc":true,"url_params":{},"custom_params":{},"custom_form_data":{},"post_processing":[],"time_offsets":[]}],"form_data":{"datasource":"107__table","viz_type":"table","query_mode":"raw","groupby":[],"time_grain_sqla":"P1D","temporal_columns_lookup":{"event_timestamp":true},"metrics":[],"all_columns":["platform","course_title","courserun_readable_id","problem_name","event_type","answers","attempt","success","grade","max_grade","max_attempts","weight","markdown","event_timestamp"],"percent_metrics":[],"adhoc_filters":[{"clause":"WHERE","subject":"event_timestamp","operator":"TEMPORAL_RANGE","comparator":"No
  filter","expressionType":"SIMPLE"}],"order_by_cols":[],"row_limit":1000,"server_page_length":10,"order_desc":true,"table_timestamp_format":"smart_date","allow_render_html":true,"show_cell_bars":true,"color_pn":true,"comparison_color_scheme":"Green","comparison_type":"values","extra_form_data":{},"dashboards":[],"force":false,"result_format":"json","result_type":"full","include_time":false},"result_format":"json","result_type":"full"}'
cache_timeout:
uuid: 5e8a4f03-1504-4f8b-9990-de300d73ff93
version: 1.0.0
dataset_uuid: dc0886e8-1861-4bd9-a694-25a063adcf83
