slice_name: DEDP Learner Grades by Course
description: null
certified_by: null
certification_details: null
viz_type: table
params:
  datasource: 20__table
  viz_type: table
  slice_id: 16
  query_mode: aggregate
  groupby:
  - user_email
  - courserun_readable_id
  - grade
  time_grain_sqla: P1D
  temporal_columns_lookup: {}
  metrics: []
  all_columns: []
  percent_metrics: []
  adhoc_filters:
  - clause: WHERE
    comparator:
    - '1'
    - '2'
    - '3'
    datasourceWarning: false
    expressionType: SIMPLE
    filterOptionName: filter_zqjkwpt3r4_4750osikwqg
    isExtra: false
    isNew: false
    operator: IN
    operatorId: IN
    sqlExpression: null
    subject: mitxonline_program_id
  order_by_cols: []
  row_limit: 1000
  server_page_length: 10
  order_desc: true
  table_timestamp_format: smart_date
  show_cell_bars: true
  color_pn: true
  extra_form_data: {}
  dashboards: []
  comparison_type: values
query_context: '{"datasource":{"id":20,"type":"table"},"force":false,"queries":[{"filters":[{"col":"mitxonline_program_id","op":"IN","val":["1","2","3"]}],"extras":{"time_grain_sqla":"P1D","having":"","where":""},"applied_time_extras":{},"columns":["user_email","courserun_readable_id","grade"],"metrics":[],"orderby":[],"annotation_layers":[],"row_limit":1000,"series_limit":0,"order_desc":true,"url_params":{},"custom_params":{},"custom_form_data":{},"post_processing":[]}],"form_data":{"datasource":"20__table","viz_type":"table","slice_id":16,"query_mode":"aggregate","groupby":["user_email","courserun_readable_id","grade"],"time_grain_sqla":"P1D","temporal_columns_lookup":{},"metrics":[],"all_columns":[],"percent_metrics":[],"adhoc_filters":[{"clause":"WHERE","comparator":["1","2","3"],"datasourceWarning":false,"expressionType":"SIMPLE","filterOptionName":"filter_zqjkwpt3r4_4750osikwqg","isExtra":false,"isNew":false,"operator":"IN","operatorId":"IN","sqlExpression":null,"subject":"mitxonline_program_id"}],"order_by_cols":[],"row_limit":1000,"server_page_length":10,"order_desc":true,"table_timestamp_format":"smart_date","show_cell_bars":true,"color_pn":true,"extra_form_data":{},"dashboards":[],"force":false,"result_format":"json","result_type":"full"},"result_format":"json","result_type":"full"}'
cache_timeout: null
uuid: 1ec63597-fd4e-4e55-b5e0-aa09309f3cce
version: 1.0.0
dataset_uuid: 70bc54c5-1073-4bdc-922b-76f6eff82ae3
