slice_name: DEDP 3T2023 certificates by course runs
description: null
certified_by: null
certification_details: null
viz_type: echarts_timeseries_bar
params:
  datasource: 20__table
  viz_type: echarts_timeseries_bar
  x_axis: courserun_readable_id
  time_grain_sqla: P1D
  x_axis_sort_asc: true
  x_axis_sort_series: name
  x_axis_sort_series_ascending: true
  metrics:
  - expressionType: SQL
    sqlExpression: count(*)
    column: null
    aggregate: null
    datasourceWarning: false
    hasCustomLabel: false
    label: count(*)
    optionName: metric_lg43l93lbdj_bv8ubegsyx
  groupby: []
  adhoc_filters:
  - expressionType: SIMPLE
    subject: mitxonline_program_id
    operator: IN
    operatorId: IN
    comparator:
    - '1'
    - '2'
    - '3'
    clause: WHERE
    sqlExpression: null
    isExtra: false
    isNew: false
    datasourceWarning: false
    filterOptionName: filter_gpq16kei9r_aisn0rg4uqe
  - expressionType: SIMPLE
    subject: courserun_readable_id
    operator: LIKE
    operatorId: LIKE
    comparator: '%3T2023%'
    clause: WHERE
    sqlExpression: null
    isExtra: false
    isNew: false
    datasourceWarning: false
    filterOptionName: filter_eqdwy3pmq3j_tjz10zbhiw
  order_desc: true
  row_limit: 10000
  truncate_metric: true
  show_empty_columns: true
  comparison_type: values
  annotation_layers: []
  forecastPeriods: 10
  forecastInterval: 0.8
  orientation: vertical
  x_axis_title_margin: 15
  y_axis_title_margin: 15
  y_axis_title_position: Left
  sort_series_type: sum
  color_scheme: supersetColors
  only_total: true
  show_legend: true
  legendType: scroll
  legendOrientation: top
  x_axis_time_format: smart_date
  y_axis_format: SMART_NUMBER
  truncateXAxis: true
  y_axis_bounds:
  - null
  - null
  rich_tooltip: true
  tooltipTimeFormat: smart_date
  extra_form_data: {}
  dashboards: []
query_context: '{"datasource":{"id":20,"type":"table"},"force":false,"queries":[{"filters":[{"col":"mitxonline_program_id","op":"IN","val":["1","2","3"]},{"col":"courserun_readable_id","op":"LIKE","val":"%3T2023%"}],"extras":{"time_grain_sqla":"P1D","having":"","where":""},"applied_time_extras":{},"columns":[{"timeGrain":"P1D","columnType":"BASE_AXIS","sqlExpression":"courserun_readable_id","label":"courserun_readable_id","expressionType":"SQL"}],"metrics":[{"expressionType":"SQL","sqlExpression":"count(*)","column":null,"aggregate":null,"datasourceWarning":false,"hasCustomLabel":false,"label":"count(*)","optionName":"metric_lg43l93lbdj_bv8ubegsyx"}],"orderby":[[{"expressionType":"SQL","sqlExpression":"count(*)","column":null,"aggregate":null,"datasourceWarning":false,"hasCustomLabel":false,"label":"count(*)","optionName":"metric_lg43l93lbdj_bv8ubegsyx"},false]],"annotation_layers":[],"row_limit":10000,"series_columns":[],"series_limit":0,"order_desc":true,"url_params":{},"custom_params":{},"custom_form_data":{},"time_offsets":[],"post_processing":[{"operation":"pivot","options":{"index":["courserun_readable_id"],"columns":[],"aggregates":{"count(*)":{"operator":"mean"}},"drop_missing_columns":false}},{"operation":"flatten"}]}],"form_data":{"datasource":"20__table","viz_type":"echarts_timeseries_bar","x_axis":"courserun_readable_id","time_grain_sqla":"P1D","x_axis_sort_asc":true,"x_axis_sort_series":"name","x_axis_sort_series_ascending":true,"metrics":[{"expressionType":"SQL","sqlExpression":"count(*)","column":null,"aggregate":null,"datasourceWarning":false,"hasCustomLabel":false,"label":"count(*)","optionName":"metric_lg43l93lbdj_bv8ubegsyx"}],"groupby":[],"adhoc_filters":[{"expressionType":"SIMPLE","subject":"mitxonline_program_id","operator":"IN","operatorId":"IN","comparator":["1","2","3"],"clause":"WHERE","sqlExpression":null,"isExtra":false,"isNew":false,"datasourceWarning":false,"filterOptionName":"filter_gpq16kei9r_aisn0rg4uqe"},{"expressionType":"SIMPLE","subject":"courserun_readable_id","operator":"LIKE","operatorId":"LIKE","comparator":"%3T2023%","clause":"WHERE","sqlExpression":null,"isExtra":false,"isNew":false,"datasourceWarning":false,"filterOptionName":"filter_eqdwy3pmq3j_tjz10zbhiw"}],"order_desc":true,"row_limit":10000,"truncate_metric":true,"show_empty_columns":true,"comparison_type":"values","annotation_layers":[],"forecastPeriods":10,"forecastInterval":0.8,"orientation":"vertical","x_axis_title_margin":15,"y_axis_title_margin":15,"y_axis_title_position":"Left","sort_series_type":"sum","color_scheme":"supersetColors","only_total":true,"show_legend":true,"legendType":"scroll","legendOrientation":"top","x_axis_time_format":"smart_date","y_axis_format":"SMART_NUMBER","truncateXAxis":true,"y_axis_bounds":[null,null],"rich_tooltip":true,"tooltipTimeFormat":"smart_date","extra_form_data":{},"dashboards":[],"force":false,"result_format":"json","result_type":"full"},"result_format":"json","result_type":"full"}'
cache_timeout: null
uuid: 092c45b2-f7d3-4c7e-b4aa-99890c07746a
version: 1.0.0
dataset_uuid: 70bc54c5-1073-4bdc-922b-76f6eff82ae3
