slice_name: Distribution of Number of Videos Watched
description: null
certified_by: null
certification_details: null
viz_type: echarts_timeseries_bar
params:
  datasource: 48__table
  viz_type: echarts_timeseries_bar
  slice_id: 66
  x_axis: user_watched_video_count
  x_axis_sort_asc: true
  x_axis_sort_series: name
  x_axis_sort_series_ascending: true
  metrics:
  - aggregate: COUNT_DISTINCT
    column:
      advanced_data_type: null
      certification_details: null
      certified_by: null
      column_name: user_email
      description: null
      expression: null
      filterable: true
      groupby: true
      id: 652
      is_certified: false
      is_dttm: false
      python_date_format: null
      type: VARCHAR
      type_generic: 1
      verbose_name: null
      warning_markdown: null
    datasourceWarning: false
    expressionType: SIMPLE
    hasCustomLabel: true
    label: Learner_count
    optionName: metric_nm46la8oog_g7874if5427
    sqlExpression: null
  groupby: []
  adhoc_filters: []
  order_desc: true
  row_limit: 10000
  truncate_metric: true
  show_empty_columns: true
  comparison_type: values
  annotation_layers: []
  forecastPeriods: 10
  forecastInterval: 0.8
  orientation: vertical
  x_axis_title_margin: 15
  y_axis_title_margin: 15
  y_axis_title_position: Left
  sort_series_type: sum
  color_scheme: supersetColors
  only_total: true
  show_legend: true
  legendType: scroll
  legendOrientation: top
  x_axis_time_format: smart_date
  y_axis_format: SMART_NUMBER
  truncateXAxis: true
  y_axis_bounds:
  - null
  - null
  rich_tooltip: true
  tooltipTimeFormat: smart_date
  extra_form_data: {}
  dashboards:
  - 29
query_context: '{"datasource":{"id":48,"type":"table"},"force":false,"queries":[{"filters":[],"extras":{"having":"","where":""},"applied_time_extras":{},"columns":[{"columnType":"BASE_AXIS","sqlExpression":"user_watched_video_count","label":"user_watched_video_count","expressionType":"SQL"}],"metrics":[{"aggregate":"COUNT_DISTINCT","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"user_email","description":null,"expression":null,"filterable":true,"groupby":true,"id":652,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":"VARCHAR","type_generic":1,"verbose_name":null,"warning_markdown":null},"datasourceWarning":false,"expressionType":"SIMPLE","hasCustomLabel":true,"label":"Learner_count","optionName":"metric_nm46la8oog_g7874if5427","sqlExpression":null}],"orderby":[[{"aggregate":"COUNT_DISTINCT","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"user_email","description":null,"expression":null,"filterable":true,"groupby":true,"id":652,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":"VARCHAR","type_generic":1,"verbose_name":null,"warning_markdown":null},"datasourceWarning":false,"expressionType":"SIMPLE","hasCustomLabel":true,"label":"Learner_count","optionName":"metric_nm46la8oog_g7874if5427","sqlExpression":null},false]],"annotation_layers":[],"row_limit":10000,"series_columns":[],"series_limit":0,"order_desc":true,"url_params":{},"custom_params":{},"custom_form_data":{},"time_offsets":[],"post_processing":[{"operation":"pivot","options":{"index":["user_watched_video_count"],"columns":[],"aggregates":{"Learner_count":{"operator":"mean"}},"drop_missing_columns":false}},{"operation":"flatten"}]}],"form_data":{"datasource":"48__table","viz_type":"echarts_timeseries_bar","slice_id":66,"x_axis":"user_watched_video_count","x_axis_sort_asc":true,"x_axis_sort_series":"name","x_axis_sort_series_ascending":true,"metrics":[{"aggregate":"COUNT_DISTINCT","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"user_email","description":null,"expression":null,"filterable":true,"groupby":true,"id":652,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":"VARCHAR","type_generic":1,"verbose_name":null,"warning_markdown":null},"datasourceWarning":false,"expressionType":"SIMPLE","hasCustomLabel":true,"label":"Learner_count","optionName":"metric_nm46la8oog_g7874if5427","sqlExpression":null}],"groupby":[],"adhoc_filters":[],"order_desc":true,"row_limit":10000,"truncate_metric":true,"show_empty_columns":true,"comparison_type":"values","annotation_layers":[],"forecastPeriods":10,"forecastInterval":0.8,"orientation":"vertical","x_axis_title_margin":15,"y_axis_title_margin":15,"y_axis_title_position":"Left","sort_series_type":"sum","color_scheme":"supersetColors","only_total":true,"show_legend":true,"legendType":"scroll","legendOrientation":"top","x_axis_time_format":"smart_date","y_axis_format":"SMART_NUMBER","truncateXAxis":true,"y_axis_bounds":[null,null],"rich_tooltip":true,"tooltipTimeFormat":"smart_date","extra_form_data":{},"dashboards":[29],"force":false,"result_format":"json","result_type":"full"},"result_format":"json","result_type":"full"}'
cache_timeout: null
uuid: 9bdb6168-d5c9-4651-af36-556e29f3b5db
version: 1.0.0
dataset_uuid: 42f063d3-3c06-4834-b993-777fdbc6dea7
