slice_name: Engagement Totals
description: null
certified_by: null
certification_details: null
viz_type: echarts_timeseries_bar
params:
  adhoc_filters:
  - clause: WHERE
    comparator: No filter
    expressionType: SIMPLE
    operator: TEMPORAL_RANGE
    subject: courseactivity_date
  annotation_layers: []
  color_scheme: supersetColors
  comparison_type: values
  dashboards:
  - 26
  datasource: 10__table
  extra_form_data: {}
  forecastInterval: 0.8
  forecastPeriods: 10
  groupby: []
  legendMargin: null
  legendOrientation: top
  legendType: scroll
  metrics:
  - aggregate: null
    column: null
    datasourceWarning: false
    expressionType: SQL
    hasCustomLabel: true
    label: Watched_a_video
    optionName: metric_059piu499ctj_v1biwm6w8a
    sqlExpression: COUNT(DISTINCT(CASE WHEN num_video_played> 0 THEN user_username
      ELSE null END))
  - aggregate: null
    column: null
    datasourceWarning: false
    expressionType: SQL
    hasCustomLabel: true
    label: Tried_a_problem
    optionName: metric_t4xk2kk9zxa_zdkc9h1us7h
    sqlExpression: COUNT(DISTINCT(case when num_problem_submitted> 0 then user_username
      else null end))
  - aggregate: null
    column: null
    datasourceWarning: false
    expressionType: SQL
    hasCustomLabel: true
    label: Participated_In_Discussion
    optionName: metric_8zaqrr5aljx_o1deaowi9rp
    sqlExpression: COUNT(DISTINCT(case when num_discussion_participated> 0 then user_username
      else null end))
  - aggregate: null
    column: null
    datasourceWarning: false
    expressionType: SQL
    hasCustomLabel: true
    label: Learner_count
    optionName: metric_653jots7vt7_l91azd98z0k
    sqlExpression: COUNT(DISTINCT user_username)
  only_total: true
  order_desc: true
  orientation: vertical
  rich_tooltip: true
  row_limit: 10000
  showTooltipPercentage: false
  showTooltipTotal: false
  show_empty_columns: true
  show_legend: true
  slice_id: 73
  sort_series_type: sum
  tooltipTimeFormat: smart_date
  truncateXAxis: true
  truncate_metric: true
  viz_type: echarts_timeseries_bar
  x_axis: courserun_readable_id
  x_axis_sort: name
  x_axis_sort_asc: true
  x_axis_time_format: smart_date
  x_axis_title_margin: 15
  y_axis_bounds:
  - null
  - null
  y_axis_format: SMART_NUMBER
  y_axis_title_margin: 15
  y_axis_title_position: Left
query_context: '{"datasource":{"id":10,"type":"table"},"force":false,"queries":[{"filters":[{"col":"courseactivity_date","op":"TEMPORAL_RANGE","val":"No
  filter"}],"extras":{"having":"","where":""},"applied_time_extras":{},"columns":[{"columnType":"BASE_AXIS","sqlExpression":"courserun_readable_id","label":"courserun_readable_id","expressionType":"SQL"}],"metrics":[{"aggregate":null,"column":null,"datasourceWarning":false,"expressionType":"SQL","hasCustomLabel":true,"label":"Watched_a_video","optionName":"metric_059piu499ctj_v1biwm6w8a","sqlExpression":"COUNT(DISTINCT(CASE
  WHEN num_video_played> 0 THEN user_username ELSE null END))"},{"aggregate":null,"column":null,"datasourceWarning":false,"expressionType":"SQL","hasCustomLabel":true,"label":"Tried_a_problem","optionName":"metric_t4xk2kk9zxa_zdkc9h1us7h","sqlExpression":"COUNT(DISTINCT(case
  when num_problem_submitted> 0 then user_username else null end))"},{"aggregate":null,"column":null,"datasourceWarning":false,"expressionType":"SQL","hasCustomLabel":true,"label":"Participated_In_Discussion","optionName":"metric_8zaqrr5aljx_o1deaowi9rp","sqlExpression":"COUNT(DISTINCT(case
  when num_discussion_participated> 0 then user_username else null end))"},{"aggregate":null,"column":null,"datasourceWarning":false,"expressionType":"SQL","hasCustomLabel":true,"label":"Learner_count","optionName":"metric_653jots7vt7_l91azd98z0k","sqlExpression":"COUNT(DISTINCT
  user_username)"}],"orderby":[[{"aggregate":null,"column":null,"datasourceWarning":false,"expressionType":"SQL","hasCustomLabel":true,"label":"Watched_a_video","optionName":"metric_059piu499ctj_v1biwm6w8a","sqlExpression":"COUNT(DISTINCT(CASE
  WHEN num_video_played> 0 THEN user_username ELSE null END))"},false]],"annotation_layers":[],"row_limit":10000,"series_columns":[],"series_limit":0,"order_desc":true,"url_params":{},"custom_params":{},"custom_form_data":{},"time_offsets":[],"post_processing":[{"operation":"pivot","options":{"index":["courserun_readable_id"],"columns":[],"aggregates":{"Watched_a_video":{"operator":"mean"},"Tried_a_problem":{"operator":"mean"},"Participated_In_Discussion":{"operator":"mean"},"Learner_count":{"operator":"mean"}},"drop_missing_columns":false}},{"operation":"flatten"}]}],"form_data":{"datasource":"10__table","viz_type":"echarts_timeseries_bar","slice_id":73,"x_axis":"courserun_readable_id","x_axis_sort_asc":true,"x_axis_sort_series":"name","x_axis_sort_series_ascending":true,"metrics":[{"aggregate":null,"column":null,"datasourceWarning":false,"expressionType":"SQL","hasCustomLabel":true,"label":"Watched_a_video","optionName":"metric_059piu499ctj_v1biwm6w8a","sqlExpression":"COUNT(DISTINCT(CASE
  WHEN num_video_played> 0 THEN user_username ELSE null END))"},{"aggregate":null,"column":null,"datasourceWarning":false,"expressionType":"SQL","hasCustomLabel":true,"label":"Tried_a_problem","optionName":"metric_t4xk2kk9zxa_zdkc9h1us7h","sqlExpression":"COUNT(DISTINCT(case
  when num_problem_submitted> 0 then user_username else null end))"},{"aggregate":null,"column":null,"datasourceWarning":false,"expressionType":"SQL","hasCustomLabel":true,"label":"Participated_In_Discussion","optionName":"metric_8zaqrr5aljx_o1deaowi9rp","sqlExpression":"COUNT(DISTINCT(case
  when num_discussion_participated> 0 then user_username else null end))"},{"aggregate":null,"column":null,"datasourceWarning":false,"expressionType":"SQL","hasCustomLabel":true,"label":"Learner_count","optionName":"metric_653jots7vt7_l91azd98z0k","sqlExpression":"COUNT(DISTINCT
  user_username)"}],"groupby":[],"adhoc_filters":[{"clause":"WHERE","comparator":"No
  filter","expressionType":"SIMPLE","operator":"TEMPORAL_RANGE","subject":"courseactivity_date"}],"order_desc":true,"row_limit":10000,"truncate_metric":true,"show_empty_columns":true,"comparison_type":"values","annotation_layers":[],"forecastPeriods":10,"forecastInterval":0.8,"orientation":"vertical","x_axis_title_margin":15,"y_axis_title_margin":15,"y_axis_title_position":"Left","sort_series_type":"sum","color_scheme":"supersetColors","only_total":true,"show_legend":true,"legendType":"scroll","legendOrientation":"top","legendMargin":null,"x_axis_time_format":"smart_date","y_axis_format":"SMART_NUMBER","y_axis_bounds":[null,null],"truncateXAxis":true,"rich_tooltip":true,"showTooltipTotal":false,"showTooltipPercentage":false,"tooltipTimeFormat":"smart_date","extra_form_data":{},"dashboards":[26],"force":false,"result_format":"json","result_type":"full"},"result_format":"json","result_type":"full"}'
cache_timeout: null
uuid: 24ea41c4-da94-443a-af6b-77bc7e09c303
version: 1.0.0
dataset_uuid: e7330108-bdfa-4ff0-8ca3-084d7e8cbda8
