slice_name: Latest Course Activity Date
description: null
certified_by: null
certification_details: null
viz_type: table
params:
  datasource: 47__table
  viz_type: table
  slice_id: 62
  query_mode: aggregate
  groupby: []
  time_grain_sqla: P1D
  temporal_columns_lookup:
    courseactivity_date: true
  metrics:
  - aggregate: MAX
    column:
      advanced_data_type: null
      certification_details: null
      certified_by: null
      column_name: courseactivity_date
      description: null
      expression: null
      filterable: true
      groupby: true
      id: 711
      is_certified: false
      is_dttm: true
      python_date_format: null
      type: DATE
      type_generic: 2
      verbose_name: null
      warning_markdown: null
    datasourceWarning: false
    expressionType: SIMPLE
    hasCustomLabel: true
    label: Latest Course Activity Date
    optionName: metric_2a0s7ht5t42_y116rfrjcu
    sqlExpression: null
  all_columns: []
  percent_metrics: []
  adhoc_filters:
  - expressionType: SIMPLE
    subject: courseactivity_date
    operator: TEMPORAL_RANGE
    comparator: No filter
    clause: WHERE
    sqlExpression: null
    isExtra: false
    isNew: false
    datasourceWarning: false
    filterOptionName: filter_3bhylqb5grn_ztmh2j2v29e
  - expressionType: SQL
    sqlExpression: courseactivity_date <= current_date
    clause: WHERE
    subject: courseactivity_date
    operator: TEMPORAL_RANGE
    operatorId: TEMPORAL_RANGE
    comparator: null
    isExtra: false
    isNew: false
    datasourceWarning: false
    filterOptionName: filter_1sdhhe17e5o_0lz20p68pjqs
  order_by_cols: []
  row_limit: 1000
  server_page_length: 10
  order_desc: true
  table_timestamp_format: smart_date
  show_cell_bars: true
  color_pn: true
  extra_form_data: {}
  dashboards:
  - 27
  comparison_type: values
query_context: '{"datasource":{"id":47,"type":"table"},"force":false,"queries":[{"filters":[{"col":"courseactivity_date","op":"TEMPORAL_RANGE","val":"No
  filter"}],"extras":{"time_grain_sqla":"P1D","having":"","where":"(courseactivity_date
  <= current_date)"},"applied_time_extras":{},"columns":[],"metrics":[{"aggregate":"MAX","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"courseactivity_date","description":null,"expression":null,"filterable":true,"groupby":true,"id":711,"is_certified":false,"is_dttm":true,"python_date_format":null,"type":"DATE","type_generic":2,"verbose_name":null,"warning_markdown":null},"datasourceWarning":false,"expressionType":"SIMPLE","hasCustomLabel":true,"label":"Latest
  Course Activity Date","optionName":"metric_2a0s7ht5t42_y116rfrjcu","sqlExpression":null}],"orderby":[[{"aggregate":"MAX","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"courseactivity_date","description":null,"expression":null,"filterable":true,"groupby":true,"id":711,"is_certified":false,"is_dttm":true,"python_date_format":null,"type":"DATE","type_generic":2,"verbose_name":null,"warning_markdown":null},"datasourceWarning":false,"expressionType":"SIMPLE","hasCustomLabel":true,"label":"Latest
  Course Activity Date","optionName":"metric_2a0s7ht5t42_y116rfrjcu","sqlExpression":null},false]],"annotation_layers":[],"row_limit":1000,"series_limit":0,"order_desc":true,"url_params":{},"custom_params":{},"custom_form_data":{},"post_processing":[]}],"form_data":{"datasource":"47__table","viz_type":"table","slice_id":62,"query_mode":"aggregate","groupby":[],"time_grain_sqla":"P1D","temporal_columns_lookup":{"courseactivity_date":true},"metrics":[{"aggregate":"MAX","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"courseactivity_date","description":null,"expression":null,"filterable":true,"groupby":true,"id":711,"is_certified":false,"is_dttm":true,"python_date_format":null,"type":"DATE","type_generic":2,"verbose_name":null,"warning_markdown":null},"datasourceWarning":false,"expressionType":"SIMPLE","hasCustomLabel":true,"label":"Latest
  Course Activity Date","optionName":"metric_2a0s7ht5t42_y116rfrjcu","sqlExpression":null}],"all_columns":[],"percent_metrics":[],"adhoc_filters":[{"expressionType":"SIMPLE","subject":"courseactivity_date","operator":"TEMPORAL_RANGE","comparator":"No
  filter","clause":"WHERE","sqlExpression":null,"isExtra":false,"isNew":false,"datasourceWarning":false,"filterOptionName":"filter_3bhylqb5grn_ztmh2j2v29e"},{"expressionType":"SQL","sqlExpression":"courseactivity_date
  <= current_date","clause":"WHERE","subject":"courseactivity_date","operator":"TEMPORAL_RANGE","operatorId":"TEMPORAL_RANGE","comparator":null,"isExtra":false,"isNew":false,"datasourceWarning":false,"filterOptionName":"filter_1sdhhe17e5o_0lz20p68pjqs"}],"order_by_cols":[],"row_limit":1000,"server_page_length":10,"order_desc":true,"table_timestamp_format":"smart_date","show_cell_bars":true,"color_pn":true,"extra_form_data":{},"dashboards":[27],"force":false,"result_format":"json","result_type":"full"},"result_format":"json","result_type":"full"}'
cache_timeout: null
uuid: 5f95a268-4339-4d73-b8d8-d082ca53b28d
version: 1.0.0
dataset_uuid: f221af29-5df4-4025-8355-401041f94835
