---
slice_name: Latest Activity Date
description:
certified_by:
certification_details:
viz_type: table
params:
  datasource: 154__table
  viz_type: table
  query_mode: aggregate
  groupby: []
  time_grain_sqla: P1D
  temporal_columns_lookup:
    activity_date: true
  metrics:
  - expressionType: SIMPLE
    column:
      advanced_data_type:
      certification_details:
      certified_by:
      column_name: activity_date
      description:
      expression: ''
      filterable: true
      groupby: true
      id: 2282
      is_certified: false
      is_dttm: true
      python_date_format:
      type: DATE
      type_generic: 2
      verbose_name:
      warning_markdown:
    aggregate: MAX
    sqlExpression:
    datasourceWarning: false
    hasCustomLabel: false
    label: MAX(activity_date)
    optionName: metric_85lf3u74ixn_ez32bhzujl9
  all_columns: []
  percent_metrics: []
  adhoc_filters:
  - clause: WHERE
    subject: activity_date
    operator: TEMPORAL_RANGE
    comparator: No filter
    expressionType: SIMPLE
  order_by_cols: []
  order_desc: true
  row_limit: 1000
  server_page_length: 10
  table_timestamp_format: smart_date
  allow_render_html: true
  show_cell_bars: true
  color_pn: true
  comparison_color_scheme: Green
  comparison_type: values
  extra_form_data: {}
  dashboards:
  - 59
query_context: '{"datasource":{"id":154,"type":"table"},"force":false,"queries":[{"filters":[{"col":"activity_date","op":"TEMPORAL_RANGE","val":"No
  filter"}],"extras":{"time_grain_sqla":"P1D","having":"","where":""},"applied_time_extras":{},"columns":[],"metrics":[{"expressionType":"SIMPLE","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"activity_date","description":null,"expression":"","filterable":true,"groupby":true,"id":2282,"is_certified":false,"is_dttm":true,"python_date_format":null,"type":"DATE","type_generic":2,"verbose_name":null,"warning_markdown":null},"aggregate":"MAX","sqlExpression":null,"datasourceWarning":false,"hasCustomLabel":false,"label":"MAX(activity_date)","optionName":"metric_85lf3u74ixn_ez32bhzujl9"}],"orderby":[[{"expressionType":"SIMPLE","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"activity_date","description":null,"expression":"","filterable":true,"groupby":true,"id":2282,"is_certified":false,"is_dttm":true,"python_date_format":null,"type":"DATE","type_generic":2,"verbose_name":null,"warning_markdown":null},"aggregate":"MAX","sqlExpression":null,"datasourceWarning":false,"hasCustomLabel":false,"label":"MAX(activity_date)","optionName":"metric_85lf3u74ixn_ez32bhzujl9"},false]],"annotation_layers":[],"row_limit":1000,"series_limit":0,"order_desc":true,"url_params":{},"custom_params":{},"custom_form_data":{},"post_processing":[],"time_offsets":[]}],"form_data":{"datasource":"154__table","viz_type":"table","query_mode":"aggregate","groupby":[],"time_grain_sqla":"P1D","temporal_columns_lookup":{"activity_date":true},"metrics":[{"expressionType":"SIMPLE","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"activity_date","description":null,"expression":"","filterable":true,"groupby":true,"id":2282,"is_certified":false,"is_dttm":true,"python_date_format":null,"type":"DATE","type_generic":2,"verbose_name":null,"warning_markdown":null},"aggregate":"MAX","sqlExpression":null,"datasourceWarning":false,"hasCustomLabel":false,"label":"MAX(activity_date)","optionName":"metric_85lf3u74ixn_ez32bhzujl9"}],"all_columns":[],"percent_metrics":[],"adhoc_filters":[{"clause":"WHERE","subject":"activity_date","operator":"TEMPORAL_RANGE","comparator":"No
  filter","expressionType":"SIMPLE"}],"order_by_cols":[],"order_desc":true,"row_limit":1000,"server_page_length":10,"table_timestamp_format":"smart_date","allow_render_html":true,"show_cell_bars":true,"color_pn":true,"comparison_color_scheme":"Green","comparison_type":"values","extra_form_data":{},"dashboards":[59],"force":false,"result_format":"json","result_type":"full"},"result_format":"json","result_type":"full"}'
cache_timeout:
uuid: f9e19a79-18f9-4a54-ad7a-85c5f0b5b801
version: 1.0.0
dataset_uuid: 8c2b6f11-28f8-4353-8e43-6c53ea6b1d91
