---
slice_name: Learner Performance
description:
certified_by:
certification_details:
viz_type: table
params:
  datasource: 38__table
  viz_type: table
  slice_id: 48
  query_mode: aggregate
  groupby:
  - course_title
  - courserun_readable_id
  time_grain_sqla: P1D
  temporal_columns_lookup: {}
  metrics:
  - aggregate:
    column:
    datasourceWarning: false
    expressionType: SQL
    hasCustomLabel: true
    label: Count_of_Passing_Grades
    optionName: metric_cb6ifhe3g1_pjq21962l3
    sqlExpression: SUM(case when courserungrade_is_passing = true then 1 else 0 end)
  - aggregate: AVG
    column:
      advanced_data_type:
      certification_details:
      certified_by:
      column_name: courserungrade_grade
      description:
      expression:
      filterable: true
      groupby: true
      id: 514
      is_certified: false
      is_dttm: false
      python_date_format:
      type: DECIMAL(38, 4)
      type_generic: 0
      verbose_name:
      warning_markdown:
    datasourceWarning: false
    expressionType: SIMPLE
    hasCustomLabel: true
    label: AVG_Course_Grade
    optionName: metric_ws9dtukl2hc_gksgs0oyppt
    sqlExpression:
  - aggregate:
    column:
    datasourceWarning: false
    expressionType: SQL
    hasCustomLabel: true
    label: Count_of_Certificates_Earned
    optionName: metric_bz2uw9fgwy4_0hcsj2sn55c
    sqlExpression: sum(case when courseruncertificate_is_earned = true then 1 else
      0 end)
  all_columns: []
  percent_metrics: []
  adhoc_filters:
  - clause: WHERE
    comparator:
    - 
    - deferred
    - refunded
    - transferred
    datasourceWarning: false
    expressionType: SIMPLE
    filterOptionName: filter_60orc3xmciv_bdv5ncadvih
    isExtra: false
    isNew: false
    operator: IN
    operatorId: IN
    sqlExpression:
    subject: courserunenrollment_enrollment_status
  order_by_cols: []
  row_limit: 1000
  server_page_length: 10
  order_desc: true
  table_timestamp_format: smart_date
  show_cell_bars: true
  color_pn: true
  extra_form_data: {}
  dashboards:
  - 16
  comparison_type: values
query_context: '{"datasource":{"id":38,"type":"table"},"force":false,"queries":[{"filters":[{"col":"courserunenrollment_enrollment_status","op":"IN","val":[null,"deferred","refunded","transferred"]}],"extras":{"time_grain_sqla":"P1D","having":"","where":""},"applied_time_extras":{},"columns":["course_title","courserun_readable_id"],"metrics":[{"aggregate":null,"column":null,"datasourceWarning":false,"expressionType":"SQL","hasCustomLabel":true,"label":"Count_of_Passing_Grades","optionName":"metric_cb6ifhe3g1_pjq21962l3","sqlExpression":"SUM(case
  when courserungrade_is_passing = true then 1 else 0 end)"},{"aggregate":"AVG","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"courserungrade_grade","description":null,"expression":null,"filterable":true,"groupby":true,"id":514,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":"DECIMAL(38,
  4)","type_generic":0,"verbose_name":null,"warning_markdown":null},"datasourceWarning":false,"expressionType":"SIMPLE","hasCustomLabel":true,"label":"AVG_Course_Grade","optionName":"metric_ws9dtukl2hc_gksgs0oyppt","sqlExpression":null},{"aggregate":null,"column":null,"datasourceWarning":false,"expressionType":"SQL","hasCustomLabel":true,"label":"Count_of_Certificates_Earned","optionName":"metric_bz2uw9fgwy4_0hcsj2sn55c","sqlExpression":"sum(case
  when courseruncertificate_is_earned = true then 1 else 0 end)"}],"orderby":[[{"aggregate":null,"column":null,"datasourceWarning":false,"expressionType":"SQL","hasCustomLabel":true,"label":"Count_of_Passing_Grades","optionName":"metric_cb6ifhe3g1_pjq21962l3","sqlExpression":"SUM(case
  when courserungrade_is_passing = true then 1 else 0 end)"},false]],"annotation_layers":[],"row_limit":1000,"series_limit":0,"order_desc":true,"url_params":{},"custom_params":{},"custom_form_data":{},"post_processing":[]}],"form_data":{"datasource":"38__table","viz_type":"table","slice_id":48,"query_mode":"aggregate","groupby":["course_title","courserun_readable_id"],"time_grain_sqla":"P1D","temporal_columns_lookup":{},"metrics":[{"aggregate":null,"column":null,"datasourceWarning":false,"expressionType":"SQL","hasCustomLabel":true,"label":"Count_of_Passing_Grades","optionName":"metric_cb6ifhe3g1_pjq21962l3","sqlExpression":"SUM(case
  when courserungrade_is_passing = true then 1 else 0 end)"},{"aggregate":"AVG","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"courserungrade_grade","description":null,"expression":null,"filterable":true,"groupby":true,"id":514,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":"DECIMAL(38,
  4)","type_generic":0,"verbose_name":null,"warning_markdown":null},"datasourceWarning":false,"expressionType":"SIMPLE","hasCustomLabel":true,"label":"AVG_Course_Grade","optionName":"metric_ws9dtukl2hc_gksgs0oyppt","sqlExpression":null},{"aggregate":null,"column":null,"datasourceWarning":false,"expressionType":"SQL","hasCustomLabel":true,"label":"Count_of_Certificates_Earned","optionName":"metric_bz2uw9fgwy4_0hcsj2sn55c","sqlExpression":"sum(case
  when courseruncertificate_is_earned = true then 1 else 0 end)"}],"all_columns":[],"percent_metrics":[],"adhoc_filters":[{"clause":"WHERE","comparator":[null,"deferred","refunded","transferred"],"datasourceWarning":false,"expressionType":"SIMPLE","filterOptionName":"filter_60orc3xmciv_bdv5ncadvih","isExtra":false,"isNew":false,"operator":"IN","operatorId":"IN","sqlExpression":null,"subject":"courserunenrollment_enrollment_status"}],"order_by_cols":[],"row_limit":1000,"server_page_length":10,"order_desc":true,"table_timestamp_format":"smart_date","show_cell_bars":true,"color_pn":true,"extra_form_data":{},"dashboards":[16],"force":false,"result_format":"json","result_type":"full"},"result_format":"json","result_type":"full"}'
cache_timeout:
uuid: d747faf0-d2f8-4dde-84ca-54b60775e051
version: 1.0.0
dataset_uuid: f3e517dd-4012-441e-8dfe-edaef1318000
