---
slice_name: Learners Enrolled
description:
certified_by:
certification_details:
viz_type: big_number_total
params:
  datasource: 38__table
  viz_type: big_number_total
  slice_id: 45
  metric:
    aggregate: COUNT_DISTINCT
    column:
      advanced_data_type:
      certification_details:
      certified_by:
      column_name: user_email
      description:
      expression:
      filterable: true
      groupby: true
      id: 480
      is_certified: false
      is_dttm: false
      python_date_format:
      type: VARCHAR
      type_generic: 1
      verbose_name:
      warning_markdown:
    datasourceWarning: false
    expressionType: SIMPLE
    hasCustomLabel: false
    label: COUNT_DISTINCT(user_email)
    optionName: metric_5843lrl7hfu_w3oti257dj
    sqlExpression:
  adhoc_filters:
  - expressionType: SIMPLE
    subject: courserunenrollment_is_active
    operator: IN
    operatorId: IN
    comparator:
    - true
    clause: WHERE
    sqlExpression:
    isExtra: false
    isNew: false
    datasourceWarning: false
    filterOptionName: filter_o2n4rpik3b_cz5k34mkm7a
  header_font_size: 0.4
  subheader_font_size: 0.15
  y_axis_format: SMART_NUMBER
  time_format: smart_date
  extra_form_data: {}
  dashboards:
  - 24
query_context: '{"datasource":{"id":38,"type":"table"},"force":false,"queries":[{"filters":[{"col":"courserunenrollment_is_active","op":"IN","val":[true]}],"extras":{"having":"","where":""},"applied_time_extras":{},"columns":[],"metrics":[{"aggregate":"COUNT_DISTINCT","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"user_email","description":null,"expression":null,"filterable":true,"groupby":true,"id":480,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":"VARCHAR","type_generic":1,"verbose_name":null,"warning_markdown":null},"datasourceWarning":false,"expressionType":"SIMPLE","hasCustomLabel":false,"label":"COUNT_DISTINCT(user_email)","optionName":"metric_5843lrl7hfu_w3oti257dj","sqlExpression":null}],"annotation_layers":[],"series_limit":0,"order_desc":true,"url_params":{},"custom_params":{},"custom_form_data":{}}],"form_data":{"adhoc_filters":[{"clause":"WHERE","comparator":[true],"datasourceWarning":false,"expressionType":"SIMPLE","filterOptionName":"filter_o2n4rpik3b_cz5k34mkm7a","isExtra":false,"isNew":false,"operator":"IN","operatorId":"IN","sqlExpression":null,"subject":"courserunenrollment_is_active"}],"dashboards":[24],"datasource":"38__table","extra_form_data":{},"header_font_size":0.4,"metric":{"aggregate":"COUNT_DISTINCT","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"user_email","description":null,"expression":null,"filterable":true,"groupby":true,"id":480,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":"VARCHAR","type_generic":1,"verbose_name":null,"warning_markdown":null},"datasourceWarning":false,"expressionType":"SIMPLE","hasCustomLabel":false,"label":"COUNT_DISTINCT(user_email)","optionName":"metric_5843lrl7hfu_w3oti257dj","sqlExpression":null},"slice_id":56,"subheader_font_size":0.15,"time_format":"smart_date","viz_type":"big_number_total","y_axis_format":"SMART_NUMBER","force":false,"result_format":"json","result_type":"full"},"result_format":"json","result_type":"full"}'
cache_timeout:
uuid: c0066291-5b04-437d-b41d-3a4412aa8c82
version: 1.0.0
dataset_uuid: f3e517dd-4012-441e-8dfe-edaef1318000
