slice_name: Learners Enrolled
description: null
certified_by: null
certification_details: null
viz_type: big_number_total
params:
  datasource: 38__table
  viz_type: big_number_total
  slice_id: 45
  metric:
    expressionType: SIMPLE
    column:
      advanced_data_type: null
      certification_details: null
      certified_by: null
      column_name: user_email
      description: null
      expression: null
      filterable: true
      groupby: true
      id: 480
      is_certified: false
      is_dttm: false
      python_date_format: null
      type: VARCHAR
      type_generic: 1
      verbose_name: null
      warning_markdown: null
    aggregate: COUNT_DISTINCT
    sqlExpression: null
    datasourceWarning: false
    hasCustomLabel: false
    label: COUNT_DISTINCT(user_email)
    optionName: metric_5843lrl7hfu_w3oti257dj
  adhoc_filters:
  - clause: WHERE
    comparator:
    - true
    datasourceWarning: false
    expressionType: SIMPLE
    filterOptionName: filter_o2n4rpik3b_cz5k34mkm7a
    isExtra: false
    isNew: false
    operator: IN
    operatorId: IN
    sqlExpression: null
    subject: courserunenrollment_is_active
  header_font_size: 0.4
  subheader_font_size: 0.15
  y_axis_format: SMART_NUMBER
  time_format: smart_date
  extra_form_data: {}
  dashboards:
  - 24
  - 27
query_context: '{"datasource":{"id":38,"type":"table"},"force":false,"queries":[{"filters":[{"col":"courserunenrollment_is_active","op":"IN","val":[true]}],"extras":{"having":"","where":""},"applied_time_extras":{},"columns":[],"metrics":[{"expressionType":"SIMPLE","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"user_email","description":null,"expression":null,"filterable":true,"groupby":true,"id":480,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":"VARCHAR","type_generic":1,"verbose_name":null,"warning_markdown":null},"aggregate":"COUNT_DISTINCT","sqlExpression":null,"datasourceWarning":false,"hasCustomLabel":false,"label":"COUNT_DISTINCT(user_email)","optionName":"metric_5843lrl7hfu_w3oti257dj"}],"annotation_layers":[],"series_limit":0,"order_desc":true,"url_params":{},"custom_params":{},"custom_form_data":{__JINJA2_CLOSE__],"form_data":{"datasource":"38__table","viz_type":"big_number_total","slice_id":45,"metric":{"expressionType":"SIMPLE","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"user_email","description":null,"expression":null,"filterable":true,"groupby":true,"id":480,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":"VARCHAR","type_generic":1,"verbose_name":null,"warning_markdown":null},"aggregate":"COUNT_DISTINCT","sqlExpression":null,"datasourceWarning":false,"hasCustomLabel":false,"label":"COUNT_DISTINCT(user_email)","optionName":"metric_5843lrl7hfu_w3oti257dj"},"adhoc_filters":[{"clause":"WHERE","comparator":[true],"datasourceWarning":false,"expressionType":"SIMPLE","filterOptionName":"filter_o2n4rpik3b_cz5k34mkm7a","isExtra":false,"isNew":false,"operator":"IN","operatorId":"IN","sqlExpression":null,"subject":"courserunenrollment_is_active"}],"header_font_size":0.4,"subheader_font_size":0.15,"y_axis_format":"SMART_NUMBER","time_format":"smart_date","extra_form_data":{},"dashboards":[24,27],"force":false,"result_format":"json","result_type":"full"},"result_format":"json","result_type":"full"}'
cache_timeout: null
uuid: 37d70f20-6dcc-4237-921b-521dc43425a7
version: 1.0.0
dataset_uuid: f3e517dd-4012-441e-8dfe-edaef1318000
