slice_name: Learn New Users
description: null
certified_by: null
certification_details: null
viz_type: echarts_timeseries_bar
params:
  datasource: 84__table
  viz_type: echarts_timeseries_bar
  slice_id: 146
  x_axis: date_joined_on_mitlearn
  time_grain_sqla: P1W
  metrics:
  - count
  groupby: []
  adhoc_filters:
  - clause: WHERE
    datasourceWarning: false
    expressionType: SIMPLE
    filterOptionName: filter_0ibm6pfbybok_6d7edn5vmkr
    isExtra: false
    isNew: false
    operator: IS NOT NULL
    operatorId: IS_NOT_NULL
    sqlExpression: null
    subject: mitlearn_user_id
  - clause: WHERE
    comparator: No filter
    expressionType: SIMPLE
    operator: TEMPORAL_RANGE
    subject: date_joined_on_mitlearn
  row_limit: 10000
  truncate_metric: true
  show_empty_columns: true
  rolling_type: sum
  comparison_type: values
  annotation_layers: []
  forecastPeriods: 10
  forecastInterval: 0.8
  orientation: vertical
  x_axis_title: Account Created
  x_axis_title_margin: 50
  y_axis_title: Number of Users
  y_axis_title_margin: 30
  y_axis_title_position: Left
  sort_series_type: sum
  color_scheme: supersetColors
  show_value: false
  stack: null
  minorTicks: false
  zoomable: true
  show_legend: true
  legendType: scroll
  legendOrientation: top
  legendMargin: null
  x_axis_time_format: smart_date
  y_axis_format: SMART_NUMBER
  logAxis: true
  y_axis_bounds:
  - null
  - null
  truncateXAxis: true
  xAxisBounds:
  - null
  - null
  rich_tooltip: true
  showTooltipTotal: true
  tooltipTimeFormat: smart_date
  extra_form_data: {}
  dashboards:
  - 49
query_context: '{"datasource":{"id":84,"type":"table"},"force":false,"queries":[{"filters":[{"col":"mitlearn_user_id","op":"IS
  NOT NULL"},{"col":"date_joined_on_mitlearn","op":"TEMPORAL_RANGE","val":"No filter"}],"extras":{"time_grain_sqla":"P1W","having":"","where":""},"applied_time_extras":{},"columns":[{"timeGrain":"P1W","columnType":"BASE_AXIS","sqlExpression":"date_joined_on_mitlearn","label":"date_joined_on_mitlearn","expressionType":"SQL"}],"metrics":["count"],"orderby":[["count",false]],"annotation_layers":[],"row_limit":10000,"series_columns":[],"series_limit":0,"order_desc":true,"url_params":{},"custom_params":{},"custom_form_data":{},"time_offsets":[],"post_processing":[{"operation":"pivot","options":{"index":["date_joined_on_mitlearn"],"columns":[],"aggregates":{"count":{"operator":"mean"}},"drop_missing_columns":false}},{"operation":"rolling","options":{"rolling_type":"sum","window":1,"min_periods":0,"columns":{"count":"count"}}},{"operation":"flatten"}]}],"form_data":{"datasource":"84__table","viz_type":"echarts_timeseries_bar","slice_id":146,"x_axis":"date_joined_on_mitlearn","time_grain_sqla":"P1W","metrics":["count"],"groupby":[],"adhoc_filters":[{"clause":"WHERE","datasourceWarning":false,"expressionType":"SIMPLE","filterOptionName":"filter_0ibm6pfbybok_6d7edn5vmkr","isExtra":false,"isNew":false,"operator":"IS
  NOT NULL","operatorId":"IS_NOT_NULL","sqlExpression":null,"subject":"mitlearn_user_id"},{"clause":"WHERE","comparator":"No
  filter","expressionType":"SIMPLE","operator":"TEMPORAL_RANGE","subject":"date_joined_on_mitlearn"}],"row_limit":10000,"truncate_metric":true,"show_empty_columns":true,"rolling_type":"sum","comparison_type":"values","annotation_layers":[],"forecastPeriods":10,"forecastInterval":0.8,"orientation":"vertical","x_axis_title":"Account
  Created","x_axis_title_margin":50,"y_axis_title":"Number of Users","y_axis_title_margin":30,"y_axis_title_position":"Left","sort_series_type":"sum","color_scheme":"supersetColors","show_value":false,"stack":null,"minorTicks":false,"zoomable":true,"show_legend":true,"legendType":"scroll","legendOrientation":"top","legendMargin":null,"x_axis_time_format":"smart_date","y_axis_format":"SMART_NUMBER","logAxis":true,"y_axis_bounds":[null,null],"truncateXAxis":true,"xAxisBounds":[null,null],"rich_tooltip":true,"showTooltipTotal":true,"tooltipTimeFormat":"smart_date","extra_form_data":{},"dashboards":[49],"force":false,"result_format":"json","result_type":"full"},"result_format":"json","result_type":"full"}'
cache_timeout: null
uuid: 5cba1239-2f4c-472b-82f6-788f18de0fd2
version: 1.0.0
dataset_uuid: 7f46cdba-1bf0-4f10-9606-a41b77b9e77c
