---
slice_name: Learner Problem Engagement
description:
certified_by:
certification_details:
viz_type: table
params:
  datasource: 65__table
  viz_type: table
  slice_id: 84
  query_mode: raw
  groupby: []
  temporal_columns_lookup: {}
  all_columns:
  - user_email
  - full_name
  - courserun_readable_id
  - section_title
  - subsection_title
  - problem_title
  - num_of_attempts
  - num_of_correct_attempts
  - max_possible_grade
  - learner_lowest_grade
  - learner_highest_grade
  percent_metrics: []
  adhoc_filters: []
  order_by_cols:
  - '["section_block_index", true]'
  - '["subsection_block_index", true]'
  order_desc: true
  row_limit: 10000
  server_page_length: 10
  table_timestamp_format: smart_date
  include_search: true
  allow_render_html: true
  column_config:
    learner_highest_grade:
      showCellBars: false
    learner_lowest_grade:
      showCellBars: false
    max_possible_grade:
      showCellBars: false
    num_of_correct_attempts:
      showCellBars: false
  show_cell_bars: true
  color_pn: true
  comparison_color_scheme: Green
  conditional_formatting: []
  comparison_type: values
  extra_form_data: {}
  dashboards:
  - 45
query_context: '{"datasource":{"id":65,"type":"table"},"force":false,"queries":[{"filters":[],"extras":{"having":"","where":""},"applied_time_extras":{},"columns":["user_email","full_name","courserun_readable_id","section_title","subsection_title","problem_title","num_of_attempts","num_of_correct_attempts","max_possible_grade","learner_lowest_grade","learner_highest_grade"],"orderby":[["section_block_index",true],["subsection_block_index",true]],"annotation_layers":[],"row_limit":10000,"series_limit":0,"order_desc":true,"url_params":{},"custom_params":{},"custom_form_data":{},"post_processing":[],"time_offsets":[]}],"form_data":{"datasource":"65__table","viz_type":"table","slice_id":84,"query_mode":"raw","groupby":[],"temporal_columns_lookup":{},"all_columns":["user_email","full_name","courserun_readable_id","section_title","subsection_title","problem_title","num_of_attempts","num_of_correct_attempts","max_possible_grade","learner_lowest_grade","learner_highest_grade"],"percent_metrics":[],"adhoc_filters":[],"order_by_cols":["[\"section_block_index\",
  true]","[\"subsection_block_index\", true]"],"order_desc":true,"row_limit":10000,"server_page_length":10,"table_timestamp_format":"smart_date","include_search":true,"allow_render_html":true,"column_config":{"learner_highest_grade":{"showCellBars":false},"learner_lowest_grade":{"showCellBars":false},"max_possible_grade":{"showCellBars":false},"num_of_correct_attempts":{"showCellBars":false}},"show_cell_bars":true,"color_pn":true,"comparison_color_scheme":"Green","conditional_formatting":[],"comparison_type":"values","extra_form_data":{},"dashboards":[45],"force":false,"result_format":"json","result_type":"full","include_time":false},"result_format":"json","result_type":"full"}'
cache_timeout:
uuid: 695dd2d8-48d5-436b-a646-204bdf5f2be5
version: 1.0.0
dataset_uuid: b9e94ba2-f399-4210-b042-b8aaa4039f58
