slice_name: MITxOnline Enrollment Activity
description: null
certified_by: null
certification_details: null
viz_type: echarts_area
params:
  adhoc_filters: []
  annotation_layers: []
  color_scheme: supersetColors
  comparison_type: values
  dashboards:
  - 5
  datasource: 2__table
  extra_form_data: {}
  forecastInterval: 0.8
  forecastPeriods: 10
  groupby: []
  legendOrientation: top
  legendType: scroll
  markerSize: 6
  metrics:
  - aggregate: null
    column: null
    datasourceWarning: false
    expressionType: SQL
    hasCustomLabel: true
    label: verified_count
    optionName: metric_n2jmx6hwai_dppg711uhn6
    sqlExpression: sum(case when courserunenrollment_enrollment_mode= 'verified' then
      1 else 0 end)
  - aggregate: null
    column: null
    datasourceWarning: false
    expressionType: SQL
    hasCustomLabel: true
    label: audit_count
    optionName: metric_h6yl06zrsvi_ioalqftnb9s
    sqlExpression: sum(case when courserunenrollment_enrollment_mode= 'audit' then
      1 else 0 end)
  - aggregate: null
    column: null
    datasourceWarning: false
    expressionType: SQL
    hasCustomLabel: true
    label: total_enrollment_count
    optionName: metric_yd4mcqx26io_cz6zy2hssf5
    sqlExpression: count(*)
  only_total: true
  opacity: 0.2
  order_desc: true
  rich_tooltip: true
  rolling_type: cumsum
  row_limit: 10000
  seriesType: line
  show_empty_columns: true
  show_legend: true
  slice_id: 7
  sort_series_type: sum
  time_grain_sqla: P1D
  timeseries_limit_metric:
    aggregate: null
    column: null
    datasourceWarning: false
    expressionType: SQL
    hasCustomLabel: false
    label: MIN(courserunenrollment_created_on)
    optionName: metric_q5qzyqzlh4b_a14q0ei293
    sqlExpression: MIN(courserunenrollment_created_on)
  tooltipTimeFormat: smart_date
  truncate_metric: true
  viz_type: echarts_area
  x_axis:
    expressionType: SQL
    label: enrollment_date
    sqlExpression: cast(substring(courserunenrollment_created_on, 1, 10) as date)
  x_axis_sort: name
  x_axis_sort_asc: true
  x_axis_time_format: smart_date
  x_axis_title_margin: 15
  y_axis_bounds:
  - null
  - null
  y_axis_format: SMART_NUMBER
  y_axis_title_margin: 15
  y_axis_title_position: Left
query_context: '{"datasource":{"id":2,"type":"table"},"force":false,"queries":[{"filters":[],"extras":{"having":"","where":""},"applied_time_extras":{},"columns":[{"timeGrain":"P1D","columnType":"BASE_AXIS","expressionType":"SQL","label":"enrollment_date","sqlExpression":"cast(substring(courserunenrollment_created_on,
  1, 10) as date)"}],"metrics":[{"aggregate":null,"column":null,"datasourceWarning":false,"expressionType":"SQL","hasCustomLabel":true,"label":"verified_count","optionName":"metric_n2jmx6hwai_dppg711uhn6","sqlExpression":"sum(case
  when courserunenrollment_enrollment_mode= ''verified'' then 1 else 0 end)"},{"aggregate":null,"column":null,"datasourceWarning":false,"expressionType":"SQL","hasCustomLabel":true,"label":"audit_count","optionName":"metric_h6yl06zrsvi_ioalqftnb9s","sqlExpression":"sum(case
  when courserunenrollment_enrollment_mode= ''audit'' then 1 else 0 end)"},{"aggregate":null,"column":null,"datasourceWarning":false,"expressionType":"SQL","hasCustomLabel":true,"label":"total_enrollment_count","optionName":"metric_yd4mcqx26io_cz6zy2hssf5","sqlExpression":"count(*)"}],"orderby":[[{"aggregate":null,"column":null,"datasourceWarning":false,"expressionType":"SQL","hasCustomLabel":false,"label":"MIN(courserunenrollment_created_on)","optionName":"metric_q5qzyqzlh4b_a14q0ei293","sqlExpression":"MIN(courserunenrollment_created_on)"},false]],"annotation_layers":[],"row_limit":10000,"series_columns":[],"series_limit":0,"series_limit_metric":{"aggregate":null,"column":null,"datasourceWarning":false,"expressionType":"SQL","hasCustomLabel":false,"label":"MIN(courserunenrollment_created_on)","optionName":"metric_q5qzyqzlh4b_a14q0ei293","sqlExpression":"MIN(courserunenrollment_created_on)"},"order_desc":true,"url_params":{},"custom_params":{},"custom_form_data":{},"time_offsets":[],"post_processing":[{"operation":"pivot","options":{"index":["enrollment_date"],"columns":[],"aggregates":{"verified_count":{"operator":"mean"},"audit_count":{"operator":"mean"},"total_enrollment_count":{"operator":"mean"}},"drop_missing_columns":false}},{"operation":"cum","options":{"operator":"sum","columns":{"verified_count":"verified_count","audit_count":"audit_count","total_enrollment_count":"total_enrollment_count"}}},{"operation":"flatten"}]}],"form_data":{"datasource":"2__table","viz_type":"echarts_area","slice_id":7,"x_axis":{"expressionType":"SQL","label":"enrollment_date","sqlExpression":"cast(substring(courserunenrollment_created_on,
  1, 10) as date)"},"time_grain_sqla":"P1D","x_axis_sort_asc":true,"x_axis_sort_series":"name","x_axis_sort_series_ascending":true,"metrics":[{"aggregate":null,"column":null,"datasourceWarning":false,"expressionType":"SQL","hasCustomLabel":true,"label":"verified_count","optionName":"metric_n2jmx6hwai_dppg711uhn6","sqlExpression":"sum(case
  when courserunenrollment_enrollment_mode= ''verified'' then 1 else 0 end)"},{"aggregate":null,"column":null,"datasourceWarning":false,"expressionType":"SQL","hasCustomLabel":true,"label":"audit_count","optionName":"metric_h6yl06zrsvi_ioalqftnb9s","sqlExpression":"sum(case
  when courserunenrollment_enrollment_mode= ''audit'' then 1 else 0 end)"},{"aggregate":null,"column":null,"datasourceWarning":false,"expressionType":"SQL","hasCustomLabel":true,"label":"total_enrollment_count","optionName":"metric_yd4mcqx26io_cz6zy2hssf5","sqlExpression":"count(*)"}],"groupby":[],"adhoc_filters":[],"timeseries_limit_metric":{"aggregate":null,"column":null,"datasourceWarning":false,"expressionType":"SQL","hasCustomLabel":false,"label":"MIN(courserunenrollment_created_on)","optionName":"metric_q5qzyqzlh4b_a14q0ei293","sqlExpression":"MIN(courserunenrollment_created_on)"},"order_desc":true,"row_limit":10000,"truncate_metric":true,"show_empty_columns":true,"rolling_type":"cumsum","comparison_type":"values","annotation_layers":[],"forecastPeriods":10,"forecastInterval":0.8,"x_axis_title_margin":15,"y_axis_title_margin":15,"y_axis_title_position":"Left","sort_series_type":"sum","color_scheme":"supersetColors","seriesType":"line","opacity":0.2,"only_total":true,"markerSize":6,"show_legend":true,"legendType":"scroll","legendOrientation":"top","x_axis_time_format":"smart_date","rich_tooltip":true,"tooltipTimeFormat":"smart_date","y_axis_format":"SMART_NUMBER","y_axis_bounds":[null,null],"extra_form_data":{},"dashboards":[5],"force":false,"result_format":"json","result_type":"full"},"result_format":"json","result_type":"full"}'
cache_timeout: null
uuid: 6fd11c69-4110-465f-8ed6-bfcdbe59b8b4
version: 1.0.0
