slice_name: MITxOnline Earned Certificate
description: null
certified_by: null
certification_details: null
viz_type: echarts_timeseries_line
params:
  datasource: 13__table
  viz_type: echarts_timeseries_line
  slice_id: 12
  x_axis:
    expressionType: SQL
    label: courseruncertificate_created_on
    sqlExpression: cast(substring(courseruncertificate_created_on, 1, 10) as date)
  time_grain_sqla: P1D
  metrics:
  - aggregate: null
    column: null
    datasourceWarning: false
    expressionType: SQL
    hasCustomLabel: true
    label: Certificate_count
    optionName: metric_v39mqis8me8_uw74ltnpo5q
    sqlExpression: count(*)
  groupby: []
  adhoc_filters: []
  row_limit: 10000
  truncate_metric: true
  show_empty_columns: true
  comparison_type: values
  annotation_layers: []
  forecastPeriods: 10
  forecastInterval: 0.8
  x_axis_title_margin: 15
  y_axis_title_margin: 15
  y_axis_title_position: Left
  sort_series_type: sum
  color_scheme: supersetColors
  seriesType: line
  zoomable: true
  show_legend: true
  legendType: scroll
  legendOrientation: top
  x_axis_time_format: smart_date
  rich_tooltip: true
  tooltipTimeFormat: smart_date
  y_axis_format: SMART_NUMBER
  truncateXAxis: true
  extra_form_data: {}
  dashboards:
  - 7
  - 20
query_context: '{"datasource":{"id":13,"type":"table"},"force":false,"queries":[{"filters":[],"extras":{"time_grain_sqla":"P1D","having":"","where":""},"applied_time_extras":{},"columns":[{"timeGrain":"P1D","columnType":"BASE_AXIS","expressionType":"SQL","label":"courseruncertificate_created_on","sqlExpression":"cast(substring(courseruncertificate_created_on,
  1, 10) as date)"}],"metrics":[{"aggregate":null,"column":null,"datasourceWarning":false,"expressionType":"SQL","hasCustomLabel":true,"label":"Certificate_count","optionName":"metric_v39mqis8me8_uw74ltnpo5q","sqlExpression":"count(*)"}],"orderby":[[{"aggregate":null,"column":null,"datasourceWarning":false,"expressionType":"SQL","hasCustomLabel":true,"label":"Certificate_count","optionName":"metric_v39mqis8me8_uw74ltnpo5q","sqlExpression":"count(*)"},false]],"annotation_layers":[],"row_limit":10000,"series_columns":[],"series_limit":0,"order_desc":true,"url_params":{},"custom_params":{},"custom_form_data":{},"time_offsets":[],"post_processing":[{"operation":"pivot","options":{"index":["courseruncertificate_created_on"],"columns":[],"aggregates":{"Certificate_count":{"operator":"mean"}},"drop_missing_columns":false}},{"operation":"flatten"}]}],"form_data":{"datasource":"13__table","viz_type":"echarts_timeseries_line","slice_id":12,"x_axis":{"expressionType":"SQL","label":"courseruncertificate_created_on","sqlExpression":"cast(substring(courseruncertificate_created_on,
  1, 10) as date)"},"time_grain_sqla":"P1D","metrics":[{"aggregate":null,"column":null,"datasourceWarning":false,"expressionType":"SQL","hasCustomLabel":true,"label":"Certificate_count","optionName":"metric_v39mqis8me8_uw74ltnpo5q","sqlExpression":"count(*)"}],"groupby":[],"adhoc_filters":[],"row_limit":10000,"truncate_metric":true,"show_empty_columns":true,"comparison_type":"values","annotation_layers":[],"forecastPeriods":10,"forecastInterval":0.8,"x_axis_title_margin":15,"y_axis_title_margin":15,"y_axis_title_position":"Left","sort_series_type":"sum","color_scheme":"supersetColors","seriesType":"line","zoomable":true,"show_legend":true,"legendType":"scroll","legendOrientation":"top","x_axis_time_format":"smart_date","rich_tooltip":true,"tooltipTimeFormat":"smart_date","y_axis_format":"SMART_NUMBER","truncateXAxis":true,"extra_form_data":{},"dashboards":[7,20],"force":false,"result_format":"json","result_type":"full"},"result_format":"json","result_type":"full"}'
cache_timeout: null
uuid: d953e953-a5d6-4e48-af54-5b0e033a401c
version: 1.0.0
dataset_uuid: 45f0412f-0d34-4d04-a3ff-e595a3bada19
