---
slice_name: MITxOnline Enrollment Demographics by Gender
description:
certified_by:
certification_details:
viz_type: echarts_timeseries_bar
params:
  datasource: 2__table
  viz_type: echarts_timeseries_bar
  slice_id: 9
  x_axis: user_gender
  time_grain_sqla: P1D
  x_axis_sort_asc: true
  x_axis_sort_series: name
  x_axis_sort_series_ascending: true
  metrics:
  - aggregate:
    column:
    datasourceWarning: false
    expressionType: SQL
    hasCustomLabel: true
    label: Enrollment_count
    optionName: metric_w8255bgremp_lh56mhwqeqc
    sqlExpression: count(*)
  groupby: []
  adhoc_filters: []
  order_desc: true
  row_limit: 10000
  truncate_metric: true
  show_empty_columns: true
  comparison_type: values
  annotation_layers: []
  forecastPeriods: 10
  forecastInterval: 0.8
  orientation: vertical
  x_axis_title_margin: 15
  y_axis_title_margin: 15
  y_axis_title_position: Left
  sort_series_type: sum
  color_scheme: supersetColors
  only_total: true
  show_legend: true
  legendType: scroll
  legendOrientation: top
  x_axis_time_format: smart_date
  y_axis_format: SMART_NUMBER
  y_axis_bounds:
  - 
  - 
  rich_tooltip: true
  tooltipTimeFormat: smart_date
  extra_form_data: {}
  dashboards:
  - 5
query_context: '{"datasource":{"id":2,"type":"table"},"force":false,"queries":[{"filters":[],"extras":{"having":"","where":""},"applied_time_extras":{},"columns":[{"timeGrain":"P1D","columnType":"BASE_AXIS","sqlExpression":"user_gender","label":"user_gender","expressionType":"SQL"}],"metrics":[{"aggregate":null,"column":null,"datasourceWarning":false,"expressionType":"SQL","hasCustomLabel":true,"label":"Enrollment_count","optionName":"metric_w8255bgremp_lh56mhwqeqc","sqlExpression":"count(*)"}],"orderby":[[{"aggregate":null,"column":null,"datasourceWarning":false,"expressionType":"SQL","hasCustomLabel":true,"label":"Enrollment_count","optionName":"metric_w8255bgremp_lh56mhwqeqc","sqlExpression":"count(*)"},false]],"annotation_layers":[],"row_limit":10000,"series_columns":[],"series_limit":0,"order_desc":true,"url_params":{},"custom_params":{},"custom_form_data":{},"time_offsets":[],"post_processing":[{"operation":"pivot","options":{"index":["user_gender"],"columns":[],"aggregates":{"Enrollment_count":{"operator":"mean"__JINJA2_CLOSE__,"drop_missing_columns":false__JINJA2_CLOSE__,{"operation":"flatten"}]}],"form_data":{"datasource":"2__table","viz_type":"echarts_timeseries_bar","slice_id":9,"x_axis":"user_gender","time_grain_sqla":"P1D","x_axis_sort_asc":true,"x_axis_sort_series":"name","x_axis_sort_series_ascending":true,"metrics":[{"aggregate":null,"column":null,"datasourceWarning":false,"expressionType":"SQL","hasCustomLabel":true,"label":"Enrollment_count","optionName":"metric_w8255bgremp_lh56mhwqeqc","sqlExpression":"count(*)"}],"groupby":[],"adhoc_filters":[],"order_desc":true,"row_limit":10000,"truncate_metric":true,"show_empty_columns":true,"comparison_type":"values","annotation_layers":[],"forecastPeriods":10,"forecastInterval":0.8,"orientation":"vertical","x_axis_title_margin":15,"y_axis_title_margin":15,"y_axis_title_position":"Left","sort_series_type":"sum","color_scheme":"supersetColors","only_total":true,"show_legend":true,"legendType":"scroll","legendOrientation":"top","x_axis_time_format":"smart_date","y_axis_format":"SMART_NUMBER","y_axis_bounds":[null,null],"rich_tooltip":true,"tooltipTimeFormat":"smart_date","extra_form_data":{},"dashboards":[5],"force":false,"result_format":"json","result_type":"full"},"result_format":"json","result_type":"full"}'
cache_timeout:
uuid: 57721cfb-3413-484d-abfa-cb1be38daafe
version: 1.0.0
