slice_name: MITxOnline Learner Enrollments- All Course
description: null
certified_by: null
certification_details: null
viz_type: echarts_area
params:
  adhoc_filters:
  - clause: WHERE
    comparator: null
    datasourceWarning: false
    expressionType: SQL
    filterOptionName: filter_roqh2v2cnt_1lmxzd5d78f
    isExtra: false
    isNew: false
    operator: null
    sqlExpression: courserunenrollment_created_on >= '2021-01-01 00:00:00'
    subject: null
  annotation_layers: []
  color_scheme: supersetColors
  comparison_type: values
  dashboards: []
  datasource: 3__table
  extra_form_data: {}
  forecastInterval: 0.8
  forecastPeriods: 10
  groupby: []
  legendOrientation: top
  legendType: scroll
  markerSize: 6
  metrics:
  - aggregate: null
    column: null
    datasourceWarning: false
    expressionType: SQL
    hasCustomLabel: true
    label: verified_count
    optionName: metric_xa8dkyvc2g_zhsl5l9t3k
    sqlExpression: sum(case when courserunenrollment_enrollment_mode= 'verified' then
      1 else 0 end)
  - aggregate: null
    column: null
    datasourceWarning: false
    expressionType: SQL
    hasCustomLabel: true
    label: audit_count
    optionName: metric_qsumaa2pde7_3gxypcd1u5m
    sqlExpression: 'sum(case when courserunenrollment_enrollment_mode= ''audit'' then
      1 else 0 end) '
  - aggregate: null
    column: null
    datasourceWarning: false
    expressionType: SQL
    hasCustomLabel: true
    label: total_enrollment_count
    optionName: metric_7vr6wa9k7uv_r69aq2ikm3j
    sqlExpression: count(*)
  only_total: true
  opacity: 0.2
  order_desc: true
  rich_tooltip: true
  rolling_type: cumsum
  row_limit: 50000
  seriesType: line
  show_empty_columns: true
  show_legend: true
  slice_id: 5
  sort_series_type: sum
  time_grain_sqla: P1D
  timeseries_limit_metric:
    aggregate: MIN
    column:
      advanced_data_type: null
      certification_details: null
      certified_by: null
      column_name: courserunenrollment_created_on
      description: null
      expression: null
      filterable: true
      groupby: true
      id: 36
      is_certified: false
      is_dttm: false
      python_date_format: null
      type: VARCHAR
      type_generic: 1
      verbose_name: null
      warning_markdown: null
    datasourceWarning: false
    expressionType: SIMPLE
    hasCustomLabel: false
    label: MIN(courserunenrollment_created_on)
    optionName: metric_ui1awwyv6k_72ybjbwgamf
    sqlExpression: null
  tooltipTimeFormat: smart_date
  truncate_metric: true
  viz_type: echarts_area
  x_axis:
    expressionType: SQL
    label: Enrollment_date
    sqlExpression: cast(substring(courserunenrollment_created_on, 1, 10) as date)
  x_axis_sort: name
  x_axis_sort_asc: true
  x_axis_time_format: smart_date
  x_axis_title_margin: 15
  y_axis_bounds:
  - null
  - null
  y_axis_format: SMART_NUMBER
  y_axis_title_margin: 15
  y_axis_title_position: Left
query_context: '{"datasource":{"id":3,"type":"table"},"force":false,"queries":[{"filters":[],"extras":{"having":"","where":"(courserunenrollment_created_on
  >= ''2021-01-01 00:00:00'')"},"applied_time_extras":{},"columns":[{"timeGrain":"P1D","columnType":"BASE_AXIS","expressionType":"SQL","label":"Enrollment_date","sqlExpression":"cast(substring(courserunenrollment_created_on,
  1, 10) as date)"}],"metrics":[{"aggregate":null,"column":null,"datasourceWarning":false,"expressionType":"SQL","hasCustomLabel":true,"label":"verified_count","optionName":"metric_xa8dkyvc2g_zhsl5l9t3k","sqlExpression":"sum(case
  when courserunenrollment_enrollment_mode= ''verified'' then 1 else 0 end)"},{"aggregate":null,"column":null,"datasourceWarning":false,"expressionType":"SQL","hasCustomLabel":true,"label":"audit_count","optionName":"metric_qsumaa2pde7_3gxypcd1u5m","sqlExpression":"sum(case
  when courserunenrollment_enrollment_mode= ''audit'' then 1 else 0 end) "},{"aggregate":null,"column":null,"datasourceWarning":false,"expressionType":"SQL","hasCustomLabel":true,"label":"total_enrollment_count","optionName":"metric_7vr6wa9k7uv_r69aq2ikm3j","sqlExpression":"count(*)"}],"orderby":[[{"aggregate":"MIN","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"courserunenrollment_created_on","description":null,"expression":null,"filterable":true,"groupby":true,"id":36,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":"VARCHAR","type_generic":1,"verbose_name":null,"warning_markdown":null},"datasourceWarning":false,"expressionType":"SIMPLE","hasCustomLabel":false,"label":"MIN(courserunenrollment_created_on)","optionName":"metric_ui1awwyv6k_72ybjbwgamf","sqlExpression":null},false]],"annotation_layers":[],"row_limit":50000,"series_columns":[],"series_limit":0,"series_limit_metric":{"aggregate":"MIN","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"courserunenrollment_created_on","description":null,"expression":null,"filterable":true,"groupby":true,"id":36,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":"VARCHAR","type_generic":1,"verbose_name":null,"warning_markdown":null},"datasourceWarning":false,"expressionType":"SIMPLE","hasCustomLabel":false,"label":"MIN(courserunenrollment_created_on)","optionName":"metric_ui1awwyv6k_72ybjbwgamf","sqlExpression":null},"order_desc":true,"url_params":{},"custom_params":{},"custom_form_data":{},"time_offsets":[],"post_processing":[{"operation":"pivot","options":{"index":["Enrollment_date"],"columns":[],"aggregates":{"verified_count":{"operator":"mean"},"audit_count":{"operator":"mean"},"total_enrollment_count":{"operator":"mean"}},"drop_missing_columns":false}},{"operation":"cum","options":{"operator":"sum","columns":{"verified_count":"verified_count","audit_count":"audit_count","total_enrollment_count":"total_enrollment_count"}}},{"operation":"flatten"}]}],"form_data":{"datasource":"3__table","viz_type":"echarts_area","slice_id":5,"x_axis":{"expressionType":"SQL","label":"Enrollment_date","sqlExpression":"cast(substring(courserunenrollment_created_on,
  1, 10) as date)"},"time_grain_sqla":"P1D","x_axis_sort_asc":true,"x_axis_sort_series":"name","x_axis_sort_series_ascending":true,"metrics":[{"aggregate":null,"column":null,"datasourceWarning":false,"expressionType":"SQL","hasCustomLabel":true,"label":"verified_count","optionName":"metric_xa8dkyvc2g_zhsl5l9t3k","sqlExpression":"sum(case
  when courserunenrollment_enrollment_mode= ''verified'' then 1 else 0 end)"},{"aggregate":null,"column":null,"datasourceWarning":false,"expressionType":"SQL","hasCustomLabel":true,"label":"audit_count","optionName":"metric_qsumaa2pde7_3gxypcd1u5m","sqlExpression":"sum(case
  when courserunenrollment_enrollment_mode= ''audit'' then 1 else 0 end) "},{"aggregate":null,"column":null,"datasourceWarning":false,"expressionType":"SQL","hasCustomLabel":true,"label":"total_enrollment_count","optionName":"metric_7vr6wa9k7uv_r69aq2ikm3j","sqlExpression":"count(*)"}],"groupby":[],"adhoc_filters":[{"clause":"WHERE","comparator":null,"datasourceWarning":false,"expressionType":"SQL","filterOptionName":"filter_roqh2v2cnt_1lmxzd5d78f","isExtra":false,"isNew":false,"operator":null,"sqlExpression":"courserunenrollment_created_on
  >= ''2021-01-01 00:00:00''","subject":null}],"timeseries_limit_metric":{"aggregate":"MIN","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"courserunenrollment_created_on","description":null,"expression":null,"filterable":true,"groupby":true,"id":36,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":"VARCHAR","type_generic":1,"verbose_name":null,"warning_markdown":null},"datasourceWarning":false,"expressionType":"SIMPLE","hasCustomLabel":false,"label":"MIN(courserunenrollment_created_on)","optionName":"metric_ui1awwyv6k_72ybjbwgamf","sqlExpression":null},"order_desc":true,"row_limit":50000,"truncate_metric":true,"show_empty_columns":true,"rolling_type":"cumsum","comparison_type":"values","annotation_layers":[],"forecastPeriods":10,"forecastInterval":0.8,"x_axis_title_margin":15,"y_axis_title_margin":15,"y_axis_title_position":"Left","sort_series_type":"sum","color_scheme":"supersetColors","seriesType":"line","opacity":0.2,"only_total":true,"markerSize":6,"show_legend":true,"legendType":"scroll","legendOrientation":"top","x_axis_time_format":"smart_date","rich_tooltip":true,"tooltipTimeFormat":"smart_date","y_axis_format":"SMART_NUMBER","y_axis_bounds":[null,null],"extra_form_data":{},"dashboards":[],"force":false,"result_format":"json","result_type":"full"},"result_format":"json","result_type":"full"}'
cache_timeout: null
uuid: ab3dd918-2308-446f-8d81-f89ac4f342cf
version: 1.0.0
