---
slice_name: MITxOnline Content Engagement
description:
certified_by:
certification_details:
viz_type: echarts_timeseries_line
params:
  adhoc_filters:
  - clause: WHERE
    comparator: No filter
    datasourceWarning: false
    expressionType: SIMPLE
    filterOptionName: filter_vmnxg0351v_lspf9hzyi4i
    isExtra: false
    isNew: false
    operator: TEMPORAL_RANGE
    sqlExpression:
    subject: courseactivity_date
  annotation_layers: []
  area: false
  color_scheme: supersetColors
  comparison_type: values
  dashboards:
  - 7
  datasource: 10__table
  extra_form_data: {}
  forecastInterval: 0.8
  forecastPeriods: 10
  groupby: []
  legendOrientation: top
  legendType: scroll
  logAxis: false
  markerEnabled: true
  markerSize: 6
  metrics:
  - aggregate:
    column:
    datasourceWarning: false
    expressionType: SQL
    hasCustomLabel: true
    label: Watched_a_video
    optionName: metric_nn1wefuu2db_mpukfx7sm3p
    sqlExpression: SUM(CASE WHEN num_video_played> 0 THEN 1 ELSE 0 END)
  - aggregate:
    column:
    datasourceWarning: false
    expressionType: SQL
    hasCustomLabel: true
    label: Tried_a_problem
    optionName: metric_5dkp4rc3smx_j5uh6anrsrg
    sqlExpression: SUM(case when num_problem_submitted> 0 then 1 else 0 end)
  - aggregate:
    column:
    datasourceWarning: false
    expressionType: SQL
    hasCustomLabel: true
    label: Participated_In_Discussion
    optionName: metric_nyeto5r6o1_a3bqgmcrvng
    sqlExpression: SUM(case when num_discussion_participated> 0 then 1 else 0 end)
  - aggregate: COUNT_DISTINCT
    column:
      advanced_data_type:
      certification_details:
      certified_by:
      column_name: user_username
      description:
      expression:
      filterable: true
      groupby: true
      id: 123
      is_certified: false
      is_dttm: false
      python_date_format:
      type: VARCHAR
      type_generic: 1
      verbose_name:
      warning_markdown:
    datasourceWarning: false
    expressionType: SIMPLE
    hasCustomLabel: true
    label: Learner_count
    optionName: metric_455ovz8nu4s_6b2gv5odit3
    sqlExpression:
  only_total: true
  opacity: 0.2
  order_desc: true
  rich_tooltip: true
  row_limit: 10000
  seriesType: line
  show_empty_columns: false
  show_legend: true
  show_value: false
  slice_id: 11
  sort_series_type: sum
  time_grain_sqla: P1W
  timeseries_limit_metric:
    aggregate: MAX
    column:
      advanced_data_type:
      certification_details:
      certified_by:
      column_name: courseactivity_date
      description:
      expression:
      filterable: true
      groupby: true
      id: 122
      is_certified: false
      is_dttm: true
      python_date_format:
      type: DATE
      type_generic: 2
      verbose_name:
      warning_markdown:
    datasourceWarning: false
    expressionType: SIMPLE
    hasCustomLabel: false
    label: MAX(courseactivity_date)
    optionName: metric_okhl5d9h4c_ah7l934rd7f
    sqlExpression:
  tooltipTimeFormat: smart_date
  truncateXAxis: true
  truncate_metric: false
  viz_type: echarts_timeseries_line
  x_axis:
    expressionType: SQL
    label: courseactivity_date
    sqlExpression: courseactivity_date
  x_axis_sort: name
  x_axis_sort_asc: true
  x_axis_time_format: smart_date
  x_axis_title_margin: 15
  y_axis_bounds:
  - 
  - 
  y_axis_format: SMART_NUMBER
  y_axis_title_margin: 15
  y_axis_title_position: Left
  zoomable: true
query_context: '{"datasource":{"id":10,"type":"table"},"force":false,"queries":[{"filters":[{"col":"courseactivity_date","op":"TEMPORAL_RANGE","val":"No
  filter"}],"extras":{"time_grain_sqla":"P1W","having":"","where":""},"applied_time_extras":{},"columns":[{"timeGrain":"P1W","columnType":"BASE_AXIS","expressionType":"SQL","label":"courseactivity_date","sqlExpression":"courseactivity_date"}],"metrics":[{"aggregate":null,"column":null,"datasourceWarning":false,"expressionType":"SQL","hasCustomLabel":true,"label":"Watched_a_video","optionName":"metric_nn1wefuu2db_mpukfx7sm3p","sqlExpression":"SUM(CASE
  WHEN num_video_played> 0 THEN 1 ELSE 0 END)"},{"aggregate":null,"column":null,"datasourceWarning":false,"expressionType":"SQL","hasCustomLabel":true,"label":"Tried_a_problem","optionName":"metric_5dkp4rc3smx_j5uh6anrsrg","sqlExpression":"SUM(case
  when num_problem_submitted> 0 then 1 else 0 end)"},{"aggregate":null,"column":null,"datasourceWarning":false,"expressionType":"SQL","hasCustomLabel":true,"label":"Participated_In_Discussion","optionName":"metric_nyeto5r6o1_a3bqgmcrvng","sqlExpression":"SUM(case
  when num_discussion_participated> 0 then 1 else 0 end)"},{"aggregate":"COUNT_DISTINCT","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"user_username","description":null,"expression":null,"filterable":true,"groupby":true,"id":123,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":"VARCHAR","type_generic":1,"verbose_name":null,"warning_markdown":null},"datasourceWarning":false,"expressionType":"SIMPLE","hasCustomLabel":true,"label":"Learner_count","optionName":"metric_455ovz8nu4s_6b2gv5odit3","sqlExpression":null}],"orderby":[[{"aggregate":"MAX","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"courseactivity_date","description":null,"expression":null,"filterable":true,"groupby":true,"id":122,"is_certified":false,"is_dttm":true,"python_date_format":null,"type":"DATE","type_generic":2,"verbose_name":null,"warning_markdown":null},"datasourceWarning":false,"expressionType":"SIMPLE","hasCustomLabel":false,"label":"MAX(courseactivity_date)","optionName":"metric_okhl5d9h4c_ah7l934rd7f","sqlExpression":null},false]],"annotation_layers":[],"row_limit":10000,"series_columns":[],"series_limit":0,"series_limit_metric":{"aggregate":"MAX","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"courseactivity_date","description":null,"expression":null,"filterable":true,"groupby":true,"id":122,"is_certified":false,"is_dttm":true,"python_date_format":null,"type":"DATE","type_generic":2,"verbose_name":null,"warning_markdown":null},"datasourceWarning":false,"expressionType":"SIMPLE","hasCustomLabel":false,"label":"MAX(courseactivity_date)","optionName":"metric_okhl5d9h4c_ah7l934rd7f","sqlExpression":null},"order_desc":true,"url_params":{},"custom_params":{},"custom_form_data":{},"time_offsets":[],"post_processing":[{"operation":"pivot","options":{"index":["courseactivity_date"],"columns":[],"aggregates":{"Watched_a_video":{"operator":"mean"},"Tried_a_problem":{"operator":"mean"},"Participated_In_Discussion":{"operator":"mean"},"Learner_count":{"operator":"mean"__JINJA2_CLOSE__,"drop_missing_columns":true__JINJA2_CLOSE__,{"operation":"flatten"}]}],"form_data":{"adhoc_filters":[{"clause":"WHERE","comparator":"No
  filter","datasourceWarning":false,"expressionType":"SIMPLE","filterOptionName":"filter_vmnxg0351v_lspf9hzyi4i","isExtra":false,"isNew":false,"operator":"TEMPORAL_RANGE","sqlExpression":null,"subject":"courseactivity_date"}],"annotation_layers":[],"area":false,"color_scheme":"supersetColors","comparison_type":"values","dashboards":[7],"datasource":"10__table","extra_form_data":{},"forecastInterval":0.8,"forecastPeriods":10,"groupby":[],"legendOrientation":"top","legendType":"scroll","logAxis":false,"markerEnabled":true,"markerSize":6,"metrics":[{"aggregate":null,"column":null,"datasourceWarning":false,"expressionType":"SQL","hasCustomLabel":true,"label":"Watched_a_video","optionName":"metric_nn1wefuu2db_mpukfx7sm3p","sqlExpression":"SUM(CASE
  WHEN num_video_played> 0 THEN 1 ELSE 0 END)"},{"aggregate":null,"column":null,"datasourceWarning":false,"expressionType":"SQL","hasCustomLabel":true,"label":"Tried_a_problem","optionName":"metric_5dkp4rc3smx_j5uh6anrsrg","sqlExpression":"SUM(case
  when num_problem_submitted> 0 then 1 else 0 end)"},{"aggregate":null,"column":null,"datasourceWarning":false,"expressionType":"SQL","hasCustomLabel":true,"label":"Participated_In_Discussion","optionName":"metric_nyeto5r6o1_a3bqgmcrvng","sqlExpression":"SUM(case
  when num_discussion_participated> 0 then 1 else 0 end)"},{"aggregate":"COUNT_DISTINCT","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"user_username","description":null,"expression":null,"filterable":true,"groupby":true,"id":123,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":"VARCHAR","type_generic":1,"verbose_name":null,"warning_markdown":null},"datasourceWarning":false,"expressionType":"SIMPLE","hasCustomLabel":true,"label":"Learner_count","optionName":"metric_455ovz8nu4s_6b2gv5odit3","sqlExpression":null}],"only_total":true,"opacity":0.2,"order_desc":true,"rich_tooltip":true,"row_limit":10000,"seriesType":"line","show_empty_columns":false,"show_legend":true,"show_value":false,"slice_id":58,"sort_series_type":"sum","time_grain_sqla":"P1W","timeseries_limit_metric":{"aggregate":"MAX","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"courseactivity_date","description":null,"expression":null,"filterable":true,"groupby":true,"id":122,"is_certified":false,"is_dttm":true,"python_date_format":null,"type":"DATE","type_generic":2,"verbose_name":null,"warning_markdown":null},"datasourceWarning":false,"expressionType":"SIMPLE","hasCustomLabel":false,"label":"MAX(courseactivity_date)","optionName":"metric_okhl5d9h4c_ah7l934rd7f","sqlExpression":null},"tooltipTimeFormat":"smart_date","truncateXAxis":true,"truncate_metric":false,"viz_type":"echarts_timeseries_line","x_axis":{"expressionType":"SQL","label":"courseactivity_date","sqlExpression":"courseactivity_date"},"x_axis_sort_asc":true,"x_axis_sort_series":"name","x_axis_sort_series_ascending":true,"x_axis_time_format":"smart_date","x_axis_title_margin":15,"y_axis_bounds":[null,null],"y_axis_format":"SMART_NUMBER","y_axis_title_margin":15,"y_axis_title_position":"Left","zoomable":true,"force":false,"result_format":"json","result_type":"full"},"result_format":"json","result_type":"full"}'
cache_timeout:
uuid: 3267dca3-cc86-47f9-ae47-f338d1af4071
version: 1.0.0
dataset_uuid: e7330108-bdfa-4ff0-8ca3-084d7e8cbda8
