slice_name: Organization Administration Chatbot Use
description: Counts of chatbot & learner sessions within a particular course block
  rolled up by Month
certified_by: null
certification_details: null
viz_type: echarts_timeseries_bar
params:
  datasource: 152__table
  viz_type: echarts_timeseries_bar
  slice_id: 134
  x_axis:
    expressionType: SQL
    label: activity_date
    sqlExpression: date_format(activity_date, '%c-%Y')
  time_grain_sqla: P1M
  metrics:
  - aggregate: SUM
    column:
      advanced_data_type: null
      certification_details: null
      certified_by: null
      column_name: chatbot_used_count
      description: null
      expression: ''
      filterable: true
      groupby: true
      id: 2240
      is_certified: false
      is_dttm: false
      python_date_format: null
      type: INTEGER
      type_generic: 0
      verbose_name: null
      warning_markdown: null
    datasourceWarning: false
    expressionType: SIMPLE
    hasCustomLabel: false
    label: SUM(chatbot_used_count)
    optionName: metric_5fbz2uevo0h_d7pymd866yf
    sqlExpression: null
  groupby: []
  adhoc_filters:
  - clause: WHERE
    comparator: No filter
    datasourceWarning: false
    expressionType: SIMPLE
    filterOptionName: filter_lp2f9t9pf2_hpvt8b6h2fo
    isExtra: false
    isNew: false
    operator: TEMPORAL_RANGE
    operatorId: TEMPORAL_RANGE
    sqlExpression: null
    subject: activity_date
  - clause: WHERE
    comparator: null
    datasourceWarning: false
    expressionType: SQL
    filterOptionName: filter_lp2f9t9pf2_hpvt8b6h2fo
    isExtra: false
    isNew: false
    operator: TEMPORAL_RANGE
    operatorId: TEMPORAL_RANGE
    sqlExpression: activity_date IS NOT NULL
    subject: activity_date
  - clause: WHERE
    comparator: '01/01/2025 : '
    datasourceWarning: false
    expressionType: SIMPLE
    filterOptionName: filter_lp2f9t9pf2_hpvt8b6h2fo
    isExtra: false
    isNew: false
    operator: TEMPORAL_RANGE
    operatorId: TEMPORAL_RANGE
    sqlExpression: null
    subject: activity_date
  row_limit: 10000
  truncate_metric: true
  show_empty_columns: true
  comparison_type: values
  annotation_layers: []
  forecastPeriods: 10
  forecastInterval: 0.8
  orientation: vertical
  x_axis_title_margin: 15
  y_axis_title_margin: 30
  y_axis_title_position: Left
  sort_series_type: sum
  sort_series_ascending: true
  color_scheme: supersetColors
  show_legend: true
  legendType: scroll
  legendOrientation: top
  x_axis_time_format: smart_date
  xAxisLabelInterval: auto
  y_axis_format: SMART_NUMBER
  y_axis_bounds:
  - null
  - null
  truncateXAxis: true
  rich_tooltip: true
  showTooltipTotal: true
  tooltipTimeFormat: smart_date
  extra_form_data: {}
  dashboards:
  - 58
query_context: '{"datasource":{"id":152,"type":"table"},"force":false,"queries":[{"filters":[{"col":"activity_date","op":"TEMPORAL_RANGE","val":"No
  filter"},{"col":"activity_date","op":"TEMPORAL_RANGE","val":"01/01/2025 : "}],"extras":{"time_grain_sqla":"P1M","having":"","where":"(activity_date
  IS NOT NULL)"},"applied_time_extras":{},"columns":[{"timeGrain":"P1M","columnType":"BASE_AXIS","expressionType":"SQL","label":"activity_date","sqlExpression":"date_format(activity_date,
  ''%c-%Y'')"}],"metrics":[{"aggregate":"SUM","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"chatbot_used_count","description":null,"expression":"","filterable":true,"groupby":true,"id":2240,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":"INTEGER","type_generic":0,"verbose_name":null,"warning_markdown":null},"datasourceWarning":false,"expressionType":"SIMPLE","hasCustomLabel":false,"label":"SUM(chatbot_used_count)","optionName":"metric_5fbz2uevo0h_d7pymd866yf","sqlExpression":null}],"orderby":[[{"aggregate":"SUM","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"chatbot_used_count","description":null,"expression":"","filterable":true,"groupby":true,"id":2240,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":"INTEGER","type_generic":0,"verbose_name":null,"warning_markdown":null},"datasourceWarning":false,"expressionType":"SIMPLE","hasCustomLabel":false,"label":"SUM(chatbot_used_count)","optionName":"metric_5fbz2uevo0h_d7pymd866yf","sqlExpression":null},false]],"annotation_layers":[],"row_limit":10000,"series_columns":[],"series_limit":0,"group_others_when_limit_reached":false,"order_desc":true,"url_params":{},"custom_params":{},"custom_form_data":{},"time_offsets":[],"post_processing":[{"operation":"pivot","options":{"index":["activity_date"],"columns":[],"aggregates":{"SUM(chatbot_used_count)":{"operator":"mean"}},"drop_missing_columns":false}},{"operation":"flatten"}]}],"form_data":{"datasource":"152__table","viz_type":"echarts_timeseries_bar","slice_id":134,"x_axis":{"expressionType":"SQL","label":"activity_date","sqlExpression":"date_format(activity_date,
  ''%c-%Y'')"},"time_grain_sqla":"P1M","metrics":[{"aggregate":"SUM","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"chatbot_used_count","description":null,"expression":"","filterable":true,"groupby":true,"id":2240,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":"INTEGER","type_generic":0,"verbose_name":null,"warning_markdown":null},"datasourceWarning":false,"expressionType":"SIMPLE","hasCustomLabel":false,"label":"SUM(chatbot_used_count)","optionName":"metric_5fbz2uevo0h_d7pymd866yf","sqlExpression":null}],"groupby":[],"adhoc_filters":[{"clause":"WHERE","comparator":"No
  filter","datasourceWarning":false,"expressionType":"SIMPLE","filterOptionName":"filter_lp2f9t9pf2_hpvt8b6h2fo","isExtra":false,"isNew":false,"operator":"TEMPORAL_RANGE","operatorId":"TEMPORAL_RANGE","sqlExpression":null,"subject":"activity_date"},{"clause":"WHERE","comparator":null,"datasourceWarning":false,"expressionType":"SQL","filterOptionName":"filter_lp2f9t9pf2_hpvt8b6h2fo","isExtra":false,"isNew":false,"operator":"TEMPORAL_RANGE","operatorId":"TEMPORAL_RANGE","sqlExpression":"activity_date
  IS NOT NULL","subject":"activity_date"},{"clause":"WHERE","comparator":"01/01/2025
  : ","datasourceWarning":false,"expressionType":"SIMPLE","filterOptionName":"filter_lp2f9t9pf2_hpvt8b6h2fo","isExtra":false,"isNew":false,"operator":"TEMPORAL_RANGE","operatorId":"TEMPORAL_RANGE","sqlExpression":null,"subject":"activity_date"}],"row_limit":10000,"truncate_metric":true,"show_empty_columns":true,"comparison_type":"values","annotation_layers":[],"forecastPeriods":10,"forecastInterval":0.8,"orientation":"vertical","x_axis_title_margin":15,"y_axis_title_margin":30,"y_axis_title_position":"Left","sort_series_type":"sum","sort_series_ascending":true,"color_scheme":"supersetColors","show_legend":true,"legendType":"scroll","legendOrientation":"top","x_axis_time_format":"smart_date","xAxisLabelInterval":"auto","y_axis_format":"SMART_NUMBER","y_axis_bounds":[null,null],"truncateXAxis":true,"rich_tooltip":true,"showTooltipTotal":true,"tooltipTimeFormat":"smart_date","extra_form_data":{},"dashboards":[58],"force":false,"result_format":"json","result_type":"full"},"result_format":"json","result_type":"full"}'
cache_timeout: null
uuid: a8eba8e2-dff3-4975-8b54-9f6f4dd39478
version: 1.0.0
dataset_uuid: 4a71d2a9-c1b2-44e7-8c8d-a4a336779ab8
