---
slice_name: Organization Administration Unique Active Learners
description: 'An active learner is considered anyone who participated in a discussion,
  watched a video, completed a problem, used a chat bot, got a certificate, or participated
  in a navigation activity in a particular month.

  '
certified_by:
certification_details:
viz_type: echarts_timeseries_bar
params:
  datasource: 152__table
  viz_type: echarts_timeseries_bar
  slice_id: 137
  x_axis:
    expressionType: SQL
    label: activity_date
    sqlExpression: date_format(activity_date, '%c-%Y')
  time_grain_sqla: P1M
  metrics:
  - aggregate: COUNT_DISTINCT
    column:
      advanced_data_type:
      certification_details:
      certified_by:
      column_name: user_email
      description:
      expression: ''
      filterable: true
      groupby: true
      id: 2234
      is_certified: false
      is_dttm: false
      python_date_format:
      type: column
      type_generic: 1
      uuid: 25a4e321-d824-4b23-8919-c0b20994824d
      verbose_name:
      warning_markdown:
    datasourceWarning: false
    expressionType: SIMPLE
    hasCustomLabel: false
    label: COUNT_DISTINCT(user_email)
    optionName: metric_avc0go3oz8r_qw1xqr59kbm
    sqlExpression:
  groupby: []
  adhoc_filters:
  - clause: WHERE
    comparator: No filter
    datasourceWarning: false
    expressionType: SIMPLE
    filterOptionName: filter_q8zowbm2rp8_kn7ge9hq7m
    isExtra: false
    isNew: false
    operator: TEMPORAL_RANGE
    sqlExpression:
    subject: activity_date
  - clause: WHERE
    comparator:
    - 1
    datasourceWarning: false
    expressionType: SIMPLE
    filterOptionName: filter_ceg0vlp19u6_xc4grctwycb
    isExtra: false
    isNew: false
    operator: IN
    operatorId: IN
    sqlExpression:
    subject: active_count
  row_limit: 10000
  truncate_metric: true
  show_empty_columns: true
  comparison_type: values
  annotation_layers: []
  forecastPeriods: 10
  forecastInterval: 0.8
  orientation: vertical
  x_axis_title_margin: 15
  y_axis_title_margin: 30
  y_axis_title_position: Left
  sort_series_type: sum
  color_scheme: supersetColors
  time_shift_color: true
  only_total: true
  show_legend: true
  legendType: scroll
  legendOrientation: top
  x_axis_time_format: smart_date
  xAxisLabelInterval: auto
  y_axis_format: SMART_NUMBER
  y_axis_bounds:
  - 
  - 
  truncateXAxis: true
  rich_tooltip: true
  showTooltipTotal: true
  tooltipTimeFormat: smart_date
  extra_form_data: {}
  dashboards:
  - 58
query_context: '{"datasource":{"id":152,"type":"table"},"force":false,"queries":[{"filters":[{"col":"activity_date","op":"TEMPORAL_RANGE","val":"No
  filter"},{"col":"active_count","op":"IN","val":[1]}],"extras":{"time_grain_sqla":"P1M","having":"","where":""},"applied_time_extras":{},"columns":[{"timeGrain":"P1M","columnType":"BASE_AXIS","expressionType":"SQL","label":"activity_date","sqlExpression":"date_format(activity_date,
  ''%c-%Y'')"}],"metrics":[{"aggregate":"COUNT_DISTINCT","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"user_email","description":null,"expression":"","filterable":true,"groupby":true,"id":2234,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":"column","type_generic":1,"uuid":"25a4e321-d824-4b23-8919-c0b20994824d","verbose_name":null,"warning_markdown":null},"datasourceWarning":false,"expressionType":"SIMPLE","hasCustomLabel":false,"label":"COUNT_DISTINCT(user_email)","optionName":"metric_avc0go3oz8r_qw1xqr59kbm","sqlExpression":null}],"orderby":[[{"aggregate":"COUNT_DISTINCT","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"user_email","description":null,"expression":"","filterable":true,"groupby":true,"id":2234,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":"column","type_generic":1,"uuid":"25a4e321-d824-4b23-8919-c0b20994824d","verbose_name":null,"warning_markdown":null},"datasourceWarning":false,"expressionType":"SIMPLE","hasCustomLabel":false,"label":"COUNT_DISTINCT(user_email)","optionName":"metric_avc0go3oz8r_qw1xqr59kbm","sqlExpression":null},false]],"annotation_layers":[],"row_limit":10000,"series_columns":[],"series_limit":0,"group_others_when_limit_reached":false,"order_desc":true,"url_params":{},"custom_params":{},"custom_form_data":{},"time_offsets":[],"post_processing":[{"operation":"pivot","options":{"index":["activity_date"],"columns":[],"aggregates":{"COUNT_DISTINCT(user_email)":{"operator":"mean"}},"drop_missing_columns":false}},{"operation":"flatten"}]}],"form_data":{"datasource":"152__table","viz_type":"echarts_timeseries_bar","slice_id":137,"x_axis":{"expressionType":"SQL","label":"activity_date","sqlExpression":"date_format(activity_date,
  ''%c-%Y'')"},"time_grain_sqla":"P1M","metrics":[{"aggregate":"COUNT_DISTINCT","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"user_email","description":null,"expression":"","filterable":true,"groupby":true,"id":2234,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":"column","type_generic":1,"uuid":"25a4e321-d824-4b23-8919-c0b20994824d","verbose_name":null,"warning_markdown":null},"datasourceWarning":false,"expressionType":"SIMPLE","hasCustomLabel":false,"label":"COUNT_DISTINCT(user_email)","optionName":"metric_avc0go3oz8r_qw1xqr59kbm","sqlExpression":null}],"groupby":[],"adhoc_filters":[{"clause":"WHERE","comparator":"No
  filter","datasourceWarning":false,"expressionType":"SIMPLE","filterOptionName":"filter_q8zowbm2rp8_kn7ge9hq7m","isExtra":false,"isNew":false,"operator":"TEMPORAL_RANGE","sqlExpression":null,"subject":"activity_date"},{"clause":"WHERE","comparator":[1],"datasourceWarning":false,"expressionType":"SIMPLE","filterOptionName":"filter_ceg0vlp19u6_xc4grctwycb","isExtra":false,"isNew":false,"operator":"IN","operatorId":"IN","sqlExpression":null,"subject":"active_count"}],"row_limit":10000,"truncate_metric":true,"show_empty_columns":true,"comparison_type":"values","annotation_layers":[],"forecastPeriods":10,"forecastInterval":0.8,"orientation":"vertical","x_axis_title_margin":15,"y_axis_title_margin":30,"y_axis_title_position":"Left","sort_series_type":"sum","color_scheme":"supersetColors","time_shift_color":true,"only_total":true,"show_legend":true,"legendType":"scroll","legendOrientation":"top","x_axis_time_format":"smart_date","xAxisLabelInterval":"auto","y_axis_format":"SMART_NUMBER","y_axis_bounds":[null,null],"truncateXAxis":true,"rich_tooltip":true,"showTooltipTotal":true,"tooltipTimeFormat":"smart_date","extra_form_data":{},"dashboards":[58],"force":false,"result_format":"json","result_type":"full"},"result_format":"json","result_type":"full"}'
cache_timeout:
uuid: 33b8ff2e-ddd7-4fa6-a438-d422da92fb27
version: 1.0.0
dataset_uuid: 4a71d2a9-c1b2-44e7-8c8d-a4a336779ab8
