slice_name: Page Engagement By Section
description: null
certified_by: null
certification_details: null
viz_type: table
params:
  datasource: 82__table
  viz_type: table
  slice_id: 95
  query_mode: aggregate
  groupby:
  - section_title
  temporal_columns_lookup: {}
  metrics:
  - aggregate: SUM
    column:
      advanced_data_type: null
      certification_details: null
      certified_by: null
      column_name: num_of_views
      description: null
      expression: null
      filterable: true
      groupby: true
      id: 1105
      is_certified: false
      is_dttm: false
      python_date_format: null
      type: BIGINT
      type_generic: 0
      verbose_name: null
      warning_markdown: null
    datasourceWarning: false
    expressionType: SIMPLE
    hasCustomLabel: true
    label: num_of_views
    optionName: metric_rtw6byftwfe_zc65y029dwe
    sqlExpression: null
  all_columns: []
  percent_metrics: []
  adhoc_filters: []
  timeseries_limit_metric:
    aggregate: MIN
    column:
      advanced_data_type: null
      certification_details: null
      certified_by: null
      column_name: section_block_index
      description: null
      expression: null
      filterable: true
      groupby: true
      id: 1115
      is_certified: false
      is_dttm: false
      python_date_format: null
      type: BIGINT
      type_generic: 0
      verbose_name: null
      warning_markdown: null
    datasourceWarning: false
    expressionType: SIMPLE
    hasCustomLabel: false
    label: MIN(section_block_index)
    optionName: metric_p0p1a6i9oxd_sgjigxr56j
    sqlExpression: null
  order_by_cols: []
  row_limit: 1000
  server_page_length: 10
  order_desc: false
  table_timestamp_format: smart_date
  allow_render_html: true
  show_cell_bars: true
  color_pn: true
  comparison_color_scheme: Green
  comparison_type: values
  extra_form_data: {}
  dashboards:
  - 45
query_context: '{"datasource":{"id":82,"type":"table"},"force":false,"queries":[{"filters":[],"extras":{"having":"","where":""},"applied_time_extras":{},"columns":["section_title"],"metrics":[{"aggregate":"SUM","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"num_of_views","description":null,"expression":null,"filterable":true,"groupby":true,"id":1105,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":"BIGINT","type_generic":0,"verbose_name":null,"warning_markdown":null},"datasourceWarning":false,"expressionType":"SIMPLE","hasCustomLabel":true,"label":"num_of_views","optionName":"metric_rtw6byftwfe_zc65y029dwe","sqlExpression":null}],"orderby":[[{"aggregate":"MIN","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"section_block_index","description":null,"expression":null,"filterable":true,"groupby":true,"id":1115,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":"BIGINT","type_generic":0,"verbose_name":null,"warning_markdown":null},"datasourceWarning":false,"expressionType":"SIMPLE","hasCustomLabel":false,"label":"MIN(section_block_index)","optionName":"metric_p0p1a6i9oxd_sgjigxr56j","sqlExpression":null},true]],"annotation_layers":[],"row_limit":1000,"series_limit":0,"series_limit_metric":{"aggregate":"MIN","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"section_block_index","description":null,"expression":null,"filterable":true,"groupby":true,"id":1115,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":"BIGINT","type_generic":0,"verbose_name":null,"warning_markdown":null},"datasourceWarning":false,"expressionType":"SIMPLE","hasCustomLabel":false,"label":"MIN(section_block_index)","optionName":"metric_p0p1a6i9oxd_sgjigxr56j","sqlExpression":null},"order_desc":false,"url_params":{},"custom_params":{},"custom_form_data":{},"post_processing":[],"time_offsets":[]}],"form_data":{"datasource":"82__table","viz_type":"table","slice_id":95,"query_mode":"aggregate","groupby":["section_title"],"temporal_columns_lookup":{},"metrics":[{"aggregate":"SUM","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"num_of_views","description":null,"expression":null,"filterable":true,"groupby":true,"id":1105,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":"BIGINT","type_generic":0,"verbose_name":null,"warning_markdown":null},"datasourceWarning":false,"expressionType":"SIMPLE","hasCustomLabel":true,"label":"num_of_views","optionName":"metric_rtw6byftwfe_zc65y029dwe","sqlExpression":null}],"all_columns":[],"percent_metrics":[],"adhoc_filters":[],"timeseries_limit_metric":{"aggregate":"MIN","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"section_block_index","description":null,"expression":null,"filterable":true,"groupby":true,"id":1115,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":"BIGINT","type_generic":0,"verbose_name":null,"warning_markdown":null},"datasourceWarning":false,"expressionType":"SIMPLE","hasCustomLabel":false,"label":"MIN(section_block_index)","optionName":"metric_p0p1a6i9oxd_sgjigxr56j","sqlExpression":null},"order_by_cols":[],"row_limit":1000,"server_page_length":10,"order_desc":false,"table_timestamp_format":"smart_date","allow_render_html":true,"show_cell_bars":true,"color_pn":true,"comparison_color_scheme":"Green","comparison_type":"values","extra_form_data":{},"dashboards":[45],"force":false,"result_format":"json","result_type":"full"},"result_format":"json","result_type":"full"}'
cache_timeout: null
uuid: b4d14d82-feb2-49bf-847f-2cb8b2c11d20
version: 1.0.0
dataset_uuid: 68c544d7-726d-495a-bf87-81255b2e8604
