slice_name: Page Engagement By Courserun
description: null
certified_by: null
certification_details: null
viz_type: table
params:
  datasource: 82__table
  viz_type: table
  slice_id: 97
  query_mode: aggregate
  groupby:
  - courserun_readable_id
  temporal_columns_lookup: {}
  metrics:
  - aggregate: SUM
    column:
      advanced_data_type: null
      certification_details: null
      certified_by: null
      column_name: num_of_views
      description: null
      expression: null
      filterable: true
      groupby: true
      id: 1105
      is_certified: false
      is_dttm: false
      python_date_format: null
      type: BIGINT
      type_generic: 0
      verbose_name: null
      warning_markdown: null
    datasourceWarning: false
    expressionType: SIMPLE
    hasCustomLabel: true
    label: num_of_views
    optionName: metric_cr6w2trp67f_qvyzngurisn
    sqlExpression: null
  all_columns: []
  percent_metrics: []
  adhoc_filters: []
  order_by_cols: []
  row_limit: 1000
  order_desc: true
  table_timestamp_format: smart_date
  allow_render_html: true
  show_cell_bars: true
  color_pn: true
  comparison_color_scheme: Green
  comparison_type: values
  extra_form_data: {}
  dashboards:
  - 45
query_context: '{"datasource":{"id":82,"type":"table"},"force":false,"queries":[{"filters":[],"extras":{"having":"","where":""},"applied_time_extras":{},"columns":["courserun_readable_id"],"metrics":[{"aggregate":"SUM","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"num_of_views","description":null,"expression":null,"filterable":true,"groupby":true,"id":1105,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":"BIGINT","type_generic":0,"verbose_name":null,"warning_markdown":null},"datasourceWarning":false,"expressionType":"SIMPLE","hasCustomLabel":true,"label":"num_of_views","optionName":"metric_cr6w2trp67f_qvyzngurisn","sqlExpression":null}],"orderby":[[{"aggregate":"SUM","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"num_of_views","description":null,"expression":null,"filterable":true,"groupby":true,"id":1105,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":"BIGINT","type_generic":0,"verbose_name":null,"warning_markdown":null},"datasourceWarning":false,"expressionType":"SIMPLE","hasCustomLabel":true,"label":"num_of_views","optionName":"metric_cr6w2trp67f_qvyzngurisn","sqlExpression":null},false]],"annotation_layers":[],"row_limit":1000,"series_limit":0,"order_desc":true,"url_params":{},"custom_params":{},"custom_form_data":{},"post_processing":[],"time_offsets":[]}],"form_data":{"datasource":"82__table","viz_type":"table","slice_id":97,"query_mode":"aggregate","groupby":["courserun_readable_id"],"temporal_columns_lookup":{},"metrics":[{"aggregate":"SUM","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"num_of_views","description":null,"expression":null,"filterable":true,"groupby":true,"id":1105,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":"BIGINT","type_generic":0,"verbose_name":null,"warning_markdown":null},"datasourceWarning":false,"expressionType":"SIMPLE","hasCustomLabel":true,"label":"num_of_views","optionName":"metric_cr6w2trp67f_qvyzngurisn","sqlExpression":null}],"all_columns":[],"percent_metrics":[],"adhoc_filters":[],"order_by_cols":[],"row_limit":1000,"order_desc":true,"table_timestamp_format":"smart_date","allow_render_html":true,"show_cell_bars":true,"color_pn":true,"comparison_color_scheme":"Green","comparison_type":"values","extra_form_data":{},"dashboards":[45],"force":false,"result_format":"json","result_type":"full"},"result_format":"json","result_type":"full"}'
cache_timeout: null
uuid: 008cffdc-9283-4daf-8507-746491486bd4
version: 1.0.0
dataset_uuid: c3182341-5246-40c2-8f04-885369c38093
