slice_name: Page Engagement By Subsection
description: null
certified_by: null
certification_details: null
viz_type: table
params:
  adhoc_filters: []
  all_columns: []
  allow_render_html: true
  color_pn: true
  comparison_color_scheme: Green
  comparison_type: values
  dashboards:
  - 45
  datasource: 16__table
  extra_form_data: {}
  groupby:
  - subsection_title
  metrics:
  - aggregate: SUM
    column:
      advanced_data_type: null
      certification_details: null
      certified_by: null
      column_name: num_of_views
      description: null
      expression: null
      filterable: true
      groupby: true
      id: 1105
      is_certified: false
      is_dttm: false
      python_date_format: null
      type: BIGINT
      type_generic: 0
      verbose_name: null
      warning_markdown: null
    datasourceWarning: false
    expressionType: SIMPLE
    hasCustomLabel: true
    label: num_of_views
    optionName: metric_i369jawpcup_vuuhlblhaz
    sqlExpression: null
  order_by_cols: []
  order_desc: false
  percent_metrics: []
  query_mode: aggregate
  row_limit: 1000
  server_page_length: 10
  show_cell_bars: true
  slice_id: 96
  table_timestamp_format: smart_date
  temporal_columns_lookup: {}
  timeseries_limit_metric:
    aggregate: MIN
    column:
      advanced_data_type: null
      certification_details: null
      certified_by: null
      column_name: subsection_block_index
      description: null
      expression: null
      filterable: true
      groupby: true
      id: 1114
      is_certified: false
      is_dttm: false
      python_date_format: null
      type: BIGINT
      type_generic: 0
      verbose_name: null
      warning_markdown: null
    datasourceWarning: false
    expressionType: SIMPLE
    hasCustomLabel: false
    label: MIN(subsection_block_index)
    optionName: metric_hw3xjytwl_ek726rk1ph
    sqlExpression: null
  viz_type: table
  annotation_layers: []
query_context: '{"datasource": {"id": 16, "type": "table"}, "force": false, "queries":
  [{"filters": [], "extras": {"having": "", "where": ""}, "applied_time_extras": {},
  "columns": ["subsection_title"], "metrics": [{"aggregate": "SUM", "column": {"advanced_data_type":
  null, "certification_details": null, "certified_by": null, "column_name": "num_of_views",
  "description": null, "expression": null, "filterable": true, "groupby": true, "id":
  1105, "is_certified": false, "is_dttm": false, "python_date_format": null, "type":
  "BIGINT", "type_generic": 0, "verbose_name": null, "warning_markdown": null}, "datasourceWarning":
  false, "expressionType": "SIMPLE", "hasCustomLabel": true, "label": "num_of_views",
  "optionName": "metric_i369jawpcup_vuuhlblhaz", "sqlExpression": null}], "orderby":
  [[{"aggregate": "MIN", "column": {"advanced_data_type": null, "certification_details":
  null, "certified_by": null, "column_name": "subsection_block_index", "description":
  null, "expression": null, "filterable": true, "groupby": true, "id": 1114, "is_certified":
  false, "is_dttm": false, "python_date_format": null, "type": "BIGINT", "type_generic":
  0, "verbose_name": null, "warning_markdown": null}, "datasourceWarning": false,
  "expressionType": "SIMPLE", "hasCustomLabel": false, "label": "MIN(subsection_block_index)",
  "optionName": "metric_hw3xjytwl_ek726rk1ph", "sqlExpression": null}, true]], "annotation_layers":
  [], "row_limit": 1000, "series_limit": 0, "series_limit_metric": {"aggregate": "MIN",
  "column": {"advanced_data_type": null, "certification_details": null, "certified_by":
  null, "column_name": "subsection_block_index", "description": null, "expression":
  null, "filterable": true, "groupby": true, "id": 1114, "is_certified": false, "is_dttm":
  false, "python_date_format": null, "type": "BIGINT", "type_generic": 0, "verbose_name":
  null, "warning_markdown": null}, "datasourceWarning": false, "expressionType": "SIMPLE",
  "hasCustomLabel": false, "label": "MIN(subsection_block_index)", "optionName": "metric_hw3xjytwl_ek726rk1ph",
  "sqlExpression": null}, "order_desc": false, "url_params": {}, "custom_params":
  {}, "custom_form_data": {}, "post_processing": [], "time_offsets": []}], "form_data":
  {"datasource": "16__table", "viz_type": "table", "slice_id": 96, "query_mode": "aggregate",
  "groupby": ["subsection_title"], "temporal_columns_lookup": {}, "metrics": [{"aggregate":
  "SUM", "column": {"advanced_data_type": null, "certification_details": null, "certified_by":
  null, "column_name": "num_of_views", "description": null, "expression": null, "filterable":
  true, "groupby": true, "id": 1105, "is_certified": false, "is_dttm": false, "python_date_format":
  null, "type": "BIGINT", "type_generic": 0, "verbose_name": null, "warning_markdown":
  null}, "datasourceWarning": false, "expressionType": "SIMPLE", "hasCustomLabel":
  true, "label": "num_of_views", "optionName": "metric_i369jawpcup_vuuhlblhaz", "sqlExpression":
  null}], "all_columns": [], "percent_metrics": [], "adhoc_filters": [], "timeseries_limit_metric":
  {"aggregate": "MIN", "column": {"advanced_data_type": null, "certification_details":
  null, "certified_by": null, "column_name": "subsection_block_index", "description":
  null, "expression": null, "filterable": true, "groupby": true, "id": 1114, "is_certified":
  false, "is_dttm": false, "python_date_format": null, "type": "BIGINT", "type_generic":
  0, "verbose_name": null, "warning_markdown": null}, "datasourceWarning": false,
  "expressionType": "SIMPLE", "hasCustomLabel": false, "label": "MIN(subsection_block_index)",
  "optionName": "metric_hw3xjytwl_ek726rk1ph", "sqlExpression": null}, "order_by_cols":
  [], "row_limit": 1000, "server_page_length": 10, "order_desc": false, "table_timestamp_format":
  "smart_date", "allow_render_html": true, "show_cell_bars": true, "color_pn": true,
  "comparison_color_scheme": "Green", "comparison_type": "values", "extra_form_data":
  {}, "dashboards": [45], "force": false, "result_format": "json", "result_type":
  "full"}, "result_format": "json", "result_type": "full"}'
cache_timeout: null
uuid: f41fcf95-edc7-4dcd-bbe8-54406e775b37
version: 1.0.0
dataset_uuid: c3182341-5246-40c2-8f04-885369c38093
