slice_name: Percentage of Video Played
description: null
certified_by: null
certification_details: null
viz_type: table
params:
  adhoc_filters:
  - clause: WHERE
    comparator: No filter
    datasourceWarning: false
    expressionType: SIMPLE
    filterOptionName: filter_i78t0qa2vdc_uohfyrbt5d
    isExtra: false
    isNew: false
    operator: TEMPORAL_RANGE
    sqlExpression: null
    subject: activity_date
  - clause: WHERE
    comparator:
    - video
    datasourceWarning: false
    expressionType: SIMPLE
    filterOptionName: filter_ow7wmcww8p_aya1tggllfg
    isExtra: false
    isNew: false
    operator: IN
    operatorId: IN
    sqlExpression: null
    subject: block_category
  all_columns: []
  allow_render_html: true
  color_pn: true
  column_config:
    Avg_%_Video_Played:
      d3NumberFormat: ',.1%'
  comparison_color_scheme: Green
  comparison_type: values
  conditional_formatting: []
  dashboards:
  - 59
  datasource: 18__table
  extra_form_data: {}
  groupby:
  - section_title
  - subsection_title
  - block_title
  metrics:
  - aggregate: null
    column: null
    datasourceWarning: false
    expressionType: SQL
    hasCustomLabel: true
    label: Avg_%_Video_Played
    optionName: metric_z3je25mgv1r_j1gf6wdybya
    sqlExpression: AVG((case when estimated_time_played>= video_duration then video_duration
      else estimated_time_played end)/(case when video_duration = 0 then null else
      video_duration end))
  order_by_cols: []
  order_desc: true
  percent_metrics: []
  query_mode: aggregate
  row_limit: 1000
  server_page_length: 10
  show_cell_bars: true
  table_timestamp_format: smart_date
  temporal_columns_lookup:
    activity_date: true
  time_grain_sqla: P1D
  viz_type: table
  annotation_layers: []
query_context: '{"datasource": {"id": 18, "type": "table"}, "force": false, "queries":
  [{"filters": [{"col": "activity_date", "op": "TEMPORAL_RANGE", "val": "No filter"},
  {"col": "block_category", "op": "IN", "val": ["video"]}], "extras": {"time_grain_sqla":
  "P1D", "having": "", "where": ""}, "applied_time_extras": {}, "columns": ["section_title",
  "subsection_title", "block_title"], "metrics": [{"expressionType": "SQL", "sqlExpression":
  "AVG((case when estimated_time_played>= video_duration then video_duration else
  estimated_time_played end)/(case when video_duration = 0 then null else video_duration
  end))", "column": null, "aggregate": null, "datasourceWarning": false, "hasCustomLabel":
  true, "label": "Avg_%_Video_Played", "optionName": "metric_z3je25mgv1r_j1gf6wdybya"}],
  "orderby": [[{"expressionType": "SQL", "sqlExpression": "AVG((case when estimated_time_played>=
  video_duration then video_duration else estimated_time_played end)/(case when video_duration
  = 0 then null else video_duration end))", "column": null, "aggregate": null, "datasourceWarning":
  false, "hasCustomLabel": true, "label": "Avg_%_Video_Played", "optionName": "metric_z3je25mgv1r_j1gf6wdybya"},
  false]], "annotation_layers": [], "row_limit": 1000, "series_limit": 0, "order_desc":
  true, "url_params": {}, "custom_params": {}, "custom_form_data": {}, "post_processing":
  [], "time_offsets": []}], "form_data": {"datasource": "18__table", "viz_type": "table",
  "query_mode": "aggregate", "groupby": ["section_title", "subsection_title", "block_title"],
  "time_grain_sqla": "P1D", "temporal_columns_lookup": {"activity_date": true}, "metrics":
  [{"expressionType": "SQL", "sqlExpression": "AVG((case when estimated_time_played>=
  video_duration then video_duration else estimated_time_played end)/(case when video_duration
  = 0 then null else video_duration end))", "column": null, "aggregate": null, "datasourceWarning":
  false, "hasCustomLabel": true, "label": "Avg_%_Video_Played", "optionName": "metric_z3je25mgv1r_j1gf6wdybya"}],
  "all_columns": [], "percent_metrics": [], "adhoc_filters": [{"expressionType": "SIMPLE",
  "subject": "activity_date", "operator": "TEMPORAL_RANGE", "comparator": "No filter",
  "clause": "WHERE", "sqlExpression": null, "isExtra": false, "isNew": false, "datasourceWarning":
  false, "filterOptionName": "filter_i78t0qa2vdc_uohfyrbt5d"}, {"expressionType":
  "SIMPLE", "subject": "block_category", "operator": "IN", "operatorId": "IN", "comparator":
  ["video"], "clause": "WHERE", "sqlExpression": null, "isExtra": false, "isNew":
  false, "datasourceWarning": false, "filterOptionName": "filter_ow7wmcww8p_aya1tggllfg"}],
  "order_by_cols": [], "order_desc": true, "row_limit": 1000, "server_page_length":
  10, "table_timestamp_format": "smart_date", "allow_render_html": true, "column_config":
  {"Avg_%_Video_Played": {"d3NumberFormat": ",.1%"}}, "show_cell_bars": true, "color_pn":
  true, "comparison_color_scheme": "Green", "conditional_formatting": [], "comparison_type":
  "values", "extra_form_data": {}, "dashboards": [59], "force": false, "result_format":
  "json", "result_type": "full"}, "result_format": "json", "result_type": "full"}'
cache_timeout: null
uuid: 9bb14cc1-d787-4f47-b6d3-86adb3d4ec47
version: 1.0.0
dataset_uuid: 8c2b6f11-28f8-4353-8e43-6c53ea6b1d91
