slice_name: Percent Content Engagement
description: null
certified_by: null
certification_details: null
viz_type: table
params:
  datasource: 47__table
  viz_type: table
  slice_id: 74
  query_mode: aggregate
  groupby:
  - courserun_readable_id
  temporal_columns_lookup:
    courseactivity_date: true
  metrics:
  - aggregate: null
    column: null
    datasourceWarning: false
    expressionType: SQL
    hasCustomLabel: true
    label: '%_of_Learners_That_Played_A_Video'
    optionName: metric_l5c334byisa_p7rmx2wh92
    sqlExpression: 'CAST(COUNT(DISTINCT (CASE WHEN num_video_played> 0 THEN user_username
      ELSE null END)) AS decimal(10,2))/

      CAST(COUNT(DISTINCT user_username) as decimal(10,2))'
  - aggregate: null
    column: null
    datasourceWarning: false
    expressionType: SQL
    hasCustomLabel: true
    label: '%_of_Learners_That_Submitted_Problem'
    optionName: metric_ylcblnqaund_cnq3layng0u
    sqlExpression: 'CAST(COUNT(DISTINCT (CASE WHEN num_problem_submitted> 0 THEN user_username
      ELSE null END)) AS decimal(10,2))/

      CAST(COUNT(DISTINCT user_username) as decimal(10,2))'
  - aggregate: null
    column: null
    datasourceWarning: false
    expressionType: SQL
    hasCustomLabel: true
    label: '%_of_Learners_Participated_In_Discussion'
    optionName: metric_bv6eq24ga6m_3ew9eu11jld
    sqlExpression: 'CAST(COUNT(DISTINCT (CASE WHEN num_discussion_participated> 0
      THEN user_username ELSE null END)) AS decimal(10,2))/

      CAST(COUNT(DISTINCT user_username) as decimal(10,2))'
  all_columns: []
  percent_metrics: []
  adhoc_filters:
  - clause: WHERE
    comparator: No filter
    expressionType: SIMPLE
    operator: TEMPORAL_RANGE
    subject: courseactivity_date
  order_by_cols: []
  row_limit: 1000
  server_page_length: 10
  order_desc: true
  table_timestamp_format: smart_date
  allow_render_html: true
  column_config:
    '%_of_Learners_Participated_In_Discussion':
      d3SmallNumberFormat: ',.1%'
    '%_of_Learners_That_Played_A_Video':
      d3NumberFormat: ',.1%'
    '%_of_Learners_That_Submitted_Problem':
      d3SmallNumberFormat: ',.1%'
  show_cell_bars: true
  color_pn: true
  comparison_color_scheme: Green
  conditional_formatting: []
  comparison_type: values
  extra_form_data: {}
  dashboards: []
query_context: '{"datasource":{"id":47,"type":"table"},"force":false,"queries":[{"filters":[{"col":"courseactivity_date","op":"TEMPORAL_RANGE","val":"No
  filter"}],"extras":{"having":"","where":""},"applied_time_extras":{},"columns":["courserun_readable_id"],"metrics":[{"aggregate":null,"column":null,"datasourceWarning":false,"expressionType":"SQL","hasCustomLabel":true,"label":"%_of_Learners_That_Played_A_Video","optionName":"metric_l5c334byisa_p7rmx2wh92","sqlExpression":"CAST(COUNT(DISTINCT
  (CASE WHEN num_video_played> 0 THEN user_username ELSE null END)) AS decimal(10,2))/\nCAST(COUNT(DISTINCT
  user_username) as decimal(10,2))"},{"aggregate":null,"column":null,"datasourceWarning":false,"expressionType":"SQL","hasCustomLabel":true,"label":"%_of_Learners_That_Submitted_Problem","optionName":"metric_ylcblnqaund_cnq3layng0u","sqlExpression":"CAST(COUNT(DISTINCT
  (CASE WHEN num_problem_submitted> 0 THEN user_username ELSE null END)) AS decimal(10,2))/\nCAST(COUNT(DISTINCT
  user_username) as decimal(10,2))"},{"aggregate":null,"column":null,"datasourceWarning":false,"expressionType":"SQL","hasCustomLabel":true,"label":"%_of_Learners_Participated_In_Discussion","optionName":"metric_bv6eq24ga6m_3ew9eu11jld","sqlExpression":"CAST(COUNT(DISTINCT
  (CASE WHEN num_discussion_participated> 0 THEN user_username ELSE null END)) AS
  decimal(10,2))/\nCAST(COUNT(DISTINCT user_username) as decimal(10,2))"}],"orderby":[[{"aggregate":null,"column":null,"datasourceWarning":false,"expressionType":"SQL","hasCustomLabel":true,"label":"%_of_Learners_That_Played_A_Video","optionName":"metric_l5c334byisa_p7rmx2wh92","sqlExpression":"CAST(COUNT(DISTINCT
  (CASE WHEN num_video_played> 0 THEN user_username ELSE null END)) AS decimal(10,2))/\nCAST(COUNT(DISTINCT
  user_username) as decimal(10,2))"},false]],"annotation_layers":[],"row_limit":1000,"series_limit":0,"order_desc":true,"url_params":{},"custom_params":{},"custom_form_data":{},"post_processing":[],"time_offsets":[]}],"form_data":{"datasource":"47__table","viz_type":"table","slice_id":74,"query_mode":"aggregate","groupby":["courserun_readable_id"],"temporal_columns_lookup":{"courseactivity_date":true},"metrics":[{"aggregate":null,"column":null,"datasourceWarning":false,"expressionType":"SQL","hasCustomLabel":true,"label":"%_of_Learners_That_Played_A_Video","optionName":"metric_l5c334byisa_p7rmx2wh92","sqlExpression":"CAST(COUNT(DISTINCT
  (CASE WHEN num_video_played> 0 THEN user_username ELSE null END)) AS decimal(10,2))/\nCAST(COUNT(DISTINCT
  user_username) as decimal(10,2))"},{"aggregate":null,"column":null,"datasourceWarning":false,"expressionType":"SQL","hasCustomLabel":true,"label":"%_of_Learners_That_Submitted_Problem","optionName":"metric_ylcblnqaund_cnq3layng0u","sqlExpression":"CAST(COUNT(DISTINCT
  (CASE WHEN num_problem_submitted> 0 THEN user_username ELSE null END)) AS decimal(10,2))/\nCAST(COUNT(DISTINCT
  user_username) as decimal(10,2))"},{"aggregate":null,"column":null,"datasourceWarning":false,"expressionType":"SQL","hasCustomLabel":true,"label":"%_of_Learners_Participated_In_Discussion","optionName":"metric_bv6eq24ga6m_3ew9eu11jld","sqlExpression":"CAST(COUNT(DISTINCT
  (CASE WHEN num_discussion_participated> 0 THEN user_username ELSE null END)) AS
  decimal(10,2))/\nCAST(COUNT(DISTINCT user_username) as decimal(10,2))"}],"all_columns":[],"percent_metrics":[],"adhoc_filters":[{"clause":"WHERE","comparator":"No
  filter","expressionType":"SIMPLE","operator":"TEMPORAL_RANGE","subject":"courseactivity_date"}],"order_by_cols":[],"row_limit":1000,"server_page_length":10,"order_desc":true,"table_timestamp_format":"smart_date","allow_render_html":true,"column_config":{"%_of_Learners_Participated_In_Discussion":{"d3SmallNumberFormat":",.1%"},"%_of_Learners_That_Played_A_Video":{"d3NumberFormat":",.1%"},"%_of_Learners_That_Submitted_Problem":{"d3SmallNumberFormat":",.1%"__JINJA2_CLOSE__,"show_cell_bars":true,"color_pn":true,"comparison_color_scheme":"Green","conditional_formatting":[],"comparison_type":"values","extra_form_data":{},"dashboards":[],"force":false,"result_format":"json","result_type":"full"},"result_format":"json","result_type":"full"}'
cache_timeout: null
uuid: 822d24da-190a-49ea-9253-8a26637a89c8
version: 1.0.0
dataset_uuid: f221af29-5df4-4025-8355-401041f94835
