slice_name: Problem Engagement By Subsection
description: null
certified_by: null
certification_details: null
viz_type: table
params:
  datasource: 67__table
  viz_type: table
  slice_id: 92
  query_mode: aggregate
  groupby:
  - subsection_title
  temporal_columns_lookup: {}
  metrics:
  - aggregate: null
    column: null
    datasourceWarning: false
    expressionType: SQL
    hasCustomLabel: true
    label: Avg_%_problems_attempted
    optionName: metric_2okl1r6oqnv_4z1d7j5lcqg
    sqlExpression: AVG( percetage_problems_attempted)
  all_columns: []
  percent_metrics: []
  adhoc_filters: []
  timeseries_limit_metric:
    aggregate: MIN
    column:
      advanced_data_type: null
      certification_details: null
      certified_by: null
      column_name: subsection_block_index
      description: null
      expression: null
      filterable: true
      groupby: true
      id: 1113
      is_certified: false
      is_dttm: false
      python_date_format: null
      type: BIGINT
      type_generic: 0
      verbose_name: null
      warning_markdown: null
    datasourceWarning: false
    expressionType: SIMPLE
    hasCustomLabel: false
    label: MIN(subsection_block_index)
    optionName: metric_vk6iba314z_v91bdhlgcyq
    sqlExpression: null
  order_by_cols: []
  row_limit: 10000
  server_page_length: 10
  order_desc: false
  table_timestamp_format: smart_date
  allow_render_html: true
  column_config:
    Avg_%_problems_attempted:
      d3NumberFormat: ',.1%'
  show_cell_bars: true
  color_pn: true
  comparison_color_scheme: Green
  conditional_formatting: []
  comparison_type: values
  extra_form_data: {}
  dashboards:
  - 45
query_context: '{"datasource":{"id":67,"type":"table"},"force":false,"queries":[{"filters":[],"extras":{"having":"","where":""},"applied_time_extras":{},"columns":["subsection_title"],"metrics":[{"aggregate":null,"column":null,"datasourceWarning":false,"expressionType":"SQL","hasCustomLabel":true,"label":"Avg_%_problems_attempted","optionName":"metric_2okl1r6oqnv_4z1d7j5lcqg","sqlExpression":"AVG(
  percetage_problems_attempted)"}],"orderby":[[{"aggregate":"MIN","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"subsection_block_index","description":null,"expression":null,"filterable":true,"groupby":true,"id":1113,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":"BIGINT","type_generic":0,"verbose_name":null,"warning_markdown":null},"datasourceWarning":false,"expressionType":"SIMPLE","hasCustomLabel":false,"label":"MIN(subsection_block_index)","optionName":"metric_vk6iba314z_v91bdhlgcyq","sqlExpression":null},true]],"annotation_layers":[],"row_limit":10000,"series_limit":0,"series_limit_metric":{"aggregate":"MIN","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"subsection_block_index","description":null,"expression":null,"filterable":true,"groupby":true,"id":1113,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":"BIGINT","type_generic":0,"verbose_name":null,"warning_markdown":null},"datasourceWarning":false,"expressionType":"SIMPLE","hasCustomLabel":false,"label":"MIN(subsection_block_index)","optionName":"metric_vk6iba314z_v91bdhlgcyq","sqlExpression":null},"order_desc":false,"url_params":{},"custom_params":{},"custom_form_data":{},"post_processing":[],"time_offsets":[]}],"form_data":{"datasource":"67__table","viz_type":"table","slice_id":92,"query_mode":"aggregate","groupby":["subsection_title"],"temporal_columns_lookup":{},"metrics":[{"aggregate":null,"column":null,"datasourceWarning":false,"expressionType":"SQL","hasCustomLabel":true,"label":"Avg_%_problems_attempted","optionName":"metric_2okl1r6oqnv_4z1d7j5lcqg","sqlExpression":"AVG(
  percetage_problems_attempted)"}],"all_columns":[],"percent_metrics":[],"adhoc_filters":[],"timeseries_limit_metric":{"aggregate":"MIN","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"subsection_block_index","description":null,"expression":null,"filterable":true,"groupby":true,"id":1113,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":"BIGINT","type_generic":0,"verbose_name":null,"warning_markdown":null},"datasourceWarning":false,"expressionType":"SIMPLE","hasCustomLabel":false,"label":"MIN(subsection_block_index)","optionName":"metric_vk6iba314z_v91bdhlgcyq","sqlExpression":null},"order_by_cols":[],"row_limit":10000,"server_page_length":10,"order_desc":false,"table_timestamp_format":"smart_date","allow_render_html":true,"column_config":{"Avg_%_problems_attempted":{"d3NumberFormat":",.1%"}},"show_cell_bars":true,"color_pn":true,"comparison_color_scheme":"Green","conditional_formatting":[],"comparison_type":"values","extra_form_data":{},"dashboards":[45],"force":false,"result_format":"json","result_type":"full"},"result_format":"json","result_type":"full"}'
cache_timeout: null
uuid: bec01f31-3a3e-4bba-a280-9160e00e2b87
version: 1.0.0
dataset_uuid: a2198d6f-df2d-492c-b30b-9e3279466bdb
