slice_name: Problem Engagement by Courserun
description: null
certified_by: null
certification_details: null
viz_type: table
params:
  datasource: 66__table
  viz_type: table
  slice_id: 90
  query_mode: aggregate
  groupby:
  - courserun_readable_id
  time_grain_sqla: P1D
  temporal_columns_lookup: {}
  metrics:
  - expressionType: SQL
    sqlExpression: AVG(percetage_problems_attempted)
    column: null
    aggregate: null
    datasourceWarning: false
    hasCustomLabel: true
    label: Avg_%_problems_attempted
    optionName: metric_v0x9x3vkxs_lyd8fkz8ah
  all_columns: []
  percent_metrics: []
  adhoc_filters: []
  order_by_cols: []
  row_limit: 1000
  server_page_length: 10
  order_desc: true
  table_timestamp_format: smart_date
  allow_render_html: true
  column_config:
    Avg_%_problems_attempted:
      d3NumberFormat: ',.1%'
  show_cell_bars: true
  color_pn: true
  conditional_formatting: []
  comparison_type: values
  extra_form_data: {}
  dashboards: []
query_context: '{"datasource":{"id":66,"type":"table"},"force":false,"queries":[{"filters":[],"extras":{"having":"","where":""},"applied_time_extras":{},"columns":["courserun_readable_id"],"metrics":[{"expressionType":"SQL","sqlExpression":"AVG(percetage_problems_attempted)","column":null,"aggregate":null,"datasourceWarning":false,"hasCustomLabel":true,"label":"Avg_%_problems_attempted","optionName":"metric_v0x9x3vkxs_lyd8fkz8ah"}],"orderby":[[{"expressionType":"SQL","sqlExpression":"AVG(percetage_problems_attempted)","column":null,"aggregate":null,"datasourceWarning":false,"hasCustomLabel":true,"label":"Avg_%_problems_attempted","optionName":"metric_v0x9x3vkxs_lyd8fkz8ah"},false]],"annotation_layers":[],"row_limit":1000,"series_limit":0,"order_desc":true,"url_params":{},"custom_params":{},"custom_form_data":{},"post_processing":[],"time_offsets":[]}],"form_data":{"datasource":"66__table","viz_type":"table","slice_id":90,"query_mode":"aggregate","groupby":["courserun_readable_id"],"time_grain_sqla":"P1D","temporal_columns_lookup":{},"metrics":[{"expressionType":"SQL","sqlExpression":"AVG(percetage_problems_attempted)","column":null,"aggregate":null,"datasourceWarning":false,"hasCustomLabel":true,"label":"Avg_%_problems_attempted","optionName":"metric_v0x9x3vkxs_lyd8fkz8ah"}],"all_columns":[],"percent_metrics":[],"adhoc_filters":[],"order_by_cols":[],"row_limit":1000,"server_page_length":10,"order_desc":true,"table_timestamp_format":"smart_date","allow_render_html":true,"column_config":{"Avg_%_problems_attempted":{"d3NumberFormat":",.1%"}},"show_cell_bars":true,"color_pn":true,"conditional_formatting":[],"comparison_type":"values","extra_form_data":{},"dashboards":[],"force":false,"result_format":"json","result_type":"full"},"result_format":"json","result_type":"full"}'
cache_timeout: null
uuid: 1e30a45b-d97d-4f44-ac2c-1d9de9e05bc1
version: 1.0.0
dataset_uuid: d763f86e-5c1b-4996-9b35-f8cb13947f11
