slice_name: Problem Results
description: null
certified_by: null
certification_details: null
viz_type: table
params:
  datasource: 14__table
  viz_type: table
  slice_id: 51
  query_mode: aggregate
  groupby:
  - courserun_readable_id
  - problem_name
  time_grain_sqla: P1D
  temporal_columns_lookup: {}
  metrics:
  - expressionType: SQL
    sqlExpression: SUM(case when problem_success= 'correct' then 1 else 0 end)
    column: null
    aggregate: null
    datasourceWarning: false
    hasCustomLabel: true
    label: Problem_Correct_Count
    optionName: metric_xj16o97mjh_2ccubhpfiei
  - expressionType: SQL
    sqlExpression: SUM(case when problem_success= 'incorrect' then 1 else 0 end)
    column: null
    aggregate: null
    datasourceWarning: false
    hasCustomLabel: true
    label: Problem_Incorrect_Count
    optionName: metric_6rnk0f08ehr_ozvuvrmyihp
  - expressionType: SQL
    sqlExpression: "     ROUND(SUM(case\n               when problem_success= 'correct'\
      \ then 1\n               else 0\n           end)  * 100.0 / count(*), 1)"
    column: null
    aggregate: null
    datasourceWarning: false
    hasCustomLabel: true
    label: Correct%
    optionName: metric_zuvu0a8x2os_w2hgh59mlan
  - expressionType: SQL
    sqlExpression: "     ROUND(SUM(case\n               when problem_success= 'incorrect'\
      \ then 1\n               else 0\n           end)  * 100.0 / count(*), 1)"
    column: null
    aggregate: null
    datasourceWarning: false
    hasCustomLabel: true
    label: Incorrect%
    optionName: metric_u8nnhrkt6h_20hi6ju9pr6
  all_columns: []
  percent_metrics: []
  adhoc_filters: []
  order_by_cols: []
  row_limit: 1000
  server_page_length: 10
  order_desc: true
  table_timestamp_format: smart_date
  show_cell_bars: true
  color_pn: true
  column_config:
    SUM(case when problem_success= 'correct' then 1 else 0 end)/count(*):
      d3NumberFormat: .2%
  conditional_formatting: []
  extra_form_data: {}
  dashboards:
  - 24
  comparison_type: values
query_context: '{"datasource":{"id":14,"type":"table"},"force":false,"queries":[{"filters":[],"extras":{"time_grain_sqla":"P1D","having":"","where":""},"applied_time_extras":{},"columns":["courserun_readable_id","problem_name"],"metrics":[{"aggregate":null,"column":null,"datasourceWarning":false,"expressionType":"SQL","hasCustomLabel":true,"label":"Problem_Correct_Count","optionName":"metric_xj16o97mjh_2ccubhpfiei","sqlExpression":"SUM(case
  when problem_success= ''correct'' then 1 else 0 end)"},{"aggregate":null,"column":null,"datasourceWarning":false,"expressionType":"SQL","hasCustomLabel":true,"label":"Problem_Incorrect_Count","optionName":"metric_6rnk0f08ehr_ozvuvrmyihp","sqlExpression":"SUM(case
  when problem_success= ''incorrect'' then 1 else 0 end)"},{"aggregate":null,"column":null,"datasourceWarning":false,"expressionType":"SQL","hasCustomLabel":true,"label":"Correct%","optionName":"metric_zuvu0a8x2os_w2hgh59mlan","sqlExpression":"     ROUND(SUM(case\n               when
  problem_success= ''correct'' then 1\n               else 0\n           end)  * 100.0
  / count(*), 1)"},{"aggregate":null,"column":null,"datasourceWarning":false,"expressionType":"SQL","hasCustomLabel":true,"label":"Incorrect%","optionName":"metric_u8nnhrkt6h_20hi6ju9pr6","sqlExpression":"     ROUND(SUM(case\n               when
  problem_success= ''incorrect'' then 1\n               else 0\n           end)  *
  100.0 / count(*), 1)"}],"orderby":[[{"aggregate":null,"column":null,"datasourceWarning":false,"expressionType":"SQL","hasCustomLabel":true,"label":"Problem_Correct_Count","optionName":"metric_xj16o97mjh_2ccubhpfiei","sqlExpression":"SUM(case
  when problem_success= ''correct'' then 1 else 0 end)"},false]],"annotation_layers":[],"row_limit":1000,"series_limit":0,"order_desc":true,"url_params":{},"custom_params":{},"custom_form_data":{},"post_processing":[]}],"form_data":{"adhoc_filters":[],"all_columns":[],"color_pn":true,"column_config":{"SUM(case
  when problem_success= ''correct'' then 1 else 0 end)/count(*)":{"d3NumberFormat":".2%"}},"conditional_formatting":[],"dashboards":[24],"datasource":"14__table","extra_form_data":{},"groupby":["courserun_readable_id","problem_name"],"metrics":[{"aggregate":null,"column":null,"datasourceWarning":false,"expressionType":"SQL","hasCustomLabel":true,"label":"Problem_Correct_Count","optionName":"metric_xj16o97mjh_2ccubhpfiei","sqlExpression":"SUM(case
  when problem_success= ''correct'' then 1 else 0 end)"},{"aggregate":null,"column":null,"datasourceWarning":false,"expressionType":"SQL","hasCustomLabel":true,"label":"Problem_Incorrect_Count","optionName":"metric_6rnk0f08ehr_ozvuvrmyihp","sqlExpression":"SUM(case
  when problem_success= ''incorrect'' then 1 else 0 end)"},{"aggregate":null,"column":null,"datasourceWarning":false,"expressionType":"SQL","hasCustomLabel":true,"label":"Correct%","optionName":"metric_zuvu0a8x2os_w2hgh59mlan","sqlExpression":"     ROUND(SUM(case\n               when
  problem_success= ''correct'' then 1\n               else 0\n           end)  * 100.0
  / count(*), 1)"},{"aggregate":null,"column":null,"datasourceWarning":false,"expressionType":"SQL","hasCustomLabel":true,"label":"Incorrect%","optionName":"metric_u8nnhrkt6h_20hi6ju9pr6","sqlExpression":"     ROUND(SUM(case\n               when
  problem_success= ''incorrect'' then 1\n               else 0\n           end)  *
  100.0 / count(*), 1)"}],"order_by_cols":[],"order_desc":true,"percent_metrics":[],"query_mode":"aggregate","row_limit":1000,"server_page_length":10,"show_cell_bars":true,"slice_id":53,"table_timestamp_format":"smart_date","temporal_columns_lookup":{},"time_grain_sqla":"P1D","viz_type":"table","force":false,"result_format":"json","result_type":"full"},"result_format":"json","result_type":"full"}'
cache_timeout: null
uuid: f07a7065-db29-4749-a4c6-d2c75c9d55f8
version: 1.0.0
dataset_uuid: 9e61277c-345a-4958-947b-2436eb4abf15
