slice_name: Problem Engagement Test Report
description: null
certified_by: null
certification_details: null
viz_type: table
params:
  datasource: 65__table
  viz_type: table
  slice_id: 93
  query_mode: aggregate
  groupby:
  - section_title
  temporal_columns_lookup: {}
  metrics:
  - aggregate: null
    column: null
    datasourceWarning: false
    expressionType: SQL
    hasCustomLabel: true
    label: '%_Problems_Attempted'
    optionName: metric_224mez8063pi_ew9xvc2r8v7
    sqlExpression: sum(cast(attepted_true_cnt as decimal(30,10)))/count(*)
  - aggregate: null
    column: null
    datasourceWarning: false
    expressionType: SQL
    hasCustomLabel: true
    label: '%_Problems_Correct'
    optionName: metric_nvhhsl8lrm_khgrazj7kpo
    sqlExpression: sum(cast(correct_true_cnt as decimal(30,10)))/count(*)
  all_columns: []
  percent_metrics: []
  adhoc_filters: []
  order_by_cols: []
  row_limit: 1000
  server_page_length: 10
  order_desc: true
  table_timestamp_format: smart_date
  allow_render_html: true
  column_config:
    '%_Problems_Attempted':
      d3NumberFormat: ',.1%'
    '%_Problems_Correct':
      d3NumberFormat: ',.1%'
  show_cell_bars: true
  color_pn: true
  comparison_color_scheme: Green
  conditional_formatting: []
  comparison_type: values
  extra_form_data: {}
  dashboards: []
query_context: '{"datasource":{"id":65,"type":"table"},"force":false,"queries":[{"filters":[],"extras":{"having":"","where":""},"applied_time_extras":{},"columns":["section_title"],"metrics":[{"aggregate":null,"column":null,"datasourceWarning":false,"expressionType":"SQL","hasCustomLabel":true,"label":"%_Problems_Attempted","optionName":"metric_224mez8063pi_ew9xvc2r8v7","sqlExpression":"sum(cast(attepted_true_cnt
  as decimal(30,10)))/count(*)"},{"aggregate":null,"column":null,"datasourceWarning":false,"expressionType":"SQL","hasCustomLabel":true,"label":"%_Problems_Correct","optionName":"metric_nvhhsl8lrm_khgrazj7kpo","sqlExpression":"sum(cast(correct_true_cnt
  as decimal(30,10)))/count(*)"}],"orderby":[[{"aggregate":null,"column":null,"datasourceWarning":false,"expressionType":"SQL","hasCustomLabel":true,"label":"%_Problems_Attempted","optionName":"metric_224mez8063pi_ew9xvc2r8v7","sqlExpression":"sum(cast(attepted_true_cnt
  as decimal(30,10)))/count(*)"},false]],"annotation_layers":[],"row_limit":1000,"series_limit":0,"order_desc":true,"url_params":{},"custom_params":{},"custom_form_data":{},"post_processing":[],"time_offsets":[]}],"form_data":{"datasource":"65__table","viz_type":"table","slice_id":93,"query_mode":"aggregate","groupby":["section_title"],"temporal_columns_lookup":{},"metrics":[{"aggregate":null,"column":null,"datasourceWarning":false,"expressionType":"SQL","hasCustomLabel":true,"label":"%_Problems_Attempted","optionName":"metric_224mez8063pi_ew9xvc2r8v7","sqlExpression":"sum(cast(attepted_true_cnt
  as decimal(30,10)))/count(*)"},{"aggregate":null,"column":null,"datasourceWarning":false,"expressionType":"SQL","hasCustomLabel":true,"label":"%_Problems_Correct","optionName":"metric_nvhhsl8lrm_khgrazj7kpo","sqlExpression":"sum(cast(correct_true_cnt
  as decimal(30,10)))/count(*)"}],"all_columns":[],"percent_metrics":[],"adhoc_filters":[],"order_by_cols":[],"row_limit":1000,"server_page_length":10,"order_desc":true,"table_timestamp_format":"smart_date","allow_render_html":true,"column_config":{"%_Problems_Attempted":{"d3NumberFormat":",.1%"},"%_Problems_Correct":{"d3NumberFormat":",.1%"__JINJA2_CLOSE__,"show_cell_bars":true,"color_pn":true,"comparison_color_scheme":"Green","conditional_formatting":[],"comparison_type":"values","extra_form_data":{},"dashboards":[],"force":false,"result_format":"json","result_type":"full"},"result_format":"json","result_type":"full"}'
cache_timeout: null
uuid: c05f9d50-bb41-4058-9f35-1ec46ec907c9
version: 1.0.0
dataset_uuid: b9e94ba2-f399-4210-b042-b8aaa4039f58
