slice_name: Student Level- Course Grades
description: null
certified_by: null
certification_details: null
viz_type: table
params:
  adhoc_filters: []
  all_columns: []
  allow_render_html: true
  annotation_layers: []
  color_pn: true
  comparison_color_scheme: Green
  comparison_type: values
  conditional_formatting: []
  dashboards:
  - 52
  datasource: 19__table
  extra_form_data: {}
  groupby:
  - platform
  - openedx_user_id
  - courserun_readable_id
  metrics:
  - aggregate: MAX
    column:
      advanced_data_type: null
      certification_details: null
      certified_by: null
      column_name: courserungrade_grade
      description: null
      expression: ''
      filterable: true
      groupby: true
      id: 2114
      is_certified: false
      is_dttm: false
      python_date_format: null
      type: DOUBLE
      type_generic: 0
      verbose_name: null
      warning_markdown: null
    datasourceWarning: false
    expressionType: SIMPLE
    hasCustomLabel: true
    label: course run grade
    optionName: metric_7opguvr6ke_52sgzthcrhp
    sqlExpression: null
  order_by_cols: []
  order_desc: true
  percent_metrics: []
  query_mode: aggregate
  row_limit: 50000
  server_page_length: 10
  show_cell_bars: false
  slice_id: 125
  table_timestamp_format: smart_date
  temporal_columns_lookup: {}
  timeseries_limit_metric:
    aggregate: COUNT_DISTINCT
    column:
      advanced_data_type: null
      certification_details: null
      certified_by: null
      column_name: courserun_readable_id
      description: null
      expression: ''
      filterable: true
      groupby: true
      id: 2106
      is_certified: false
      is_dttm: false
      python_date_format: null
      type: VARCHAR
      type_generic: 1
      verbose_name: null
      warning_markdown: null
    datasourceWarning: false
    expressionType: SIMPLE
    hasCustomLabel: false
    label: COUNT_DISTINCT(courserun_readable_id)
    optionName: metric_qtnfj8fbvep_fhcvg2t52l
    sqlExpression: null
  viz_type: table
query_context: '{"datasource": {"id": 19, "type": "table"}, "force": false, "queries":
  [{"filters": [], "extras": {"having": "", "where": ""}, "applied_time_extras": {},
  "columns": ["platform", "openedx_user_id", "courserun_readable_id"], "metrics":
  [{"aggregate": "MAX", "column": {"advanced_data_type": null, "certification_details":
  null, "certified_by": null, "column_name": "courserungrade_grade", "description":
  null, "expression": "", "filterable": true, "groupby": true, "id": 2114, "is_certified":
  false, "is_dttm": false, "python_date_format": null, "type": "DOUBLE", "type_generic":
  0, "verbose_name": null, "warning_markdown": null}, "datasourceWarning": false,
  "expressionType": "SIMPLE", "hasCustomLabel": true, "label": "course run grade",
  "optionName": "metric_7opguvr6ke_52sgzthcrhp", "sqlExpression": null}], "orderby":
  [[{"aggregate": "COUNT_DISTINCT", "column": {"advanced_data_type": null, "certification_details":
  null, "certified_by": null, "column_name": "courserun_readable_id", "description":
  null, "expression": "", "filterable": true, "groupby": true, "id": 2106, "is_certified":
  false, "is_dttm": false, "python_date_format": null, "type": "VARCHAR", "type_generic":
  1, "verbose_name": null, "warning_markdown": null}, "datasourceWarning": false,
  "expressionType": "SIMPLE", "hasCustomLabel": false, "label": "COUNT_DISTINCT(courserun_readable_id)",
  "optionName": "metric_qtnfj8fbvep_fhcvg2t52l", "sqlExpression": null}, false]],
  "annotation_layers": [], "row_limit": 50000, "series_limit": 0, "series_limit_metric":
  {"aggregate": "COUNT_DISTINCT", "column": {"advanced_data_type": null, "certification_details":
  null, "certified_by": null, "column_name": "courserun_readable_id", "description":
  null, "expression": "", "filterable": true, "groupby": true, "id": 2106, "is_certified":
  false, "is_dttm": false, "python_date_format": null, "type": "VARCHAR", "type_generic":
  1, "verbose_name": null, "warning_markdown": null}, "datasourceWarning": false,
  "expressionType": "SIMPLE", "hasCustomLabel": false, "label": "COUNT_DISTINCT(courserun_readable_id)",
  "optionName": "metric_qtnfj8fbvep_fhcvg2t52l", "sqlExpression": null}, "order_desc":
  true, "url_params": {}, "custom_params": {}, "custom_form_data": {}, "post_processing":
  [], "time_offsets": []}], "form_data": {"datasource": "19__table", "viz_type": "table",
  "slice_id": 125, "query_mode": "aggregate", "groupby": ["platform", "openedx_user_id",
  "courserun_readable_id"], "temporal_columns_lookup": {}, "metrics": [{"aggregate":
  "MAX", "column": {"advanced_data_type": null, "certification_details": null, "certified_by":
  null, "column_name": "courserungrade_grade", "description": null, "expression":
  "", "filterable": true, "groupby": true, "id": 2114, "is_certified": false, "is_dttm":
  false, "python_date_format": null, "type": "DOUBLE", "type_generic": 0, "verbose_name":
  null, "warning_markdown": null}, "datasourceWarning": false, "expressionType": "SIMPLE",
  "hasCustomLabel": true, "label": "course run grade", "optionName": "metric_7opguvr6ke_52sgzthcrhp",
  "sqlExpression": null}], "all_columns": [], "percent_metrics": [], "adhoc_filters":
  [], "timeseries_limit_metric": {"aggregate": "COUNT_DISTINCT", "column": {"advanced_data_type":
  null, "certification_details": null, "certified_by": null, "column_name": "courserun_readable_id",
  "description": null, "expression": "", "filterable": true, "groupby": true, "id":
  2106, "is_certified": false, "is_dttm": false, "python_date_format": null, "type":
  "VARCHAR", "type_generic": 1, "verbose_name": null, "warning_markdown": null}, "datasourceWarning":
  false, "expressionType": "SIMPLE", "hasCustomLabel": false, "label": "COUNT_DISTINCT(courserun_readable_id)",
  "optionName": "metric_qtnfj8fbvep_fhcvg2t52l", "sqlExpression": null}, "order_by_cols":
  [], "order_desc": true, "row_limit": 50000, "server_page_length": 10, "table_timestamp_format":
  "smart_date", "allow_render_html": true, "show_cell_bars": false, "color_pn": true,
  "comparison_color_scheme": "Green", "conditional_formatting": [], "comparison_type":
  "values", "extra_form_data": {}, "dashboards": [52], "force": false, "result_format":
  "json", "result_type": "full"}, "result_format": "json", "result_type": "full"}'
cache_timeout: null
uuid: 1ffe71c4-0732-4e17-a343-67ef3dd28f3d
version: 1.0.0
dataset_uuid: 65bdc57c-00f9-42d0-bd37-d4363532fd81
