slice_name: Users Receiving Program Certificates Over Time
description: null
certified_by: null
certification_details: null
viz_type: echarts_area
params:
  datasource: 59__table
  viz_type: echarts_area
  slice_id: 99
  x_axis:
    label: programcertificate_created_on
    sqlExpression: CAST(SUBSTRING(programcertificate_created_on, 1, 10) as date)
    expressionType: SQL
  time_grain_sqla: P1D
  metrics:
  - aggregate: COUNT_DISTINCT
    column:
      advanced_data_type: null
      certification_details: null
      certified_by: null
      column_name: user_email
      description: null
      expression: null
      filterable: true
      groupby: true
      id: 908
      is_certified: false
      is_dttm: false
      python_date_format: null
      type: VARCHAR
      type_generic: 1
      verbose_name: null
      warning_markdown: null
    datasourceWarning: false
    expressionType: SIMPLE
    hasCustomLabel: true
    label: User_Count
    optionName: metric_t38tros03wf_yuhssvzrko
    sqlExpression: null
  groupby: []
  adhoc_filters: []
  row_limit: 10000
  truncate_metric: true
  show_empty_columns: true
  comparison_type: values
  annotation_layers: []
  forecastPeriods: 10
  forecastInterval: 0.8
  x_axis_title_margin: 15
  y_axis_title_margin: 15
  y_axis_title_position: Left
  sort_series_type: sum
  color_scheme: supersetColors
  seriesType: line
  opacity: 0.2
  only_total: true
  markerSize: 6
  show_legend: true
  legendType: scroll
  legendOrientation: top
  x_axis_time_format: smart_date
  rich_tooltip: true
  showTooltipTotal: true
  showTooltipPercentage: true
  tooltipTimeFormat: smart_date
  y_axis_format: SMART_NUMBER
  truncateXAxis: true
  y_axis_bounds:
  - null
  - null
  extra_form_data: {}
  dashboards:
  - 34
query_context: '{"datasource":{"id":59,"type":"table"},"force":false,"queries":[{"filters":[],"extras":{"time_grain_sqla":"P1D","having":"","where":""},"applied_time_extras":{},"columns":[{"timeGrain":"P1D","columnType":"BASE_AXIS","label":"programcertificate_created_on","sqlExpression":"CAST(SUBSTRING(programcertificate_created_on,
  1, 10) as date)","expressionType":"SQL"}],"metrics":[{"aggregate":"COUNT_DISTINCT","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"user_email","description":null,"expression":null,"filterable":true,"groupby":true,"id":908,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":"VARCHAR","type_generic":1,"verbose_name":null,"warning_markdown":null},"datasourceWarning":false,"expressionType":"SIMPLE","hasCustomLabel":true,"label":"User_Count","optionName":"metric_t38tros03wf_yuhssvzrko","sqlExpression":null}],"orderby":[[{"aggregate":"COUNT_DISTINCT","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"user_email","description":null,"expression":null,"filterable":true,"groupby":true,"id":908,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":"VARCHAR","type_generic":1,"verbose_name":null,"warning_markdown":null},"datasourceWarning":false,"expressionType":"SIMPLE","hasCustomLabel":true,"label":"User_Count","optionName":"metric_t38tros03wf_yuhssvzrko","sqlExpression":null},false]],"annotation_layers":[],"row_limit":10000,"series_columns":[],"series_limit":0,"order_desc":true,"url_params":{},"custom_params":{},"custom_form_data":{},"time_offsets":[],"post_processing":[{"operation":"pivot","options":{"index":["programcertificate_created_on"],"columns":[],"aggregates":{"User_Count":{"operator":"mean"}},"drop_missing_columns":false}},{"operation":"flatten"}]}],"form_data":{"datasource":"59__table","viz_type":"echarts_area","slice_id":99,"x_axis":{"label":"programcertificate_created_on","sqlExpression":"CAST(SUBSTRING(programcertificate_created_on,
  1, 10) as date)","expressionType":"SQL"},"time_grain_sqla":"P1D","metrics":[{"aggregate":"COUNT_DISTINCT","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"user_email","description":null,"expression":null,"filterable":true,"groupby":true,"id":908,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":"VARCHAR","type_generic":1,"verbose_name":null,"warning_markdown":null},"datasourceWarning":false,"expressionType":"SIMPLE","hasCustomLabel":true,"label":"User_Count","optionName":"metric_t38tros03wf_yuhssvzrko","sqlExpression":null}],"groupby":[],"adhoc_filters":[],"row_limit":10000,"truncate_metric":true,"show_empty_columns":true,"comparison_type":"values","annotation_layers":[],"forecastPeriods":10,"forecastInterval":0.8,"x_axis_title_margin":15,"y_axis_title_margin":15,"y_axis_title_position":"Left","sort_series_type":"sum","color_scheme":"supersetColors","seriesType":"line","opacity":0.2,"only_total":true,"markerSize":6,"show_legend":true,"legendType":"scroll","legendOrientation":"top","x_axis_time_format":"smart_date","rich_tooltip":true,"showTooltipTotal":true,"showTooltipPercentage":true,"tooltipTimeFormat":"smart_date","y_axis_format":"SMART_NUMBER","truncateXAxis":true,"y_axis_bounds":[null,null],"extra_form_data":{},"dashboards":[34],"force":false,"result_format":"json","result_type":"full"},"result_format":"json","result_type":"full"}'
cache_timeout: null
uuid: faf44954-50d0-4135-9efc-b26ebc06e5d8
version: 1.0.0
dataset_uuid: cc496da8-03f6-43ea-9b6c-900ba695e4b6
