slice_name: Video Engagement By Subsection
description: null
certified_by: null
certification_details: null
viz_type: table
params:
  datasource: 92__table
  viz_type: table
  slice_id: 88
  query_mode: aggregate
  groupby:
  - subsection_title
  temporal_columns_lookup: {}
  metrics:
  - expressionType: SQL
    sqlExpression: SUM(case when estimated_time_played > video_duration then cast(video_duration
      as decimal(30,10)) else cast(estimated_time_played as decimal(30,10)) end)/nullif(SUM(cast(video_duration
      as decimal(30,10))), 0)
    column: null
    aggregate: null
    datasourceWarning: false
    hasCustomLabel: true
    label: Percent_watched
    optionName: metric_fys9aezohe7_snlqblipex
  - expressionType: SQL
    sqlExpression: SUM(cast(video_duration as decimal(30,10)))
    column: null
    aggregate: null
    datasourceWarning: false
    hasCustomLabel: true
    label: video_duration(seconds)
    optionName: metric_71gm5fxsicf_0cbnikhtw0nr
  - expressionType: SQL
    sqlExpression: SUM(case when estimated_time_played > video_duration then cast(video_duration
      as decimal(30,10)) else cast(estimated_time_played as decimal(30,10)) end)
    column: null
    aggregate: null
    datasourceWarning: false
    hasCustomLabel: true
    label: estimated_time_played(seconds)
    optionName: metric_ovpzqaz952_b4gf1fzjhha
  all_columns: []
  percent_metrics: []
  adhoc_filters: []
  timeseries_limit_metric: null
  order_by_cols: []
  row_limit: 1000
  table_timestamp_format: smart_date
  allow_render_html: true
  column_config:
    Percent_watched:
      d3NumberFormat: ',.1%'
  show_cell_bars: true
  color_pn: true
  comparison_color_scheme: Green
  conditional_formatting: []
  comparison_type: values
  extra_form_data: {}
  dashboards:
  - 45
query_context: '{"datasource":{"id":92,"type":"table"},"force":false,"queries":[{"filters":[],"extras":{"having":"","where":""},"applied_time_extras":{},"columns":["subsection_title"],"metrics":[{"expressionType":"SQL","sqlExpression":"SUM(case
  when estimated_time_played > video_duration then cast(video_duration as decimal(30,10))
  else cast(estimated_time_played as decimal(30,10)) end)/nullif(SUM(cast(video_duration
  as decimal(30,10))), 0)","column":null,"aggregate":null,"datasourceWarning":false,"hasCustomLabel":true,"label":"Percent_watched","optionName":"metric_fys9aezohe7_snlqblipex"},{"expressionType":"SQL","sqlExpression":"SUM(cast(video_duration
  as decimal(30,10)))","column":null,"aggregate":null,"datasourceWarning":false,"hasCustomLabel":true,"label":"video_duration(seconds)","optionName":"metric_71gm5fxsicf_0cbnikhtw0nr"},{"expressionType":"SQL","sqlExpression":"SUM(case
  when estimated_time_played > video_duration then cast(video_duration as decimal(30,10))
  else cast(estimated_time_played as decimal(30,10)) end)","column":null,"aggregate":null,"datasourceWarning":false,"hasCustomLabel":true,"label":"estimated_time_played(seconds)","optionName":"metric_ovpzqaz952_b4gf1fzjhha"}],"orderby":[[{"expressionType":"SQL","sqlExpression":"SUM(case
  when estimated_time_played > video_duration then cast(video_duration as decimal(30,10))
  else cast(estimated_time_played as decimal(30,10)) end)/nullif(SUM(cast(video_duration
  as decimal(30,10))), 0)","column":null,"aggregate":null,"datasourceWarning":false,"hasCustomLabel":true,"label":"Percent_watched","optionName":"metric_fys9aezohe7_snlqblipex"},false]],"annotation_layers":[],"row_limit":1000,"series_limit":0,"order_desc":true,"url_params":{},"custom_params":{},"custom_form_data":{},"post_processing":[],"time_offsets":[]}],"form_data":{"datasource":"92__table","viz_type":"table","slice_id":88,"query_mode":"aggregate","groupby":["subsection_title"],"temporal_columns_lookup":{},"metrics":[{"expressionType":"SQL","sqlExpression":"SUM(case
  when estimated_time_played > video_duration then cast(video_duration as decimal(30,10))
  else cast(estimated_time_played as decimal(30,10)) end)/nullif(SUM(cast(video_duration
  as decimal(30,10))), 0)","column":null,"aggregate":null,"datasourceWarning":false,"hasCustomLabel":true,"label":"Percent_watched","optionName":"metric_fys9aezohe7_snlqblipex"},{"expressionType":"SQL","sqlExpression":"SUM(cast(video_duration
  as decimal(30,10)))","column":null,"aggregate":null,"datasourceWarning":false,"hasCustomLabel":true,"label":"video_duration(seconds)","optionName":"metric_71gm5fxsicf_0cbnikhtw0nr"},{"expressionType":"SQL","sqlExpression":"SUM(case
  when estimated_time_played > video_duration then cast(video_duration as decimal(30,10))
  else cast(estimated_time_played as decimal(30,10)) end)","column":null,"aggregate":null,"datasourceWarning":false,"hasCustomLabel":true,"label":"estimated_time_played(seconds)","optionName":"metric_ovpzqaz952_b4gf1fzjhha"}],"all_columns":[],"percent_metrics":[],"adhoc_filters":[],"timeseries_limit_metric":null,"order_by_cols":[],"row_limit":1000,"table_timestamp_format":"smart_date","allow_render_html":true,"column_config":{"Percent_watched":{"d3NumberFormat":",.1%"}},"show_cell_bars":true,"color_pn":true,"comparison_color_scheme":"Green","conditional_formatting":[],"comparison_type":"values","extra_form_data":{},"dashboards":[45],"force":false,"result_format":"json","result_type":"full"},"result_format":"json","result_type":"full"}'
cache_timeout: null
uuid: 8146a868-1014-48d3-9e0d-8223de1ae1a9
version: 1.0.0
dataset_uuid: 4752cd11-a13e-4a8e-be31-4d9227b07ca2
