---
slice_name: Video Engagement per Section
description:
certified_by:
certification_details:
viz_type: echarts_timeseries_bar
params:
  adhoc_filters: []
  color_scheme: supersetColors
  comparison_type: values
  contributionMode:
  dashboards:
  - 24
  datasource: 43__table
  extra_form_data: {}
  form_data_bak:
    adhoc_filters: []
    bottom_margin: auto
    color_scheme: supersetColors
    columns: []
    dashboards:
    - 24
    datasource: 43__table
    extra_form_data: {}
    groupby:
    - section_title
    metrics:
    - aggregate:
      column:
      datasourceWarning: false
      expressionType: SQL
      hasCustomLabel: true
      label: Viewed At Least One Video
      optionName: metric_ilmj7tjqf9l_3gzz1vtb7cf
      sqlExpression: count(distinct(case when user_watched_video_count > 0 then user_email
        else null end))
    - aggregate:
      column:
      datasourceWarning: false
      expressionType: SQL
      hasCustomLabel: true
      label: Viewed All Videos
      optionName: metric_547rhhgzkqw_1i0h85x10p7
      sqlExpression: count(distinct(case when user_watched_video_count = total_video_count
        then user_email else null end))
    order_desc: false
    rich_tooltip: true
    row_limit: 10000
    show_legend: true
    slice_id: 44
    timeseries_limit_metric:
      aggregate: MIN
      column:
        advanced_data_type:
        certification_details:
        certified_by:
        column_name: max_coursestructure_block_index
        description:
        expression:
        filterable: true
        groupby: true
        id: 661
        is_certified: false
        is_dttm: false
        python_date_format:
        type: BIGINT
        type_generic: 0
        verbose_name:
        warning_markdown:
      datasourceWarning: false
      expressionType: SIMPLE
      hasCustomLabel: false
      label: MIN(max_coursestructure_block_index)
      optionName: metric_l5fmf7i5xb_rbdvkyjo29h
      sqlExpression:
    viz_type: dist_bar
    x_ticks_layout: auto
    y_axis_bounds:
    - 
    - 
    y_axis_format: SMART_NUMBER
  groupby: []
  markerEnabled: false
  metrics:
  - aggregate:
    column:
    datasourceWarning: false
    expressionType: SQL
    hasCustomLabel: true
    label: Viewed At Least One Video
    optionName: metric_ilmj7tjqf9l_3gzz1vtb7cf
    sqlExpression: count(distinct(case when user_watched_video_count > 0 then user_email
      else null end))
  - aggregate:
    column:
    datasourceWarning: false
    expressionType: SQL
    hasCustomLabel: true
    label: Viewed All Videos
    optionName: metric_547rhhgzkqw_1i0h85x10p7
    sqlExpression: count(distinct(case when user_watched_video_count = total_video_count
      then user_email else null end))
  order_desc: false
  queries_bak:
  - annotation_layers: []
    applied_time_extras: {}
    columns:
    - section_title
    custom_form_data: {}
    custom_params: {}
    extras:
      having: ''
      where: ''
    filters: []
    metrics:
    - aggregate:
      column:
      datasourceWarning: false
      expressionType: SQL
      hasCustomLabel: true
      label: Viewed At Least One Video
      optionName: metric_ilmj7tjqf9l_3gzz1vtb7cf
      sqlExpression: count(distinct(case when user_watched_video_count > 0 then user_email
        else null end))
    - aggregate:
      column:
      datasourceWarning: false
      expressionType: SQL
      hasCustomLabel: true
      label: Viewed All Videos
      optionName: metric_547rhhgzkqw_1i0h85x10p7
      sqlExpression: count(distinct(case when user_watched_video_count = total_video_count
        then user_email else null end))
    order_desc: false
    row_limit: 10000
    series_limit: 0
    series_limit_metric:
      aggregate: MIN
      column:
        advanced_data_type:
        certification_details:
        certified_by:
        column_name: max_coursestructure_block_index
        description:
        expression:
        filterable: true
        groupby: true
        id: 661
        is_certified: false
        is_dttm: false
        python_date_format:
        type: BIGINT
        type_generic: 0
        verbose_name:
        warning_markdown:
      datasourceWarning: false
      expressionType: SIMPLE
      hasCustomLabel: false
      label: MIN(max_coursestructure_block_index)
      optionName: metric_l5fmf7i5xb_rbdvkyjo29h
      sqlExpression:
    url_params: {}
  rich_tooltip: true
  row_limit: 10000
  show_legend: true
  slice_id: 44
  stack:
  timeseries_limit_metric:
    aggregate: MIN
    column:
      advanced_data_type:
      certification_details:
      certified_by:
      column_name: max_coursestructure_block_index
      description:
      expression:
      filterable: true
      groupby: true
      id: 661
      is_certified: false
      is_dttm: false
      python_date_format:
      type: BIGINT
      type_generic: 0
      verbose_name:
      warning_markdown:
    datasourceWarning: false
    expressionType: SIMPLE
    hasCustomLabel: false
    label: MIN(max_coursestructure_block_index)
    optionName: metric_l5fmf7i5xb_rbdvkyjo29h
    sqlExpression:
  truncateYAxis: true
  viz_type: echarts_timeseries_bar
  xAxisLabelRotation: 45
  x_axis: section_title
  x_axis_title_margin: auto
  y_axis_bounds:
  - 
  - 
  y_axis_format: SMART_NUMBER
  zoomable: false
query_context: '{"datasource": {"id": 43, "type": "table"}, "force": false, "queries":
  [{"filters": [], "extras": {"having": "", "where": ""}, "applied_time_extras": {},
  "columns": [{"columnType": "BASE_AXIS", "sqlExpression": "section_title", "label":
  "section_title", "expressionType": "SQL"}], "metrics": [{"aggregate": null, "column":
  null, "datasourceWarning": false, "expressionType": "SQL", "hasCustomLabel": true,
  "label": "Viewed At Least One Video", "optionName": "metric_ilmj7tjqf9l_3gzz1vtb7cf",
  "sqlExpression": "count(distinct(case when user_watched_video_count > 0 then user_email
  else null end))"}, {"aggregate": null, "column": null, "datasourceWarning": false,
  "expressionType": "SQL", "hasCustomLabel": true, "label": "Viewed All Videos", "optionName":
  "metric_547rhhgzkqw_1i0h85x10p7", "sqlExpression": "count(distinct(case when user_watched_video_count
  = total_video_count then user_email else null end))"}], "annotation_layers": [],
  "row_limit": 10000, "series_limit": 0, "order_desc": false, "url_params": {}, "custom_params":
  {}, "series_limit_metric": {"aggregate": "MIN", "column": {"advanced_data_type":
  null, "certification_details": null, "certified_by": null, "column_name": "max_coursestructure_block_index",
  "description": null, "expression": null, "filterable": true, "groupby": true, "id":
  661, "is_certified": false, "is_dttm": false, "python_date_format": null, "type":
  "BIGINT", "type_generic": 0, "verbose_name": null, "warning_markdown": null}, "datasourceWarning":
  false, "expressionType": "SIMPLE", "hasCustomLabel": false, "label": "MIN(max_coursestructure_block_index)",
  "optionName": "metric_l5fmf7i5xb_rbdvkyjo29h", "sqlExpression": null}, "custom_form_data":
  {}, "series_columns": [], "orderby": [[{"aggregate": "MIN", "column": {"advanced_data_type":
  null, "certification_details": null, "certified_by": null, "column_name": "max_coursestructure_block_index",
  "description": null, "expression": null, "filterable": true, "groupby": true, "id":
  661, "is_certified": false, "is_dttm": false, "python_date_format": null, "type":
  "BIGINT", "type_generic": 0, "verbose_name": null, "warning_markdown": null}, "datasourceWarning":
  false, "expressionType": "SIMPLE", "hasCustomLabel": false, "label": "MIN(max_coursestructure_block_index)",
  "optionName": "metric_l5fmf7i5xb_rbdvkyjo29h", "sqlExpression": null}, true]], "time_offsets":
  [], "post_processing": [{"operation": "pivot", "options": {"index": ["section_title"],
  "columns": [], "aggregates": {"Viewed At Least One Video": {"operator": "mean"},
  "Viewed All Videos": {"operator": "mean"__JINJA2_CLOSE__, "drop_missing_columns":
  true__JINJA2_CLOSE__, {"operation": "flatten"}]}], "form_data": {"datasource": "43__table",
  "viz_type": "echarts_timeseries_bar", "slice_id": 44, "metrics": [{"aggregate":
  null, "column": null, "datasourceWarning": false, "expressionType": "SQL", "hasCustomLabel":
  true, "label": "Viewed At Least One Video", "optionName": "metric_ilmj7tjqf9l_3gzz1vtb7cf",
  "sqlExpression": "count(distinct(case when user_watched_video_count > 0 then user_email
  else null end))"}, {"aggregate": null, "column": null, "datasourceWarning": false,
  "expressionType": "SQL", "hasCustomLabel": true, "label": "Viewed All Videos", "optionName":
  "metric_547rhhgzkqw_1i0h85x10p7", "sqlExpression": "count(distinct(case when user_watched_video_count
  = total_video_count then user_email else null end))"}], "adhoc_filters": [], "groupby":
  [], "row_limit": 10000, "timeseries_limit_metric": {"aggregate": "MIN", "column":
  {"advanced_data_type": null, "certification_details": null, "certified_by": null,
  "column_name": "max_coursestructure_block_index", "description": null, "expression":
  null, "filterable": true, "groupby": true, "id": 661, "is_certified": false, "is_dttm":
  false, "python_date_format": null, "type": "BIGINT", "type_generic": 0, "verbose_name":
  null, "warning_markdown": null}, "datasourceWarning": false, "expressionType": "SIMPLE",
  "hasCustomLabel": false, "label": "MIN(max_coursestructure_block_index)", "optionName":
  "metric_l5fmf7i5xb_rbdvkyjo29h", "sqlExpression": null}, "order_desc": false, "color_scheme":
  "supersetColors", "show_legend": true, "rich_tooltip": true, "y_axis_format": "SMART_NUMBER",
  "y_axis_bounds": [null, null], "x_axis_title_margin": "auto", "xAxisLabelRotation":
  45, "extra_form_data": {}, "dashboards": [24], "contributionMode": null, "zoomable":
  false, "markerEnabled": false, "truncateYAxis": true, "comparison_type": "values",
  "x_axis": "section_title", "stack": null}, "result_format": "json", "result_type":
  "full"}'
cache_timeout:
uuid: ac95bf65-b2ea-4e6a-9fdf-8fdff4758f5e
version: 1.0.0
dataset_uuid: bf17ec0d-2a0a-4f97-ab5b-ae2df862d4b5
