slice_name: Video Engagement per Section
description: null
certified_by: null
certification_details: null
viz_type: echarts_timeseries_bar
params:
  adhoc_filters: []
  annotation_layers: []
  color_scheme: supersetColors
  contributionMode: null
  dashboards:
  - 26
  datasource: 43__table
  extra_form_data: {}
  forecastInterval: 0.8
  forecastPeriods: 10
  groupby: []
  legendOrientation: top
  legendType: scroll
  metrics:
  - aggregate: null
    column: null
    datasourceWarning: false
    expressionType: SQL
    hasCustomLabel: true
    label: Viewed At Least One Video
    optionName: metric_ilmj7tjqf9l_3gzz1vtb7cf
    sqlExpression: count(distinct(case when user_watched_video_count > 0 then user_email
      else null end))
  - aggregate: null
    column: null
    datasourceWarning: false
    expressionType: SQL
    hasCustomLabel: true
    label: Viewed All Videos
    optionName: metric_547rhhgzkqw_1i0h85x10p7
    sqlExpression: count(distinct(case when user_watched_video_count = total_video_count
      then user_email else null end))
  only_total: true
  order_desc: false
  orientation: vertical
  rich_tooltip: true
  row_limit: 10000
  showTooltipTotal: false
  show_empty_columns: true
  show_legend: true
  slice_id: 57
  sort_series_type: sum
  stack: null
  time_shift_color: true
  timeseries_limit_metric:
    aggregate: MIN
    column:
      advanced_data_type: null
      certification_details: null
      certified_by: null
      column_name: max_coursestructure_block_index
      description: null
      expression: null
      filterable: true
      groupby: true
      id: 661
      is_certified: false
      is_dttm: false
      python_date_format: null
      type: BIGINT
      type_generic: 0
      verbose_name: null
      warning_markdown: null
    datasourceWarning: false
    expressionType: SIMPLE
    hasCustomLabel: false
    label: MIN(max_coursestructure_block_index)
    optionName: metric_l5fmf7i5xb_rbdvkyjo29h
    sqlExpression: null
  tooltipTimeFormat: smart_date
  truncateXAxis: true
  truncateYAxis: true
  truncate_metric: true
  viz_type: echarts_timeseries_bar
  xAxisLabelRotation: 45
  x_axis: section_title
  x_axis_sort: name
  x_axis_sort_asc: true
  x_axis_time_format: smart_date
  x_axis_title_margin: auto
  y_axis_bounds:
  - null
  - null
  y_axis_format: SMART_NUMBER
  y_axis_title_margin: 30
  y_axis_title_position: Left
  zoomable: false
query_context: '{"datasource":{"id":43,"type":"table"},"force":false,"queries":[{"filters":[],"extras":{"having":"","where":""},"applied_time_extras":{},"columns":[{"columnType":"BASE_AXIS","sqlExpression":"section_title","label":"section_title","expressionType":"SQL"}],"metrics":[{"aggregate":null,"column":null,"datasourceWarning":false,"expressionType":"SQL","hasCustomLabel":true,"label":"Viewed
  At Least One Video","optionName":"metric_ilmj7tjqf9l_3gzz1vtb7cf","sqlExpression":"count(distinct(case
  when user_watched_video_count > 0 then user_email else null end))"},{"aggregate":null,"column":null,"datasourceWarning":false,"expressionType":"SQL","hasCustomLabel":true,"label":"Viewed
  All Videos","optionName":"metric_547rhhgzkqw_1i0h85x10p7","sqlExpression":"count(distinct(case
  when user_watched_video_count = total_video_count then user_email else null end))"}],"orderby":[[{"aggregate":"MIN","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"max_coursestructure_block_index","description":null,"expression":null,"filterable":true,"groupby":true,"id":661,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":"BIGINT","type_generic":0,"verbose_name":null,"warning_markdown":null},"datasourceWarning":false,"expressionType":"SIMPLE","hasCustomLabel":false,"label":"MIN(max_coursestructure_block_index)","optionName":"metric_l5fmf7i5xb_rbdvkyjo29h","sqlExpression":null},true]],"annotation_layers":[],"row_limit":10000,"series_columns":[],"series_limit":0,"series_limit_metric":{"aggregate":"MIN","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"max_coursestructure_block_index","description":null,"expression":null,"filterable":true,"groupby":true,"id":661,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":"BIGINT","type_generic":0,"verbose_name":null,"warning_markdown":null},"datasourceWarning":false,"expressionType":"SIMPLE","hasCustomLabel":false,"label":"MIN(max_coursestructure_block_index)","optionName":"metric_l5fmf7i5xb_rbdvkyjo29h","sqlExpression":null},"order_desc":false,"url_params":{},"custom_params":{},"custom_form_data":{},"time_offsets":[],"post_processing":[{"operation":"pivot","options":{"index":["section_title"],"columns":[],"aggregates":{"Viewed
  At Least One Video":{"operator":"mean"},"Viewed All Videos":{"operator":"mean"}},"drop_missing_columns":false}},{"operation":"flatten"}]}],"form_data":{"datasource":"43__table","viz_type":"echarts_timeseries_bar","slice_id":57,"x_axis":"section_title","x_axis_sort_asc":true,"x_axis_sort_series":"name","x_axis_sort_series_ascending":true,"metrics":[{"aggregate":null,"column":null,"datasourceWarning":false,"expressionType":"SQL","hasCustomLabel":true,"label":"Viewed
  At Least One Video","optionName":"metric_ilmj7tjqf9l_3gzz1vtb7cf","sqlExpression":"count(distinct(case
  when user_watched_video_count > 0 then user_email else null end))"},{"aggregate":null,"column":null,"datasourceWarning":false,"expressionType":"SQL","hasCustomLabel":true,"label":"Viewed
  All Videos","optionName":"metric_547rhhgzkqw_1i0h85x10p7","sqlExpression":"count(distinct(case
  when user_watched_video_count = total_video_count then user_email else null end))"}],"groupby":[],"contributionMode":null,"adhoc_filters":[],"timeseries_limit_metric":{"aggregate":"MIN","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"max_coursestructure_block_index","description":null,"expression":null,"filterable":true,"groupby":true,"id":661,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":"BIGINT","type_generic":0,"verbose_name":null,"warning_markdown":null},"datasourceWarning":false,"expressionType":"SIMPLE","hasCustomLabel":false,"label":"MIN(max_coursestructure_block_index)","optionName":"metric_l5fmf7i5xb_rbdvkyjo29h","sqlExpression":null},"order_desc":false,"row_limit":10000,"truncate_metric":true,"show_empty_columns":true,"annotation_layers":[],"forecastPeriods":10,"forecastInterval":0.8,"orientation":"vertical","x_axis_title_margin":"auto","y_axis_title_margin":30,"y_axis_title_position":"Left","sort_series_type":"sum","color_scheme":"supersetColors","time_shift_color":true,"stack":null,"only_total":true,"zoomable":false,"show_legend":true,"legendType":"scroll","legendOrientation":"top","x_axis_time_format":"smart_date","xAxisLabelRotation":45,"y_axis_format":"SMART_NUMBER","truncateYAxis":true,"y_axis_bounds":[null,null],"truncateXAxis":true,"rich_tooltip":true,"showTooltipTotal":false,"tooltipTimeFormat":"smart_date","extra_form_data":{},"dashboards":[26],"force":false,"result_format":"json","result_type":"full"},"result_format":"json","result_type":"full"}'
cache_timeout: null
uuid: 52f9966c-2de9-41fd-b29a-ccd1781696cb
version: 1.0.0
dataset_uuid: bf17ec0d-2a0a-4f97-ab5b-ae2df862d4b5
