---
slice_name: xPRO Product List - Standard Products Only
description:
certified_by:
certification_details:
viz_type: table
params:
  datasource: 42__table
  viz_type: table
  slice_id: 41
  query_mode: raw
  groupby:
  - productid
  time_grain_sqla: P1D
  temporal_columns_lookup: {}
  all_columns:
  - productid
  - product_name
  - product_readable_id
  - product_type
  - list_price
  - product_description
  - start_date
  - end_date
  - enrollment_start
  - enrollment_end
  - link
  percent_metrics: []
  adhoc_filters: []
  order_by_cols: []
  row_limit: 1000
  server_page_length: 10
  order_desc: true
  table_timestamp_format: smart_date
  show_cell_bars: true
  color_pn: true
  extra_form_data: {}
  dashboards: []
  comparison_type: values
query_context: '{"datasource":{"id":42,"type":"table"},"force":false,"queries":[{"filters":[],"extras":{"time_grain_sqla":"P1D","having":"","where":""},"applied_time_extras":{},"columns":["productid","product_name","product_readable_id","product_type","list_price","product_description","start_date","end_date","enrollment_start","enrollment_end","link"],"orderby":[],"annotation_layers":[],"row_limit":1000,"series_limit":0,"order_desc":true,"url_params":{},"custom_params":{},"custom_form_data":{},"post_processing":[]}],"form_data":{"datasource":"42__table","viz_type":"table","slice_id":41,"query_mode":"raw","groupby":["productid"],"time_grain_sqla":"P1D","temporal_columns_lookup":{},"all_columns":["productid","product_name","product_readable_id","product_type","list_price","product_description","start_date","end_date","enrollment_start","enrollment_end","link"],"percent_metrics":[],"adhoc_filters":[],"order_by_cols":[],"row_limit":1000,"server_page_length":10,"order_desc":true,"table_timestamp_format":"smart_date","show_cell_bars":true,"color_pn":true,"extra_form_data":{},"dashboards":[],"force":false,"result_format":"json","result_type":"full","include_time":false},"result_format":"json","result_type":"full"}'
cache_timeout:
uuid: 244158fe-79de-4ad8-bc53-f82ef3f32ffa
version: 1.0.0
dataset_uuid: dc5b25f5-cf3a-41b4-9b15-4b58532da463
